### ISSUE TITLE
Projects won't load in VS2019

### ISSUE THREAD

**Issue by rmagruder** [dotnet-architecture/eShopOnContainers#1013]
Same machine as installed VS2017 which DOES load the ServiceAndWebApps solution just fine....VS2019 will NOT. Also verified on another machine.  VS2019 complains that the proper .net SDK could not be found and the project cannot be loaded.  But again, same machine works fine on VS2017, so the SDK's are properly installed.

This could well be a VS2019 bug but other .net core projects seem to load fine it.  This one, however, just won't.

**Comment by MrDywar** [comment]
I was able to build it in VS 2019.
1) Install ".NET Core 2.2" for your VS 2019 instance using - "Visual Studio Installer".
2) If it fails on "Devspaces.Support", just add it into solution (add existing project).

Mb it will help you.

PS
But i had another issue with localhost vs separete IP (think so), because i'm using docker toolbox with VirtualBox. Some services works, some one not. Trying to solve it.

**Comment by mvelosop** [comment]
Hi @MrDywar,

Thanks for the tip above!

Could you post the error message(s) you get.

It's important to ensure the 4 GB RAM as per https://github.com/dotnet-architecture/eShopOnContainers/wiki#setting-up-your-development-environment-for-eshoponcontainers

Hope this helps.

**Comment by MrDywar** [comment]
Hi @mvelosop,

Thanks for link, i did not read all docs before i started :)

As i use docker toolbox the https://github.com/dotnet-architecture/eShopOnContainers/wiki/03.-Setting-the-eShopOnContainers-solution-up-in-a-Windows-CLI-environment-(dotnet-CLI,-Docker-CLI-and-VS-Code) did the trick!

- If i open solution from "VS 2019", it automatically starting containers and nothing works (because of docker toolbox i think).
- If i run "docker-compose up", it's working well. I was able to login to SPA as demouser and place an order.

Docker for Windows (localhost) and docker toolbox (192.168.99.100) difference bring some erros, like 4хх on images. But it's OK.

P.S.
ESHOP_EXTERNAL_DNS_NAME_OR_IP was updated to 192.168.99.100.

May be i will update to Win Pro, and start using Hyper-V. It will reduce problems today and in the future.

**Comment by mvelosop** [comment]
I don't like to run the app from VS and to avoid the app from starting you can configure VS like this:

![image](https://user-images.githubusercontent.com/7357806/57077138-3095a400-6ce3-11e9-9d74-f0b2817dd1f6.png)

Hope this helps.

**Comment by nishanil** [comment]
@mvelosop This might be a good tip to add it to our wiki?

**Comment by mvelosop** [comment]
Closing this issue now, but feel free to comment, will reopen if needed.

**Comment by TNadir** [comment]
![image](https://user-images.githubusercontent.com/34626886/66993196-d1cab800-f0d3-11e9-880d-71a18e76e20b.png)

**Comment by TNadir** [comment]
I have occured problem with SQL server
