### ISSUE TITLE
Markup is incorrect

### ISSUE THREAD

**Issue by dorward** [dotnet-architecture/eShopOnContainers#1017]
Regarding: https://github.com/dotnet-architecture/eShopOnContainers/blob/fb6d972d553dea8eb28b1c91a6b4d8606302fadf/src/Web/WebMVC/Views/Order/Index.cshtml#L18

Markup should describe the semantics of the content. This is not a series of articles with sections. It is tabular. Use a table.

**Comment by mvelosop** [comment]
Hi @dorward, that's a good point indeed 👍

There's an idea to update the general looks of the app and that would be a great time to do that, since it's a low priority item now.

I just added this to the [roadmap](https://github.com/dotnet-architecture/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases#vnext) so I'm closing this issue now.

Thanks 😊
