### ISSUE TITLE
Using sections and articles instead of divs or tables in views

### ISSUE THREAD

**Issue by w00519772** [dotnet-architecture/eShopOnContainers#1018]
Thanks again once again for developing this app.  I was recently reviewing the code in the view of the Ordering micro service: https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Web/WebMVC/Views/Order/Index.cshtml

May I ask why articles and sections were used instead of tables or divs?

**Comment by mvelosop** [comment]
Hi @w00519772, 

I really don't have an answer for that, but it really shouldn't be so.

This is a very low priority issue so it won't be fixed now, but I've just included it in the [roadmap](https://github.com/dotnet-architecture/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases#vnext), because there's the idea to revamp the whole UI, and then it'd be the best time to do it.

Thanks 😊

**Comment by w00519772** [comment]
@mvelosop, are you able to have a look at my other question here: https://github.com/dotnet-architecture/eShopOnContainers/issues/1187.  I am struggling to debug the WebSPA project.  Thanks again.
