### ISSUE TITLE
DB Creation

### ISSUE THREAD

**Issue by eliassal** [dotnet-architecture/eShopOnContainers#1032]
Hi, Can you please let me know how the DB CatalogDB is created? is there a script to populate?
I see a class called CatalogContextSeed, running the application it does not do anything
Thanks

**Comment by mvelosop** [comment]
Hi @eliassal,

This app uses Entity Framework Core Code First, which means that you:

1. Creating the model classes for your app
2. Create the initial migration (EF Core generates the code needed to create the DB and the tables, based on the model classes)
3. Run the app, which creates the DB on startup.

- You can take a look of all Catalog migrations in: https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/src/Services/Catalog/Catalog.API/Infrastructure/CatalogMigrations
- The current Catalog database model (the result of all aggregated migrations) in: https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Catalog/Catalog.API/Infrastructure/CatalogMigrations/CatalogContextModelSnapshot.cs

Migrations run when the app starts, from here:

https://github.com/dotnet-architecture/eShopOnContainers/blob/ec0c15ac84996df6311011239f5712c998e99e2c/src/Services/Catalog/Catalog.API/Program.cs#L31-L42

You might want to begin with a nice tutorial to get a better grasp of the important concepts in this [ASP.NET Core Razor Pages with EF Core tutorial](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/?view=aspnetcore-2.2)

Hope this helps.

**Comment by eliassal** [comment]
Ok thanks for your prompt response, I will do. However, I updated my project (Catalog.Api) with the piece of code from eshoponcontainer of code, added needed reference, deleted/commented the line 
.MigrateDbContext<IntegrationEventLogContext>((_, __) => { }); 
in program.cs
ran the application a container is created but still DB tables still not created

**Comment by mvelosop** [comment]
Well, as you might have guessed, it's just that very same line you commented out, the one that creates the DB, the tables and seeds the initial data 😉

**Comment by mvelosop** [comment]
Closing this issue as not related to eShopOnContainers.

**Comment by eliassal** [comment]
Hold a moment, even with this line, DB tables are not getting created. DB is created but not tables

**Comment by eliassal** [comment]
Hold a moment, tables are not getting created only DB when I delete it from server.
I debugged, execution goes through the line 
context.Database.Migrate();
in IWebHostExtensions.cs

so really I did everything I think possible but there is something wrong somewhere

**Comment by mvelosop** [comment]
I don't doubt there's something wrong, but it's not related to eShopOnContainers, for when I drop the database everything gets created as always in the original code.

I really suggest you to invest some time with the tutorials, to get the grasp of what's happening.

**Comment by mvelosop** [comment]
It's **eShopOnContainers-ServicesAndWebApps.sln** but I recommend that you run get it running it from the command line: https://github.com/dotnet-architecture/eShopOnContainers/wiki/03.-Setting-the-eShopOnContainers-solution-up-in-a-Windows-CLI-environment-(dotnet-CLI,-Docker-CLI-and-VS-Code)

**Comment by eliassal** [comment]
Miguel, running 
Docker-compose build
gives always an error as follows 
Step 4/6 : EXPOSE 80
 ---> Using cache
 ---> 8e5c7384367f
Step 5/6 : COPY ${source:-obj/Docker/publish} .
ERROR: Service 'webstatus' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder970337066/obj/Docker/publish: no such file or directory
PS C:\Users\salam.SALAM\Source\Repos\eShopOnContainers-dev> docker ps
I rebuild webstatus, then I get the same message  for payment.api. and it continues like this

In VS it builds correctly and 14 containers are launched, however, in Chrome I get a nice eshopcontainers page with all materials photos displayed, I am happy.

Now, tell me please, how can I access the sql server or rabbit or management server? For example, can I access sql with ssms?
This application seems to me a little bit very complkex for beginners, is there somewhere a step-by-step guide how this application was build to follow and understand?

**Comment by eliassal** [comment]
Another  thing Miguel, I stopped debugging in VS but all 14 containers launched by VS were still there, so VS does not stop it seems containers launched  by clicking docker-compose, is this for performance reasons?

**Comment by mvelosop** [comment]
Hi, a bunch of questions there! 😉

- This is a "simplified" sample of a microservices application, but definitely it's not "simple".
- If you are getting into microservices I recommend that you start by reading the [e-book](https://aka.ms/microservicesebook) (the latest version 😉) or the [on-line guide](https://docs.microsoft.com/dotnet/standard/microservices-architecture/).
- It's important that you follow the setup instructions in the wiki: https://github.com/dotnet-architecture/eShopOnContainers/wiki/02.-Setting-eShopOnContainers-in-a-Visual-Studio-2017-environment.
- Change these [settings to configure Docker in VS](https://github.com/dotnet-architecture/eShopOnContainers/issues/1013#issuecomment-488664792).
- There's no step-by-step, but the [architecture overview in the README](https://github.com/dotnet-architecture/eShopOnContainers#architecture-overview) should help.
- You can access the following resources within the app (You can use 10.0.75.1 or localhost):
  - Logging: http://10.0.75.1:5340/
  - RabbitMQ admin page: http://10.0.75.1:15672/ (credentials: guest/guest)
  - Heathchecks: http://10.0.75.1:5107/
- The error with `docker-compose` is probably due to the VS containers still running, you can stop them with the command `docker container stop $(docker ps -q)`.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now, will reopen if needed.
