### ISSUE TITLE
Fluent Validator - every validator constructors getting invoked in every API call

### ISSUE THREAD

**Issue by francisminu** [dotnet-architecture/eShopOnContainers#1041]
Hi,

This is actually not an issue with this project, this is just a question we have regarding Fluent Validator implementation.
We have used Fluent Validators in our project keeping eshopOnContainers as a reference. We have followed the exact same steps for registering the Validators and the Validator behavior. One behavior that we are seeing at present is that,every validator class constructor gets invoked on every API Call. Lets say there are 2 api endpoints and for each, we have a validator. Both the command and response is all different for both of these. But, when we make a call to Api1, we see that both the constructors of Validator1 and Validator2 are getting invoked, though only one Validator gets invoked. Could you please let us know if the same happens in this project as well?

Thanks,
Minu

**Comment by fr4nky80** [comment]
Have you checked that your validators are in the same assembly?

**Comment by francisminu** [comment]
Yes, they are all in the same assembly

**Comment by mvelosop** [comment]
Hi @francisminu,

Nope, that doesn't happen in eShopOnContainers.

To find out I added logging on validator constructors like this:

```cs
public CreateOrderCommandValidator(ILogger<CreateOrderCommandValidator> logger)
{
    RuleFor(command => command.City).NotEmpty();
    //...
    RuleFor(command => command.OrderItems).Must(ContainOrderItems).WithMessage("No order items found");

    logger.LogTrace("----- INSTANCE CREATED - {ClassName}", GetType().Name);
}
```

Then updated `docker-compose.override.yml` to enable trace level logging for Ordering.API namespace:

```yml
ordering.api:
  environment:
    - ASPNETCORE_ENVIRONMENT=Development
    #...
    - Serilog__MinimumLevel__Override__Ordering.API=Verbose
  ports:
    #...
```

And then got this log trace:

![image](https://user-images.githubusercontent.com/7357806/57852768-f268ac00-77db-11e9-8267-a9832c7b44bb.png)

Since this was happening in the same integration event processing context, I tried cancelling the order, which is definitely a different request and got just the same. So only the required validator classes are instantiated:

![image](https://user-images.githubusercontent.com/7357806/57853316-58096800-77dd-11e9-92f2-77343aeef995.png)

I'll create a PR later with the changes.

Hope this helps.

**Comment by mvelosop** [comment]
I'm closing this issue now, but feel free to comment. will reopen if needed.

**Comment by francisminu** [comment]
Thanks mvelosop. We mitigated the issue by implementing an IValidatorFactory and now only the required instances are being created.

**Comment by mvelosop** [comment]
Glad you could solve it!

Anyway it might have to do with these lines if you're using ASP.NET Core DI:

https://github.com/dotnet-architecture/eShopOnContainers/blob/93727c259c51e9690c88bf47b1fcbf0daffe9c14/src/Services/Ordering/Ordering.API/Infrastructure/AutofacModules/MediatorModule.cs#L29-L32

I think I read @jbogard somewhere, explaining that native DI from ASP.NET Core couldn't solve that kind of registrations, for a MediatR related issue, but I'm not sure.
