### ISSUE TITLE
Why IEventBus.Publish is not asynchronous

### ISSUE THREAD

**Issue by mohammed-fuad** [dotnet-architecture/eShopOnContainers#1047]
Q1) I've noticed Publish method in IEventBus interface isn't asynchronous, is there a reason for that?.

Q2) Also why MediatR is not used instead of such pattern, since events and handlers subscription is dynamically registered.

**Comment by mvelosop** [comment]
Hi @mohammed-fuad, those are good questions! 👍

For the  first one, it's just a matter of adapting to RabbitMQ, because its .NET client doesn't support async publishing.

As for the second one, MediatR is an **in-process messaging** package. Meaning that it only works in one process (that is, just one application). RabbitMQ OTOH, supports **inter-process messaging**, so we can use it to send messages between independent processes.

So you can't use MediatR as a replacement for RabbitMQ for messaging between microservices.

You could use RabbitMQ instead of MediatR, for in-process messaging, but it adds complexity that's not needed for this eShopOnContainers, although there could be specific situation where it'd make sense.

Hope this helps.

**Comment by mohammed-fuad** [comment]
> Hi @mohammed-fuad, those are good questions! 👍
> 
> For the first one, it's just a matter of adapting to RabbitMQ, because its .NET client doesn't support async publishing.
> 
> As for the second one, MediatR is an **in-process messaging** package. Meaning that it only works in one process (that is, just one application). RabbitMQ OTOH, supports **inter-process messaging**, so we can use it to send messages between independent processes.
> 
> So you can't use MediatR as a replacement for RabbitMQ for messaging between microservices.
> 
> You could use RabbitMQ instead of MediatR, for in-process messaging, but it adds complexity that's not needed for this eShopOnContainers, although there could be specific situation where it'd make sense.
> 
> Hope this helps.

**Comment by mohammed-fuad** [comment]
Thanks @mvelosop for your reply. It's valuable and clear 👍
