### ISSUE TITLE
[BUG?] Do  domain event handlers have to explicitly call SaveEntitiesAsync?

### ISSUE THREAD

**Issue by alecola** [dotnet-architecture/eShopOnContainers#1054]
Hello,
first of all thanks again for this great reference project. I'm focusing on the Ordering bounded context, Im' wondering if domain event handlers have to explicitly call UnitOfWork.SaveEntitiesAsync(). 

I understand that the Command Handler is responsible for persisting changes on one aggregate, and side effects on another aggregate have to be managed by a domain event triggering a domain event handler. The question is: does the domain event handler have to call SaveEntitiesAsync, when it is already called by the command handler?

For example, ValidateOrAddBuyerAggregateWhenOrderStartedDomainEventHandler explicitly calls 
`_buyerRepository.UnitOfWork.SaveEntitiesAsync()`, while UpdateOrderWhenBuyerAndPaymentMethodVerifiedDomainEventHandler does not call `_orderRepository.UnitOfWork.SaveEntitiesAsync()`.
Thanks for your time.

**Comment by victormp1988** [comment]
Basically, you are updating the buyer aggregate in that domain event handler. Due to that, a new domain event needs to be informed. The infrastructure layer defers that responsability on the SaveEntitiesAsync (which internally use Meditr for the dispatching) method. At the end, there could be N side effects after a buyer is added or updated.

**Comment by mvelosop** [comment]
Hi @alecola, @victormp1988 is right (thx 😊)

In other words, in eShop, you use SaveEntitiesAsync when you have to dispatch other domain events, and SaveChangesAsync when you don't.

As for the specific question, yes every command/event handler has to SaveChangesAsync (directly or through SaveEntitiesAsync) to send the changes tracked by the DbContext to the database.

It's also important to highlight that all those changes saved from DbContext to the database are kept in a single database transaction, that's committed when the first command/event handler finishes. That happens here:

https://github.com/dotnet-architecture/eShopOnContainers/blob/ad7d33968f102ffcb06e528b6a64002890947cea/src/Services/Ordering/Ordering.API/Application/Behaviors/TransactionBehaviour.cs#L56

Hope this helps.

**Comment by alecola** [comment]
Hello,
thanks for both answers. @mvelosop So, why UpdateOrderWhenBuyerAndPaymentMethodVerifiedDomainEventHandler  does not call _orderRepository.UnitOfWork.SaveEntitiesAsync()?

**Comment by alecola** [comment]
...or, better: why ValidateOrAddBuyerAggregateWhenOrderStartedDomainEventHandler explicitly calls
_buyerRepository.UnitOfWork.SaveEntitiesAsync(), while UpdateOrderWhenBuyerAndPaymentMethodVerifiedDomainEventHandler does not call _orderRepository.UnitOfWork.SaveEntitiesAsync()?

**Comment by mvelosop** [comment]
OOOK, @alecola, I think you've made a point here 😉 but there's something I have to delve into, because I'm not completely sure, for there seem to be some conflicting approaches.

I'll try to explain what I see.

Since we're using two DbContexts (OderingContext and IntegrationEventLogContext) in a transaction with the same Database, we should use a custom retry strategy and SaveChanges only within the scope of the `TransactionBehavior` (contrary to what I said before).

So the handlers that call SaveEntitiesAsync, should really just be publishing the "chained" domain events through mediator, without executing SaveChangesAsync.

However, as I said, I'm not completely sure so I'll try to make a small proof of concept program to check this. But it'll take some time though 🙁

**Comment by alecola** [comment]
Thanks for your help @mvelosop !

**Comment by erikpique** [comment]
Hi @alecola

I would say UpdateOrderWhenBuyerAndPaymentMethodVerifiedDomainEventHandler does not need to call SaveEntitiesAsync since it does not have to execute any domain events. Within the handler you only get some entities that are modified and tracked by the entity framework, that way when the bbdd transaction is done it is saved with everything else.
Maybe for a future improvement it would be necessary to simplify and have only one method and that internally manages the domain events if necessary in a transparent way for the programmer.

Greetings

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.

**Comment by luisguerrerolab** [comment]
I have the same doubt as @alecola, but I'll put it in different words:

I understand that command/event handlers can make the call to  `SaveEntitiesAsync` or `SaveChangesAsync`, depending on whether they want to dispatch domain events or not.

In the specific scenario that `UpdateOrderWhenBuyerAndPaymentMethodVerifiedDomainEventHandler` takes care of and as the name implies,  it seems to me that the `Handle` method should call to `await _orderRepository.UnitOfWork.SaveChangesAsync()` (no events to dispatch) because it's necessary to persist in the database the relationship created in memory when calling to `orderToUpdate.SetBuyerId(buyerPaymentMethodVerifiedEvent.Buyer.Id);`.

As @mvelosop mentioned, the complete collection of database operations that were registered during the process of creating an order will be finally persisted in database when `TransactionBehaviour` calls `await _dbContext.CommitTransactionAsync(transaction);`.

The initial question remains though.

**Comment by mvelosop** [comment]
Well, after a couple of years, I'd now say that the developer shouldn't have to worry about this, because it's a leaking detail. 😉

**Comment by luisguerrerolab** [comment]
Ah! My immense inexperience in real-world projects implementing Event-Driven communication makes me believe at first that everything I see, it's magic! That's why I wanted to re-ask this question—to make sure that it's actually not magic and discard the probability that some middleware is doing the trick.
