### ISSUE TITLE
Unable to create an object of type 'ApplicationDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

### ISSUE THREAD

**Issue by dupeng0224** [dotnet-architecture/eShopOnContainers#1080]
In Identity.API, I deleted the migrations folder and then use "Add-Migration Initial" command want to generate migrations ,an error ocurred, 
the error is "unable to create an object of type 'ApplicationDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728"

i want to known how to generate this migrations files.

**Comment by mvelosop** [comment]
Hi @dupeng0224, Why did you do that? 😳

That's definitely not an app issue which is this scope of the issues in this repo, but I'll try to give you some guidance anyway.

You get that error because to generate migrations you need either:

1. A DbContext with a default constructor (that is, a parameterless constructor)
2. Being able to get the DbContext from ApplicationServices (that is, Dependency Injection)
3. A design time factory that returns a properly configured DbContext.

Since ApplicationDbContext constructor has a parameter, you have to use options 2 or 3. See the details in the article: https://docs.microsoft.com/ef/core/miscellaneous/cli/dbcontext-creation

But option 2 (the one originally used) doesn't work any more, because the program startup was changed to improve logging. 

And, since there's no DesignTimeFactory for ApplicationDbContext you just won't be able to create migrations at this time.

If you want to learn about this way for creating migrations you can:

1. Create an ApplicationDbContextDesignTimeFactory, similar to CatalogContextDesignFactory or IntegrationEventLogContextDesignTimeFactory, or
2. Try with other microservice like Catalog.API, that already has its DesignTimeFactory.

Hope this helps.

**Comment by dupeng0224** [comment]
Hi @mvelosop thanks for you response.
I just want to learn how to generate these migrations.
 follow your instruction, i successed created ApplicationDBContext migration.
but there is another two problems,
`public class PersistedGrantDbContextFactory : IDesignTimeDbContextFactory<PersistedGrantDbContext>
    {
        public PersistedGrantDbContext CreateDbContext(string[] args)
        {
            var optionsBuilder = new DbContextOptionsBuilder<PersistedGrantDbContext>();
            optionsBuilder.UseSqlServer("Server=192.168.31.39;Database=Microsoft.eShopOnContainers.Services.IdentityDb;User Id=sa;Password=123456q!;");
            return new PersistedGrantDbContext(optionsBuilder.Options, null);
        }
    }`
in this factory , PersistedGrantDbContext has two params, how to define or pick the second param.
and same to PersistedGrantDbContext, the ConfigurationDbContext has the same question.

**Comment by mvelosop** [comment]
That's something internal to IdentityServer that I haven't explored!

Anyway, you should find it easily exploring by yourself the IdentityServer repos: https://github.com/IdentityServer

Hope this helps!

**Comment by arabsorkhi** [comment]
hello 
I had same Problem
You must insert the below code in ConfigureServices Method in Startup class :
```
services.AddDbContext<DataContext.WebAppContext>
                (options=> options.UseSqlServer(Configuration.GetConnectionString("WebAppContext")));
  
```
So You  have this:
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();
            services.AddDbContext<DataContext.WebAppContext>
                (options=> options.UseSqlServer(Configuration.GetConnectionString("WebAppContext")));
        }
```

**Comment by nblx2k4** [comment]
Solution for someone who have multiple projects:

I had the same issue and solved it by selecting one project as startup project instead of multiple projects.

**Comment by oordeelsdag** [comment]
When you move your DbContext to another project you should do this:

if you use visual studio:
right click on your main project and choose "Set as startup project"
then run tools>nuget package manager>package manager console
make sure you have chosen the project which contains your DbContext (from drop-down list)
and run: Add-Migration .....

if you use dotnet-cli just type this in terminal:
dotnet ef migrations add  MigrationName -s mainProject -p DbContextProject

make sure in termial you are in the directory which contains both main and DbContext project

**Comment by Marcel-B** [comment]
That doesn't work, the same issue occures.

![image](https://user-images.githubusercontent.com/9868657/79435250-b3387180-7fcf-11ea-91e6-bdf9399b977c.png)

**Comment by oordeelsdag** [comment]
> That doesn't work, the same issue occures.
> 
> ![image](https://user-images.githubusercontent.com/9868657/79435250-b3387180-7fcf-11ea-91e6-bdf9399b977c.png)

On this image we can see that your DbContext name is WebContext and CLI was able to find it, which is good. and I'm sure the problem is what I said earlier,and it seems you just didn't do it correctly.

Let me explain with more details:
imagine you have a directory named "Container"
inside it you have 2 projects:  
"Main" project which must be your startup project and contains startup.cs and etc
"DataAccess" project which contains your dbContext( in your case WebContext)

you should be on Container directory in Terminal
then type this:
C:\Container> dotnet ef migrations add MyMigration -s Main -p DataAccess

just be sure you have created your DbContext in standard way. something like this:

using Microsoft.EntityFrameworkCore;

namespace Container.DataAccess.Data
{
    public class WebContext : DbContext
    {
        public WebContext(DbContextOptions<WebContext> options)
            : base(options)
        {
        }

    }
}

**Comment by leoskey** [comment]
Same Problem：
```cssharp
public void ConfigureServices(IServiceCollection services)
{
            var databaseConnectionString = Configuration.GetConnectionString("AppDatabase");
            services.AddDbContext<ApplicationDbContext>(options => 
                options.UseMySql(databaseConnectionString));

            services.AddIdentity<IdentityUser, IdentityRole>()
                .AddEntityFrameworkStores<IdentityDbContext>();
}
```
Resolve：
` .AddEntityFrameworkStores<IdentityDbContext>(); `
change to
` .AddEntityFrameworkStores<ApplicationDbContext>();`

**Comment by dupeng0224** [comment]
thanks for all warm-hearted friends, and this is an old problem in 2.2. i have not try it in 3.1.

**Comment by Genato** [comment]
> You get that error because to generate migrations you need either:
> 
> 1. A DbContext with a default constructor (that is, a parameterless constructor)

I busted my head with million different solution, but this one worked like knife through butter.

I'am using WinForms with PostgreSQL NpqSQL provider for EF, and i thought that problem is with that specific setup.

THANK YOU!!!

**Comment by stellaoliveirabertt** [comment]
Well guys, in my case I was doing dependency injection before executing the new Migration, then I commented on the startup the new injection, ran the migration and then I enabled the dependency injection.

**Comment by felipementel** [comment]
This happened to me, but I will explain what happened.
I have a solution with several projects, one of which is webAPI and the entire ddd stack under it (application, domain, crosscutting and data)

I added the same solution to a razor page project ... and put the solution to start the 2 projects, because I wanted to see the site calling the webAPI ...
then I tried to run the migration and this problem occurred.

I had to put WebAPI, which has the project that accesses the database to be the startup and when I ran the migration it worked.

**Comment by mchomem** [comment]
> Solution for someone who have multiple projects:
> 
> I had the same issue and solved it by selecting one project as startup project instead of multiple projects.

Context: your solution is separated by projects, where the entity / database model is in theirs.

If for some reason you needed to delete the Migration folder, and when trying to generate the model again, you got this error because you excluded the Migrations folder after adding more projects that need to be started (usually along with the web api, as another site, angular, mvc, etc.).

If this is your context, a possible solution is this:

1) Indicate the web api project as the initialization;
2) In the model project, apply the add-migration commands "DesignatedName" and then the update-database command;

Searching the Web, I found this post because I had the same problem, but then I realized that I had excluded the Migrations folder after including other projects.
I followed the steps above and it worked for me.

**Comment by Risath** [comment]
I faced similar problem with my project. I had to do the following steps to get `Add-Migration` command working with EntityFrameworkCore 3.1.7  
  
1. Added default constructor to the DbContext class.
2. Set WebApi as startup project
3. Added `Microsoft.EntityFrameworkCore.Design` package to the WebApi project     

Not sure why the 3rd step is required?

**Comment by freshekt** [comment]
When i tried create first migration i have the same issue.  In my case I solved it  just add  empty constructor  to  ApplicationDbContext.

`public class ApplicationDbContext : IdentityDbContext<ApplicationUser, ApplicationRole, string>
    {
        public ApplicationDbContext() { }
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }
...
}`

**Comment by LazZiya** [comment]
In my case I had multiple json files configured in `Program.cs` as below, and I was not able to run migration commands:
````cs
public static void Main(string[] args)
{
    var configuration = new ConfigurationBuilder()
        .SetBasePath(AppContext.BaseDirectory)
        .AddJsonFile("file1.json", optional: true, reloadOnChange: true)
        .AddJsonFile("file2.json", optional: true, reloadOnChange: true)
        .AddJsonFile("file3.json", optional: true, reloadOnChange: true)
        .Build();

    CreateHostBuilder(args, configuration).Build().Run();
}

public static IHostBuilder CreateHostBuilder(string[] args, IConfiguration configuration) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseConfiguration(configuration);
            webBuilder.UseStartup<Startup>();
        });
````

Then, with reference to [this reply](https://stackoverflow.com/a/54786157/5519026), I changed the implementation as below and all migration commands worked as expected:
````cs
public static void Main(string[] args) =>
    CreateHostBuilder(args).Build().Run();

public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureAppConfiguration((hostContext, config) =>
        {
            config.SetBasePath(AppContext.BaseDirectory);
            config.AddJsonFile("file1.json", optional: true, reloadOnChange: true);
            config.AddJsonFile("file2.json", optional: true, reloadOnChange: true);
            config.AddJsonFile("file3.json", optional: true, reloadOnChange: true);
        })
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        });
}
````

> I'm using .net 5.0

**Comment by dusbn** [comment]
I had this issue when renaming/removing the default CreateHostBuilder function in Program.cs.

**Comment by ImranKhan00** [comment]
I faced the same problem, resolved,
`    public class SoftoChatDataContext:DbContext
    {
        public SoftoChatDataContext(DbContextOptions<SoftoChatDataContext> options):base(options)
        {
        }
        public DbSet<User> Users { get; set; }
    }`
    
when i resolved
`{
    public class SoftoChatDataContext:DbContext
    {
        public SoftoChatDataContext(DbContextOptions options):base(options)
        {
        }
        public DbSet<User> Users { get; set; }
    }`

mentioning type for `DbContextOptions` caused the problem for me. may this help someone too

**Comment by bakhraktar** [comment]
1. You must have Default Project in package manager console - Data Library(Where you have entities)
2. You must have Startup Project - API project
I had the same Error and I fix it with these tips

**Comment by bunda3d** [comment]
> If this is your context, a possible solution is this:
> 
> 1. Indicate the web api project as the initialization;
> 2. In the model project, apply the add-migration commands "DesignatedName" and then the update-database command;

can you clarify these steps? I don't understand what you're saying.

**Comment by bunda3d** [comment]
> 1. You must have Default Project in package manager console - Data Library(Where you have entities)
> 2. You must have Startup Project - API project
>    I had the same Error and I fix it with these tips

This worked for me also--But I thought I already had the API project selected as a Startup project, and was selecting the project where I wanted my migrations folder in the Package Manager Console, yet I was getting errors with command "add-migration Initial". 

Turned out: I had selected the API project in that folder as a startup project under the overall Solution properties, as one of multiple startup projects. That's not good enough for getting this migrations folder to generate. So I right-clicked on the API project in this folder and chose "set as Startup Project". This is the option that actually turns the project's file name bold. After this, the "add-migration Initial" command worked and generated a migrations folder.

**Comment by ghost** [comment]
Make sure that the DbContext class constructor looks like this 
public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

**Comment by Memmed22** [comment]
I had same issue on VS Code .net Project. I assumed problem was start up project in VS Code. So in terminal (Git Bash)

$ dotnet ef --startup-project ../MyWebApp.Web/ migrations add Initial 

$ dotnet ef --startup-project ../MyWebApp.Web/ database update

It works clearly now :)
(MyWebAppDbContext conatins in .Web lib)

**Comment by ekomut** [comment]
I set my webproject to startup project and that solved the issue for me.

**Comment by awalkhade** [comment]
> When you move your DbContext to another project you should do this:
> 
> if you use visual studio:
> right click on your main project and choose "Set as startup project"
> then run tools>nuget package manager>package manager console
> make sure you have chosen the project which contains your DbContext (from drop-down list)
> and run: Add-Migration .....
> 
> if you use dotnet-cli just type this in terminal:
> dotnet ef migrations add MigrationName -s mainProject -p DbContextProject
> 
> make sure in termial you are in the directory which contains both main and DbContext project

Perfect. It solved my problem. Thank you.
If your application/solution have multiple projects in it where Data Layer and Main project is different. We do DB connection configuration in Main project's startup file. but, while doing migrations, we don't get DB connection string in Data Layer Project. Using `**dotnet ef migrations add MigrationName -s mainProject -p DbContextProject**` this command fixed that issue. Thanks.

**Comment by ElvisGC** [comment]
ayuda no me quiere migrar

![ayuda](https://user-images.githubusercontent.com/81270532/120612843-39558880-c41b-11eb-971c-3f475aa495b9.png)

**Comment by stellaoliveirabertt** [comment]
> ayuda no me quiere migrar
> 
> ![ayuda](https://user-images.githubusercontent.com/81270532/120612843-39558880-c41b-11eb-971c-3f475aa495b9.png)

In my case I was doing dependency injection before executing the new Migration, then I commented on the startup the new injection, ran the migration and then I enabled the dependency injection.

**Comment by vatansoni89** [comment]
I am still getting this issue with .netcore 3.1 and ef core 5.

Here is my git repo:
https://github.com/vatansoni89/RabbitMQ/tree/24aef48811a08d896579a2fc28cbe7e5b870c324

![Capture](https://user-images.githubusercontent.com/29680895/122583789-3f807180-d077-11eb-84d4-0b68b3546699.JPG)

**Comment by songulija** [comment]
You can look at documentation. https://docs.microsoft.com/lt-lt/ef/core/dbcontext-configuration/#constructor-argument

Create your DbContext in standard way

![image](https://user-images.githubusercontent.com/65647664/125456563-7a3e7e76-4254-4dd6-8e26-1b477dfd20da.png)

Then add this to ConfigureServices in Startup.cs file. Of course change Connection String to yours for example: "Data Source=DESKTOP-9AB2C7F;Initial Catalog=TestDB;Integrated Security=True".


services.AddDbContext<ApplicationDbContext>(options => options.UseSqlServer("name=YOURCONNECTIONSTRING:DefaultConnection"));


For me it worked. 
![image](https://user-images.githubusercontent.com/65647664/125455742-5f116887-9d0c-4437-8fc2-394cd53e3671.png)

**Comment by avinashdubey0422** [comment]
Remove this:
public ApplicationDbContextBase(DbContextOptions contextOptions)
        : base(contextOptions)
    {
    }
-------------------------------
Add This:    
    public ApplicationDbContextBase()
    {
    }

**Comment by mbagozpel** [comment]
> > That doesn't work, the same issue occures.
> > ![image](https://user-images.githubusercontent.com/9868657/79435250-b3387180-7fcf-11ea-91e6-bdf9399b977c.png)
> 
> On this image we can see that your DbContext name is WebContext and CLI was able to find it, which is good. and I'm sure the problem is what I said earlier,and it seems you just didn't do it correctly.
> 
> Let me explain with more details: imagine you have a directory named "Container" inside it you have 2 projects: "Main" project which must be your startup project and contains startup.cs and etc "DataAccess" project which contains your dbContext( in your case WebContext)
> 
> you should be on Container directory in Terminal then type this: C:\Container> dotnet ef migrations add MyMigration -s Main -p DataAccess
> 
> just be sure you have created your DbContext in standard way. something like this:
> 
> `using Microsoft.EntityFrameworkCore;` `namespace Container.DataAccess.Data` ` {` ` public class WebContext : DbContext` ` {` ` public WebContext(DbContextOptions<WebContext> options) : base(options)` ` {` ` }` ` }` ` }`

This worked for me

**Comment by erivics** [comment]
All these being said but I am using .Net6 but I have tried most recommendation here but to no avail

![dbb](https://user-images.githubusercontent.com/75021908/164072867-0edc22fc-a4c5-49f0-b7ea-10228bb8908c.JPG)
![db](https://user-images.githubusercontent.com/75021908/164072874-502021c0-c32f-4d63-a4d8-a5f28b80df06.JPG)

**Comment by Leni52** [comment]
I had the same issue. The solution was to restart Visual Studio, then select the project containing the DbContext as Startup Project in the Package Manager Console and re-run the command.

**Comment by tsotneabsandze** [comment]
@erivics let us know if you have found any solutions yet

**Comment by GKepuska1** [comment]
Hi there,
I found the solution from my side, so hopefully this will help any of you!

When you use a command like add migration it's important to understand what is actually happening. Your project will be built and it will try to use your project as a class library. It will try to instantiate a DbContext. The error means it was unable to create the object, so something is wrong with your code which is preventing that.

First make sure your project builds without errors. This includes any code not part of the DbContext. It has to be able to build and run.

On my project it was the wrong typed connection string, in which case it didn't connect to db, so I ran the project and found the issue of the connection string. After fixing that I ran again the add-migration and whola it worked!

**Comment by alemaoast** [comment]
I had the same issue. My solution was to comment Private Assets from the infrastructure project.
This will provide access to the Microsoft.EntityFrameworkCore.Design.

![image](https://user-images.githubusercontent.com/65097349/176328487-3d9d41a8-6f0b-499c-8991-f2d3741c4eea.png)

![image](https://user-images.githubusercontent.com/65097349/176328673-06d2c9b9-31b7-4b23-9812-afea13980fe3.png)

**Comment by erivics** [comment]
Yes I have

**Comment by Abdelaziz98Shaban** [comment]
I had same problem , you have to make your web as startup project in my case was the Admin project , and select data access project (the one that has the migrations files and dbcontext) from drop down list in package manger console.

**Comment by cmkaya** [comment]
It can be caused from different problems.

In my case, the reason was because of having different projects. If `DbContext` implementation exists in a different project than the startup project, and you execute migration commands, you will likely encounter the error.

You should execute the .NET CLI command as follows:

```bash
dotnet ef migrations add MyMigration -p ../MyDbContextProject -s ../MyWebAppProject
```

- `-p`: Specifies the relative path to the project containing your `DbContext` (`MyDbContext.cs` in this case).
- `-s`: Specifies the relative path to the startup project (typically your web application project containing Startup.cs), which is required when you have multiple projects in your solution.

Make sure to replace `../MyDbContextProject` and `../MyWebAppProject` with the actual relative paths from your `MyMigrationsProject` to the `MyDbContextProject` and `MyWebAppProject` respectively.

**Comment by maxflorex** [comment]
> When you move your DbContext to another project you should do this:
> 
> if you use visual studio: right click on your main project and choose "Set as startup project" then run tools>nuget package manager>package manager console make sure you have chosen the project which contains your DbContext (from drop-down list) and run: Add-Migration .....
> 
> if you use dotnet-cli just type this in terminal: dotnet ef migrations add MigrationName -s mainProject -p DbContextProject
> 
> make sure in termial you are in the directory which contains both main and DbContext project

This worked for me! Thank you 😀 🙏🏻
