### ISSUE TITLE
Context file use in controller

### ISSUE THREAD

**Issue by mayankgaur** [dotnet-architecture/eShopOnContainers#1081]
If we use context file in controller, with ref to CatalogController makes code non reusable for further use. like if I want to use new type of db like Mongo then again I have to change in code

**Comment by mvelosop** [comment]
Hi @mayankgaur,

You're right, it's just that the goal with the Catalog.API microservice was to get the simplest CRUD implementation.

You can see a completely different pattern in the Ordering microservice for example.

However, as mentioned in the [Use NoSQL databases as a persistence infrastructure section](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/nosql-database-persistence-infrastructure) from the Microservices Architecture Guide, in most, but the simplest cases, there are constraints and trade-offs that make it difficult to create a truly database agnostic domain model, to the level that you can switch transparently between SQL and Document, so that should not be a primary goal.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now, but feel free to comment, will reopen if needed.
