### ISSUE TITLE
Containerized Microservices vs serverless Microservices

### ISSUE THREAD

**Issue by PingPongSet** [dotnet-architecture/eShopOnContainers#1086]
I am reading the wonderful book half way.

I have questions:

1 What are the pros and cons of Containerized Microservices and serverless Microservices?

2 It seems to me that serverless Microservices using Azure Function App, or Azure App Services are much simpler. 

3 Can Azure Service Fabric be used for serverless Microservices too?

4 For what scenarios are Containerized Microservices the best fit?

Great stuff here again.

**Comment by mvelosop** [comment]
Hi @PingPongSet, that's a good question!

I wouldn't say containerized microservices are comparable to serverless, because they're pretty different tools.

Serverless are usually single functions that you might call perhaps "nano" or "pico" services, someone might even argue that even service is too much of a name.

Azure functions are pretty simple and fast to build and I would use them whenever they can run independently, that is, without needing any orchestration.

Building a microservice out of functions could get you a set of too many separate moving parts, that could be a nightmare to manage, test and deploy.

So IMHO, from a high level point of view, it's a matter of complexity, for simple, very specific, and independent "nano services", use Azure Functions, when there's complex logic, more dependencies, handle "business-type" of concerns, use containerized microservices.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
