### ISSUE TITLE
Full Event Sourcing in preventing loss of domain event published to event bus subscribed by other microservicess

### ISSUE THREAD

**Issue by PingPongSet** [dotnet-architecture/eShopOnContainers#1111]
I across the article below, and want to find out exactly how full event sourcing pattern can prevent the issue of losing event when publishing domain event to event bus.

> For this scenario, using the full Event Sourcing (ES) pattern is one
> of the best approaches, if not the best.

https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/subscribe-events

Specifically, the scenario is that Catalog microservice updated a product price and published a ProductPRiceChanged event. How can full ES prevent loss of that event.

https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/subscribe-events

**Comment by mvelosop** [comment]
Hi @PingPongSet, 

As fas as I understand, ES, per se, would not prevent losing messages when publishing to the bus (That could happen for a reason outside the control of the ES), but it would make it much easier to recover from a lost message.

Since events **are** the state of the system, it should be easy to find out the ones missing to rebuild the state wherever ti's needed.

However, one approach that comes to my mind right now (but I just have a very basic knowledge of ES) is that since ES is "append only" it should be "easy" (whatever that means) to implement a distributed ES data store, so any service that needs the data would just use its copy of the ES data store.

So the distribution of events would be handled internally by the ES data store and (I would hope) tackle all possible failure modes.

Would be nice to have some input from someone with real world experience in this topic!

Hope this helps somehow.

**Comment by gregoryyoung** [comment]
Using a "catch up subscription" (as named in eventstore) would handle this case and prevent the message loss.

Let me propose that your events are stored in a log (and ordered)...

position location  data
1 1 foo
2 17 bar
3 19 baz 
4 29 wooho

When reading from this I could make a subscription based only on *read*. Basically I read forward and remember the last event I processed (checkpoint) ... if I fail I start with the one after the last I successfully finished. 

read 1
process 1
checkpoint 1
read 2 
process 2
checkpoint 2
read 3
POWER PULL
read checkpoint = 2
start at 3 (or after-2) ...

The obvious problem here is ...
read 3 
process 3
power pull ...
read 3 
process 3 //is this twice?

If things are idempotent this is no issue.

Note that this is atleast-once-messaging! and I may process something twice in a failure thus the handler should be idempotent.


Now as for the bus losing messages ... This is a bit of a different beast as the first trick will be detecting that there is a miss. This depends largely on the data in question. If its an entire stream its trivial. Just use the version (its an incrementing sequence except for some odd outliers you likely dont have) thus you can detect any gaps etc.

Or am I misunderstanding your question?

**Comment by mvelosop** [comment]
Hi @gregoryyoung (hey folks, we have a luxury guest here 😊)

Thanks for your input here!

I think the explanation is clear and straight forward.

There's something I'm not clear about. If we were using ES in eShopOnContainers, what should we do to get notified of product price changes? 

1. Subscribe each interested microservice to the event stream with a [Catch-up subscription](https://eventstore.org/docs/getting-started/reading-subscribing-events/index.html?tabs=tabid-6%2Ctabid-dotnet-client%2Ctabid-8%2Ctabid-dotnet-read-event%2Ctabid-create-sub-http#catch-up-subscriptions), separate from the configured event distribution bus (RabbitMQ or Service Bus)  or

2. Publish the events through the configured event bus.

Thanks!

**Comment by mvelosop** [comment]
Well, I'm guessing that if an ES store has the capability to handle a Catch-up subscription it would make sense to use it, much more than anything additional handled by a third-party queue.

Closing this issue now, but feel free to comment, will reopen if needed.
