### ISSUE TITLE
Testing CommandHandler

### ISSUE THREAD

**Issue by HardRock4Life** [dotnet-architecture/eShopOnContainers#1118]
Is it possible to test out every single CommandHandler? Anyone tried?

**Comment by mvelosop** [comment]
Hi @HardRock4Life,

I guess you mean "unit test" every command handler, right?

It should be possible, as they all use constructor injected interfaces... but, IMHO, it's not worth the effort to unit test them all.

I actually prefer to use more integration testing than unit testing, because that way you are testing not just the handlers, but the whole thing. The "whole thing" in DDD can get really tricky when you consider chained domain events, transactions and publishing integration events, so the value of unit testing in this scenario, again IMHO, is quite limited.

I would, perhaps, unit test a couple of command handlers that have a bit more involved logic, but that would be it.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue but feel free to comment, will reopen if needed.
