### ISSUE TITLE
Concurrency Issue?

### ISSUE THREAD

**Issue by oleg-savoskin** [dotnet-architecture/eShopOnContainers#1121]
Hi guys!

I’m using the [eShopOnContainers ](https://github.com/dotnet-architecture/eShopOnContainers)project to get better understanding of how reliable distributed systems are built. You have done a great job, I really appreciate this!

Would you please be so kind to help me understand one moment? - As we can see, [OrderingContext is registered as a scoped service](https://github.com/dotnet-architecture/eShopOnContainers/blob/3bdf3eb8736dd4c9b8e34ab78b5ca4450e025560/src/Services/Ordering/Ordering.API/Startup.cs#L230) with DI. That means that a single instance of it will be used all the way through a request. So the request comes, the context gets created and used to get an aggregate from a database, update it and push changes back to the database. Just before calling to orderingContext.SaveChangesAsync() domain events are published and handled. And this is a tricky part. A domain [event handler may use the ordering context to make some changes](https://github.com/dotnet-architecture/eShopOnContainers/blob/3bdf3eb8736dd4c9b8e34ab78b5ca4450e025560/src/Services/Ordering/Ordering.API/Application/DomainEventHandlers/OrderStartedEvent/ValidateOrAddBuyerAggregateWhenOrderStartedDomainEventHandler.cs#L58) to the database. Since domain event [handlers are executed in parallel](https://github.com/dotnet-architecture/eShopOnContainers/blob/3bdf3eb8736dd4c9b8e34ab78b5ca4450e025560/src/Services/Ordering/Ordering.Infrastructure/MediatorExtension.cs#L29) (and request is not finished yet, so the same instance of ordering context is used) the question arises – why is it ok to access the context from multiple threads? Should not we access it in a synchronous way? And how to achieve that? By using a lock on the instance?

Also, doesn’t such approach violate one of the rules of thumb mentioned by E. Evans & V. Vernon namely that we should always update a single aggregate per transaction/request? I can think of quite a large project where a single aggregate can possibly produce a hundred domain events which consecutively change/update hundreds of aggregates which again generate hundreds of domain events. And so on… Isn’t this a problem? 

Looking forward to your response.
Thank you in advance!

Oleh

**Comment by mvelosop** [comment]
Hi @oleg-savoskin, that's a nice and acute observation 👍

There are several important questions in your issue, so I'll try to answer them separately as much as I can. One important point to keep in mind is that this is my personal (and humble) opinion, from maintaining the repo for some time now, but @CESARDELATORRE and/or @nishanil could surely add some important (and official) insights.

> why is it ok to access the context from multiple threads?

I'd say it's mainly because the underlying model is quite simple, with a simple event model that usually handles a single command "chain" (not really parallel or at least parallel not conflicting). and it just hasn't caused any issue. 

Well, actually users have reported quite some interesting issues, and most of them have been solved, just no one had commented on this before.

> Should not we access it in a synchronous way? And how to achieve that? By using a lock on the instance?

I haven't really think about this before, but the first that comes to my mind is handling a DbContext per aggregate, it looks simpler and might be enough, at least up to some complexity level.

> Also, doesn’t such approach violate one of the rules of thumb mentioned by E. Evans & V. Vernon namely that we should always update a single aggregate per transaction/request?

I think we could agree that there's not a one-size-fits-all solution, it just depends on how complex your domain/application is. The key is choosing the simplest solution for the problem at hand. 

So the solution in eShop would certainly not be suitable for a domain that handles hundreds of events per operation. But just as well, the solution for such a large problem would be very difficult to comprehend for any one (or the vast majority) outside that domain.

I think it's important to keep the context in mind here.

The purpose of eShopOnContainers is to get people started in a microservices architecture and related approaches/patterns/technologies.

So one of the main concerns has been to keep complexity as low as possible, to make it easier to grasp the key concepts and get started.

Even so, there's been feedback about eShop being too complex on one side and not real-world on the other.

Well.. it's a thin a difficult line to walk, but this is a great learning resource anyway 😊

Just my two cents.

Hope this helps!

**Comment by oleg-savoskin** [comment]
Thank you, Miguel!

So, the issue does exist and theoretically there are might be conflicts while updating the database. We don't see them as there are few events and those which being raised don't lead to a conflict.

Also, what if any of domain event handlers will take longer to complete its work than the request to reach timeout? Apparently, if we want to have a background worker we cannot use a scoped context. But, if it was transient it would be much harder to maintain consistency. Should we use something like local sagas and make call to `mediator.DispatchDomainEventsAsync()` after `context.SaveChangesAsync()`?

As I can see it's quite hard to make this approach flawless. I mean the project structure itself. For instance, there is nothing to prevent another member of a team from using the ordering context directly, as it is public and API has a reference to the infrastructure project (I have seen many great projects went down the drain just because of lazy devs who didn't want to use abstractions and the project structure allowed not to). However If we made the ordering and eventLog contexts internal it would be hard to write clean code to make them use a single connection and the same transaction.

Btw, if so, wouldn't it be easy to achieve atomicity in persisting integration events by doing something like this:


```
/* Registration
---------------------------------------------------- */

services.AddScoped<DbConnection>(provider =>
{
	return new SqlConnection(connectionString);
});

services.AddScoped<DbTransaction>(provider =>
{
	return provider.GetService<DbConnection>().BeginTransaction();
});

services.AddDbContext<OrderingContext>((provider, o) =>
{
	o.UseSqlServer(provider.GetService<DbConnection>());
});

services.AddDbContext<EventLogContext>((provider, o) =>
{
	o.UseSqlServer(provider.GetService<DbConnection>());
});

/* Usage
---------------------------------------------------- */

class OrderingContext : DbContext
{
	public OrderingContext(DbContextOptions options, DbTransaction transaction) : base(options)
	{
		Database.UseTransaction(transaction);
	}
}

class EventLogContext : DbContext
{
	public EventLogContext(DbContextOptions options, DbTransaction transaction) : base(options)
	{
		Database.UseTransaction(transaction);
	}
}

class TransactionalMiddleware
{
	private readonly RequestDelegate next;

	public TransactionalMiddleware(RequestDelegate next) => this.next = next;

	public async Task InvokeAsync(HttpContext context, DbTransaction transaction)
	{
		try
		{
			await next(context);
			transaction.Commit();
		}
		catch
		{
			transaction.Rollback();
			throw;
		}
	}
}
```

In any case, could you please share your experience when such approach/architecture justifies itself? Wouldn't it be better to use classical multi-tier architecture or even a simple one-tier app while creating a micro service?

Thank you very much for your help and such a great example! I've learnt a lot.

**Comment by mvelosop** [comment]
Hi @oleg-savoskin,

This approach is certainly not flawless, and that was not the intention either, it's just good enough for this context.

I think it might even work for a bit more complex applications by creating a DbContext per aggregate and inserting records directly into the integration events outbox table (without a DbContext). However, I haven't tried this.

At some point we discussed about handling the operations (in Ordering.Api) in a single transaction, and decided it was a good solution, given the simplicity of this model.

For more complex scenarios it would probably be better to handle the domain events through an asynchronous queue, like RabbitMQ, but as usual, that would also bring in its own problems, like the need for compensating actions in case of failures, which are just not needed in our case.

So, as usual, you have to consider the trade offs to choose the "best" solution for your context.

About the atomicity issue, we started with something similar to what you propose, but it ended being a [bit more complex](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.API/Application/Behaviors/TransactionBehaviour.cs#L29), to correctly handle atomicity for operations with chained events (the ones that raise another integration events). [You might get some nice insights from the logs](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Serilog-and-Seq#Integration-event-handling).

As for the "better" solution, as I've mentioned, it's always context dependent.

A classical multi-tier app just would'n have done for eShopOnContainers, just because this is a showcase for a microservices architecture app.

What's the appropriate context for a microservices app? Well, the definitive answer is, of course, it depends.

I'd say, most of the time, the general answer is: try to avoid a microservices architecture as much as possible, because it adds **A LOT** of complexity, more specifically IMHO:

- Don't use microservices for an MVP or POC project.
- Don't use microservices if you have a small development/support team (I'm in a large microservices project right now, with 12 teams of about six people each)
- A microservices app is probably not needed if it's handling a single organization in a single country (I've had ~2.000 users (with 10x peaks) with a traditional app, with load-balanced app servers and a single clustered database)
- A microservices app is most probably needed if it has to handle millions of users across several countries.

Hope this helps.

**Comment by oleg-savoskin** [comment]
Have to admit, I have been looking for a silver bullet 😄 

I'm working on a similar project at the moment, but in our case we are using Service Fabric + Azure DTF. Basic concepts and issues are the same, so it looks like there is no magic solution to them and we still have to handle them ourselves. Though it seems to be a bit easier with DTF.

Thank you!

**Comment by mvelosop** [comment]
SF + Durable Tasks 😳😲😨

I haven't worked much with serverless, but I find it kind of scary for microservices but, as usual, it depends on the context.

Anyway that might be something "nice" to explore with eShopOnContainers (cc/@nishanil?) 😁

Cheers.

**Comment by mvelosop** [comment]
This was an interesting and nice interaction 😊, but I think we're done for the time being, so I'm closing it, but feel free to comment, will reopen if needed.

**Comment by oleg-savoskin** [comment]
Hi again!

I've been thinking about that concurrency issue while handling domain events. And eventually came to an idea. Maybe it would be ok not to have a global database transaction but rather a logical one. I mean, maybe it would be a good idea to gather all the changes made by a single request into a logical transaction, track those changes while domain events being handled recursively and roll them back in the right order in case of an error. 

Something like this:
```
public abstract class Context : DbContext
{
	...
	public async Task SaveEntitiesAsync(Guid? correlationId, int? iteration, ...)
	{
		var logicalTransactionId = correlationId ?? Guid.NewGuid();
		var currentIteration = (iteration ?? 0) + 1;

		try
		{
			await DispatchDomainEventsAsync(logicalTransactionId, currentIteration);
			await base.SaveChangesAsync(cancellationToken);
		}
		finally
		{
			if (currentIteration == 1)
				await EventualConsistencyService.EnsureLogicalTransactionCompletedAsync(logicalTransactionId);
		}
	}
}

class SomeEventHandler : DomainEventHandler<SomeEvent>
{
        ...
	public async override Task Handle(Guid correlationId, int iteration, ...)
	{
		// do things...
		await context.SaveEntitiesAsync(correlationId, iteration);
	}
}
```

[I've done a simple PoC.](https://github.com/oleg-savoskin/some-really-complex-project) Could you please take a look when you have a spare minute? What do think? Can it be used in a production environment or, maybe, in eShop?

Thank you!

**Comment by mvelosop** [comment]
Hi @osavoskin,

If I got you right, that's like duplicating the transaction handling of a database, isn't it?

If so, I'd rather use it than replace it. 

You'd also have to consider compensating actions, and they can become really complex, so I'd try to avoid that rout.

BTW, at some point you mentioned hundred of "domain events", that might be a indicator for reconsidering the microservices design in the first place.

Hope this helps.

**Comment by osavoskin** [comment]
I guess you are right.

But still don't get it. Sorry. How having a context per aggregate is going
to help to achieve atomicity.

As far as I know, in order to use a transaction instance you should use a
connection it has been created with. At the same time we are not supposed
to use that connection from multiple threads.

So, for instance,  upon handling a change to a single aggregate a domain
event gets published. There are to handlers for that event. As we are going
to make side changes to another two different aggregates they are created
with two different instances of context. If we use a single connection we
can only handle them sequentially to avoid concurrency. Or, we open new
connections for each dbContext. But how do we attach them to the existing
transaction which was created while handling the initial request?

чт, 29 авг. 2019 г., 14:30 Miguel Veloso <notifications@github.com>:

**Comment by mvelosop** [comment]
Hi @osavoskin,

I was thinking that using separate DbContexts could help avoid thread conflicts, but you're right, if it all ends up in the same connection there could also be conflicts if the "chain of events" split at some point and two different threads end up trying to update the DB at the same time.

Perhaps we'd have to use locking on the very same dbConnection to synchronize updates, but I haven't really had that situation, so I'm just guessing.

Rethinking about this, I guess this is what's happening in eShop, since all updates occur sequentially (because it's a simple case) so we don't get into concurrency issues.

The only way, that I know of, to handle a transaction using different connections us by using a `TransactionScope`, but you're not sharing the transaction but handling a distributed transaction, but it could get murkier. It might be easier to try synchronizing on the dbConnection.

But, as I said before, I haven't really had to work out a solution for this kind of problem, so I'm sorry I can't be of much more help here. 😔

Anyway if you find a solution, it'd be great if you could share some guidance.

Thanks 😊

**Comment by osavoskin** [comment]
Hi @mvelosop,

I should have read the docs more thoroughly, this is from the Mediatr docs:

> The default implementation of Publish loops through the notification handlers and awaits each one. This ensures each handler is run after one another.

So, I guess the simplest fix would be to replace [this select](https://github.com/dotnet-architecture/eShopOnContainers/blob/9dae52f80bddce4ead69717c8546c82e1d8eecac/src/Services/Ordering/Ordering.Infrastructure/MediatorExtension.cs#L24) with a foreach, loop over events, publish and await each of them, sequentially. By doing this we will eliminate concurrency altogether from domain event handling and there will be no need to sync on the dbConnection 😊

**Comment by mvelosop** [comment]
Hey @osavoskin!, yep, that's brilliant! 😊 Great finding!

Would you like to submit a PR with the fix?

**Comment by osavoskin** [comment]
It's good for karma, I suppose 😊 , will do!
