### ISSUE TITLE
Dreaded Driver Failed message

### ISSUE THREAD

**Issue by isaac2004** [dotnet-architecture/eShopOnContainers#1131]
When I do a fresh clone and follow the steps for Windows, I get the following when I run `docker-compose up`

> ERROR: for eshoponcontainers_seq_1  Cannot start service seq: driver failed programming external connectivity on endpoint eshoponcontainers_seq_1 (932e647e617a21bff79cdb7d93d0c6599047a468bb42ddad2f80df11f5994596): Error starting userland proxy: listen tcp 0.0.0.0:5340: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

I get this for pretty much all the services. I have Docker Desktop configured for 4GB of RAM and 3 Cores (I have a 16GB Surface Book 2). My firewall is configured right, but I am using a laptop that is tied to a domain (I work remote but not VPN)

What can I do to troubleshoot this?

**Comment by mvelosop** [comment]
Hi @isaac2004,

It might be a network policy from your domain, let's try to devise a method to diagnose this (very common) issue.

Please attach the output files from these PS commands:

```poweshell
Get-NetIPConfiguration -InterfaceAlias "vEthernet (DockerNAT)" > docker-nic.txt
Get-NetFirewallRule | where {$_.Description -match "vpnkit"} > vpnkit-firewall-rules.txt
```

Hope this helps.

**Comment by isaac2004** [comment]
# docker-nic
````

InterfaceAlias       : vEthernet (DockerNAT)
InterfaceIndex       : 17
InterfaceDescription : Hyper-V Virtual Ethernet Adapter #3
NetProfile.Name      : Unidentified network
IPv4Address          : 10.0.75.1
IPv6DefaultGateway   : 
IPv4DefaultGateway   : 
DNSServer            : fec0:0:0:ffff::1
                       fec0:0:0:ffff::2
                       fec0:0:0:ffff::3


````

# vpnkit-firewall-rules

````
empty
````

**Comment by mvelosop** [comment]
Hi @isaac2004, I'm sorry for the delay.

I find it strange there are no firewall rules for the vpnkit program.

Could you try disabling the firewall for a moment

- If that fixes the issue, then add a rule to allow the vpnkit program through the firewall
- If that doesn't fix the issue, there might be a corporate restriction for non private or domain networks, that might be fixed with the script: [cli-windows/set-dockernat-networkategory-to-private.ps1](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/cli-windows/set-dockernat-networkategory-to-private.ps1)

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now, but feel free to comment, will reopen if needed.
