### ISSUE TITLE
localization in net core microservices architecture 

### ISSUE THREAD

**Issue by nyghtrocker** [dotnet-architecture/eShopOnContainers#1132]
Which approach will be best to setup localization in .net core microservices. Each microservices will display error messages, validation messages etc in user different languages. Should we have one CMS that have all localize content or each microservices has its own localize content in json file.

**Comment by mvelosop** [comment]
Hi @nyghtrocker,

As usual, it depends on the whole context.

So, as a general answer, considering that the main focus when using microservices is to keep them as independent as possible and since having many of them depending on a single one creates a single point of failure, that doesn't seem appropriate.

Also, considering the independence of the dev teams. it might be better to have each team develop the related content, to de deployed along the correct version of the microservices.

Hope this helps,

**Comment by mvelosop** [comment]
Closing this issue now, but feel free to comment, will reopen if needed.
