### ISSUE TITLE
A Pluralsight Video Tutorial for Microservices Architecture?

### ISSUE THREAD

**Issue by fingers10** [dotnet-architecture/eShopOnContainers#1134]
Hello Team,

This is my suggestion. Is there any Pluralsight course available for eShopOnContainers or planning to be published? This could help many new developers to learn and build projects side by side from scratch.

Thanks,
Abdul

**Comment by mvelosop** [comment]
Hi @fingers10,

Well, that'd probably be a quite large course, and it's not in plans, at least that I know of.

There is, however a [video on CH9](https://channel9.msdn.com/events/Ignite/Microsoft-Ignite-Orlando-2017/BRK3317) with a nice introduction to eShopOnContainers from @CESARDELATORRE, that might help you get started.

After that, you might want to explore the [on-line guide](https://docs.microsoft.com/dotnet/architecture/microservices/index), that you can also download as an [e-book](https://aka.ms/microservicesebook), which would certainly be the textbook for the course 😉

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.

**Comment by markheath** [comment]
You might be interested to know that I recently published a Pluralsight course called "[Microservices Fundamentals](app.pluralsight.com/library/courses/microservices-fundamentals)" which uses eShopOnContainers as the demo application to illustrate some of the principles being discussed. 

It's unfortunately not a course about eShopOnContainers, because the course was not supposed to be specific to a technology like .NET, but I think eShopOnContainers is a great way to showcase lots of good microservices architectural practices and patterns. 

I'm currently working on another Pluralsight course in the same series and again I will be using eShopOnContainers as the example application.

I should also take this opportunity to say a big thank you to the creators of eShopOnContainers for creating such a helpful learning resource with excellent supporting documentation.

**Comment by fingers10** [comment]
@markheath many thanks for the course. I'll have a look on this. Waiting for your new course with eShopOnContainers as well.

**Comment by neoAnkit** [comment]
> You might be interested to know that I recently published a Pluralsight course called "[Microservices Fundamentals](app.pluralsight.com/library/courses/microservices-fundamentals)" which uses eShopOnContainers as the demo application to illustrate some of the principles being discussed.
> 
> It's unfortunately not a course about eShopOnContainers, because the course was not supposed to be specific to a technology like .NET, but I think eShopOnContainers is a great way to showcase lots of good microservices architectural practices and patterns.
> 
> I'm currently working on another Pluralsight course in the same series and again I will be using eShopOnContainers as the example application.
> 
> I should also take this opportunity to say a big thank you to the creators of eShopOnContainers for creating such a helpful learning resource with excellent supporting documentation.

pagw not found

**Comment by markheath** [comment]
Sorry about that! The full link (it was just missing https://) is [here](https://www.pluralsight.com/courses/microservices-fundamentals), and the follow-on course that also uses eShopOnContainers for the demo scenario is called [Building Microservices](https://www.pluralsight.com/courses/building-microservices)

**Comment by neoAnkit** [comment]
> Sorry about that! The full link (it was just missing https://) is [here](https://www.pluralsight.com/courses/microservices-fundamentals), and the follow-on course that also uses eShopOnContainers for the demo scenario is called [Building Microservices](https://www.pluralsight.com/courses/building-microservices)

Does it cover every aspect of eshoponcontainer?

**Comment by markheath** [comment]
No, it just uses eShopOnContainers as a good example of a non-trivial microservices application

**Comment by sughosneo** [comment]
Here are the few more MS learn modules on microservices https://docs.microsoft.com/en-us/dotnet/architecture/

![image](https://user-images.githubusercontent.com/13281246/100601346-7768d700-3328-11eb-9457-a56a0d7868dc.png)
