### ISSUE TITLE
Usage of Azure Key Vault as secrets storage

### ISSUE THREAD

**Issue by Uriil** [dotnet-architecture/eShopOnContainers#1135]
I've tried to follow your example of adding AzureKeyVault secrets to app, but those settings(the ones from Azure Key Vault) were overridden by config file settings:

	public class Program
	{
		public static int Main(string[] args)
		{
			var configuration = GetConfiguration();
			
			var host = BuildWebHost(configuration, args);

			host.Run();

			return 0;            
		}

		private static IWebHost BuildWebHost(IConfiguration configuration, string[] args) =>
			WebHost.CreateDefaultBuilder(args)
				.UseStartup<Startup>()
				.UseConfiguration(configuration)
				.Build();

		private static IConfiguration GetConfiguration()
		{
			var builder = new ConfigurationBuilder()
				.SetBasePath(Directory.GetCurrentDirectory())
				.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
				.AddEnvironmentVariables();

			var config = builder.Build();

			if (config.GetValue<bool>("UseVault", false))
			{
				builder.AddAzureKeyVault(
					$"https://{config["Vault:Name"]}.vault.azure.net/",
					config["Vault:ClientId"],
					config["Vault:ClientSecret"]);
			}

			return builder.Build();
		}
	}

I've ended up with usage of `ConfigureAppConfiguration` extension method, like this:

	public class Program
	{
		public static int Main(string[] args)
		{			
			var host = BuildWebHost(args);

			host.Run();

			return 0;            
		}

		private static IWebHost BuildWebHost(string[] args) =>
			WebHost.CreateDefaultBuilder(args)
				.UseStartup<Startup>()
				.ConfigureAppConfiguration((context, configurationBuilder) =>
                {
                    var config = configurationBuilder.Build();

                    if (config.GetValue("KeyVault:Enabled", true))
                    {
                        var prefix = config.GetValue<string>("ApplicationId").Replace(".", string.Empty);
                        configurationBuilder.AddAzureKeyVault(
                            $"https://{config["KeyVault:Name"]}.vault.azure.net/",
                            config["Settings:ApplicationId"],
                            config["Settings:ApplicationSecret"], new PrefixKeyVaultSecretManager(prefix));
                    }
                })
				.Build();
	}

**Comment by clouddna-au** [comment]
Yes the better approach would be to use the ConfigureAppConfiguration

**Comment by mvelosop** [comment]
Hi @Uriil, thanks for the heads up 👍

Will mark this as a bug to test and fix it.

**Comment by Uriil** [comment]
@mvelosop if you will confirm this as a bug, I will be glad to to help to fix it

**Comment by mvelosop** [comment]
Hi @Uriil,

We couldn't find anything wrong with the way the configuration is being used.

In the code sample you posted, getting the configuration before and then "using" it in the webhost builder doesn't add value, so your change makes sense.

However, in eShop it's being done the way it is, as shown here:

https://github.com/dotnet-architecture/eShopOnContainers/blob/5b17183657972bc215e22f37552607d3dd15f7eb/src/Services/Ordering/Ordering.API/Program.cs#L23-L61

To be able to log startup errors, because otherwise they end in an error 500 that's not usually easy to find out.

That said, the `UseConfiguration` extension method is going to be replaced with `AddConfiguration`  option using `ConfiguraAppConfiguration` because that's a better way to do it.

You might try the above solution in your setup, as it might also fix your issue.

Hope this helps.
