### ISSUE TITLE
Containerized RabbitMQ Integration Test Setup 

### ISSUE THREAD

**Issue by nxtx** [dotnet-architecture/eShopOnContainers#1147]
My concerns revolve around how to test if a service is successfully subscribing, publishing, and listening to subscribed events through RabbitMQ---all containerized: RabbitMQ, my service, database, and etc. all run in their separate container all orchestrated using docker-compose. 

My service is one of the hundreds of services of the application, each can be developed by different team and in different languages. Hence, I do not necessarily (can) have all the services running to run a test. Therefore, my tests are scoped to my service only. 

It was not clear to me from this sample project how to setup such integration tests. My specific questions are: 

1- For the integration test, do I need to have one docker image for the service and a separate one for the integration tests, in addition to the RabbitMQ and database containers?
2- Is it recommended to have different docker-compose than the dev docker-compose for integration tests? (I guess so, just double-checking.)

**Comment by mvelosop** [comment]
Hi @nxtx, that's a good question! 👍

You do have to set up a container for the tests, besides the regular application and infrastructure containers.

The tests  containers will be sort of clients using the application containers.

You might want to take a look at the [Unit and integration testing](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Unit-and-integration-testing#global-integration-tests-across-microservices) in the wiki for more details.

Hope this helps.

**Comment by nxtx** [comment]
Thanks @mvelosop 

Is it recommended that I create a separate `docker-compose` for integration tests? hence having something like this: 

```
│   docker-compose-integration-tests.dcproj
│   docker-compose-integration-tests.dcproj.user
│   docker-compose-integration-tests.override.yml
│   docker-compose-integration-tests.yml
│   docker-compose.dcproj
│   docker-compose.dcproj.user
│   docker-compose.override.yml
│   docker-compose.yml
```

**Comment by nxtx** [comment]
any updates on this?

**Comment by RobsonKarls** [comment]
I think if you want to really test, you should spin up all the containers you depend on and right integration tests for each case you want to test.

**Comment by nxtx** [comment]
@RobsonKarls actually the question is "what are the best practices for that?" 
 
As I asked earlier, is it recommended to create multiple `docker-compose` as I showed earlier?

**Comment by mvelosop** [comment]
Hi @nxtx,

It's hard to talk about best practices because it depends on the context, however, as for the first question, you need separate images for the services, but the integrations test projects are basically client apps exercising the APIs (requests, messages, RPCs), so they don't need to be in containers. Probably it doesn't matter where the tests are run from, but the services will probably need a specific well defined context, that could include a pre-seeded database.

For functional tests (not load tests) a setup like the one in eShopOnContainers, where there's a single container with all DBs could prove useful.

As for the second one, most probably you'll need separate docker-compose files, however, I haven't tried multiple docker-compose projects.

However, since the tests docker-compose files should probably be some sub-set or sub-set + variations of the original docker-compose set of files, and since docker-compose files have to be tweaked manually,  you might be better off creating them manually too.

Hope this helps.

**Comment by nxtx** [comment]
@mvelosop thanks, it helps a lot. 

> but the integrations test projects are basically client apps exercising the APIs (requests, messages, RPCs), so they don't need to be in containers. 

(I am very new to the dockerized tests world, so my apologies in advance if this sounds very trivial.) That is in fact what confuses me. Lets say my app is started in a docker container using `docker-compose`, how an integration test can see the app and test it? would not the tests need to know the endpoint at which they can reach the app, and is not this endpoint set via `docker-compose`?

**Comment by RobsonKarls** [comment]
> @RobsonKarls actually the question is "what are the best practices for that?"
> 
> As I asked earlier, is it recommended to create multiple `docker-compose` as I showed earlier?

@nxtx well, I like the idea to have the containers because it is a peace of code that you depende upon, but you dont need to know its internals. Here where i work we actually use inMemory implementations of the services we need to  implement our integration tests, for example,  we use in memory version of EF, we have an in memory DistributedCache and so on. I find it useful, because once we have all the in memory dependence setup, we dont need to worry about it anymore.

**Comment by mvelosop** [comment]
Hi @nxtx, I'm sorry, I kind of mixed a few concepts here. Will make my best to explain it clearer this time.

**Load testing** requires the actual services running in containers and the test projects (test applications) are clients that can run anywhere.

**Integration/Functional testing** runs the services in a specialized `TestServer` that allows you to create specialized `HttpClients` to test the endpoints, **without running the real services in separate containers**.

The integration test projects are test applications that use your API project an run it in the `TestServer`. 

You can configure the `TestServer`, much like you do in the Startup in the "real API project", to use either mock services or real services, So you can, for example, use an In-Memory DB for tests.
instead of a real SQL Server, as mentioned @RobsonKarls.

Integration tests use real services, while functional tests can use mock services, as usual it depends on your needs. Will use integrations tests for short, but they are pretty similar from this point of view.

You can run the test projects either in containers or in VS.

If you want to run the integrations test projects in containers, run this command:

```poweshell
docker-compose -f .\docker-compose-tests.yml -f .\docker-compose-tests.override.yml up
```
If you check the running containers quickly after starting the above command, you should see something like this:

![image](https://user-images.githubusercontent.com/7357806/67618499-47c3d300-f7e8-11e9-94aa-75c89cb9aaa6.png)

Where you should see that the top containers are running the tests (`dotnet test...`).

After a while, when the test complete, you should see something like this:

![image](https://user-images.githubusercontent.com/7357806/67618526-970a0380-f7e8-11e9-9fc4-ec163aef4014.png)

Where you should only see the "external services" or infrastructure containers, like SQL Server, RabbitMQ, and so on.

You can see the result of the above test runs in the folder `test-results` in the root of eShopOnContainers.

At this point you could also open up the `eShopOnContainers-ServicesAndWebApps` solution in VS and go to the Test Explorer, filter for Functional tests and run them all, you should see the tests run successfully:

![image](https://user-images.githubusercontent.com/7357806/67618596-637ba900-f7e9-11e9-9e0f-f2dd98de3702.png)

You should also get the same result from VS, by starting up only the infrastructure services with this command:

```powershell
docker-compose -f .\docker-compose-external.yml -f .\docker-compose-external.override.yml up
```

And then running the tests from VS.

The `docker-compose-external*.yml` files start only the infrastructure containers without running the tests.

Hope this helps better this time.

**Comment by nxtx** [comment]
@mvelosop @RobsonKarls thanks for the clarifications.
