### ISSUE TITLE
Can you swap out Event Bus with AWS Kinesis

### ISSUE THREAD

**Issue by freeborn5** [dotnet-architecture/eShopOnContainers#1163]
I love your project but here where I work they would like to use Kinesis as the Message Queue-  

1. Is this wise?
2. how do you think it could be implemented

**Comment by mvelosop** [comment]
Hi @freeborn5, thanks for you question!

I don't really know Kinesis, but from a quick read of the [home page](https://aws.amazon.com/kinesis/) it doesn't seem to be the most appropriate product.

Keep in mind that the implemented option for message queuing in eShopOnContainers are RabbitMQ or Azure Service Bus, not Event Bus.

You should be able to use any message queuing service (in eShopOnContainers) if you implement the required [Abstractions](https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/src/BuildingBlocks/EventBus/EventBus/Abstractions).

You'll also have to modify the startup code in the microservices using the queue, because initial configuration is not abstracted as it is the queuing service use.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
