### ISSUE TITLE
Validate data between two service Catalog,Basket

### ISSUE THREAD

**Issue by dinhle2010** [dotnet-architecture/eShopOnContainers#1171]
Thanks for share project eShopOnContainers.
My question is: Example i want check product exist before create Basket. How i can do that because product list only exist on API Catalog.

**Comment by mvelosop** [comment]
Hi @dinhle2010, that's a good question!

The approach with a microservices architecture is a bit different.

In this case the basket microservice doesn't need a catalog, since the items in each cart are added from the MVC (or SPA) web app, with all the information needed from the catalog.

So each cart has a copy of the data needed from each item of the catalog.

You might want to take a look at this articles from the [.NET Microservices guide](https://docs.microsoft.com/dotnet/architecture/microservices/) related to this topic:

- [Data sovereignty per microservice](https://docs.microsoft.com/dotnet/architecture/microservices/architect-microservice-container-applications/data-sovereignty-per-microservice) and
- [Challenges and solutions for distributed data management](https://docs.microsoft.com/dotnet/architecture/microservices/architect-microservice-container-applications/distributed-data-management).

Hope this helps.

**Comment by dinhle2010** [comment]
Hi @mvelosop,
Thanks for helps.
