### ISSUE TITLE
How to handle transactions among multiple microservices?

### ISSUE THREAD

**Issue by abolfazlmohammadiseif** [dotnet-architecture/eShopOnContainers#1173]
Hi
I have multiple microservices. I update a record within microservice A then send an event to microservice B and do another update in microservice B. if the second update fails, I need the first one to be roll-backed. how should I handle such a transaction?
Thanks in advance

**Comment by mvelosop** [comment]
Hi @abolfazlmohammadiseif, that's an interesting question!

It's hard to answer that question in general, because, as usual, it all depends on the context.

But, in general, I'd say that looks a lot like a distributed transaction, and a candidate for Two Phase Commit. If that's the case, then it's probably not a good idea to have those DB in separate microservices, because the compensatory actions for such scenario could get quite complicated.

You might find the following sections from the [Microservices Architecure guide](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/) interesting for this topic:

- [Data sovereignty per microservice](https://docs.microsoft.com/dotnet/architecture/microservices/architect-microservice-container-applications/data-sovereignty-per-microservice) and

- [Challenges and solutions for distributed data management](https://docs.microsoft.com/dotnet/architecture/microservices/architect-microservice-container-applications/distributed-data-management)

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.

**Comment by abolfazlmohammadiseif** [comment]
> Closing this issue now but feel free to comment, will reopen if needed.
Thank you very much. I'm working on your suggestions.
