### ISSUE TITLE
BrokenCircuitException`1: The circuit is now open and is not allowing calls.

### ISSUE THREAD

**Issue by sgalcheung** [dotnet-architecture/eShopOnContainers#1175]
My WebStatus microservice: http://localhost:5107/ can run well, but the Home Page of eShopOnContainers:http://localhost:5100/ can not work correctly, see the screenshot.
![image](https://user-images.githubusercontent.com/42566429/69416888-9bc3c800-0d52-11ea-805e-129d4faccc21.png)
![image](https://user-images.githubusercontent.com/42566429/69416929-b39b4c00-0d52-11ea-9da3-299fe3377af1.png)

**Comment by mvelosop** [comment]
Hi @sgal008,

Could you try to run the app from the CLI as per the [Windows setup wiki page](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#build-and-deploy-eshoponcontainers)?

Anyway, keep in mid that when you run the app from VS with debugging (F5) it's normal that you get connection exceptions like the one shown next:

![image](https://user-images.githubusercontent.com/7357806/69420877-87160e80-0d17-11ea-93bd-4127426893dc.png)

And when you do, it's important that you press F5 or the continue button, as many times as needed.

![image](https://user-images.githubusercontent.com/7357806/69421232-639f9380-0d18-11ea-9e0e-b9b2a319a93a.png)

Until the app starts completely, otherwise you might get some errors like the one you report.

Hope this helps.

**Comment by sgal008** [comment]
I just from [the CLI Windows setup wike page](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup) appear this error, not run from vs.

**Comment by baijdzm** [comment]
Having the same problem. 
The healthy check are all good but http://localhost:5100/ is not accessible.
It said: Polly.CircuitBreaker.BrokenCircuitException`1[System.Net.Http.HttpResponseMessage]: The circuit is now open and is not allowing calls.

**Comment by baijdzm** [comment]
But SPA can be open with error:
I found SPA can be opened. http://localhost:5104/
Error requesting catalog products, please try later on

**Comment by baijdzm** [comment]
Hi @sgalcheung, Do you still having this issue? Any suggestions?
Thanks in advance!

**Comment by sgalcheung** [comment]
Thanks, I will try.

**Comment by sughosneo** [comment]
Hi @sgalcheung , do you still face the same issue or is it resolved ? 

There have been some recent changes. Could you please take the latest from `dev` branch and test it ?

Thank you.

**Comment by sughosneo** [comment]
Hello Everyone, I am closing this issue as of now. If anyone has any further question, please feel free to reopen it.

Thank you.
