### ISSUE TITLE
Any other beginners need help getting this project setup ? 

### ISSUE THREAD

**Issue by punkouter2018** [dotnet-architecture/eShopOnContainers#1188]
Does there exist a video that shows how to put all the pieces together from scratch ? Or a more detailed explanation of whats going on  ?  EShopOnWeb is great and I totally understand that but going from that to this feels 100 times more difficult.  Or is there are any similar but easier examples anyone knows of so I can get the hang of microservices and containers ?

**Comment by nishanil** [comment]
We recently streamlined the [wiki ](https://github.com/dotnet-architecture/eShopOnContainers/wiki) and the repo ReadMe to help Get Started quickly. For getting started locally, you just need the Docker configured right with the necessary tools installed in VS. Have you checked them out? Does it help? 

To run the sample, it is fairly straightforward - configure Docker as per these [instructions](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#configure-docker) then run them using `docker-compose up` or simply F5 from Visual Studio.

eShopOnContainers is a fairly simple app, however, the complexity comes in due to all of its modules built and deployed independently yet working with each other in a well-defined contract. We use Docker containers and Kubernetes for our deployments. They are an excellent fit for building and deploying independent microservices as it combines its configuration and dependencies into a single independently deployable unit. Unfortunately, that too brings in complexity 😐

We've explained these concepts in detail in these free e-Books available here: https://dotnet.microsoft.com/learn/aspnet/microservices-architecture 

Once you successfully build and run this application on your local machine, take the help of the Wiki and the book to understand the features better. 

If you're new to Containers and Kubernetes, get started with this link: https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/intro 

Recently, I came across this video [Microservices Fundamentals](https://app.pluralsight.com/library/courses/microservices-fundamentals/table-of-contents) on Pluralsight from @markheath

Let us know how it goes and send us your feedback as you progress.

**Comment by punkouter2018** [comment]
Yes. Ill be working on getting it to run. Found a udemy course which does a simplified version of this that is helping. 

https://www.udemy.com/course/aspnet-core-20-e-commerce-web-site-based-on-microservices-and-docker/learn/lecture/8448304?start=30#questions

**Comment by mvelosop** [comment]
Hi @punkouter2018 

Stay tuned, there might be something in this regard.

**Comment by punkouter2018** [comment]
For the 100s of hours put into the project spending an hour or so to talk about it would help.. In the realm of apps I tell my friends to understand when it comes to .NET it is this and eShopOnWeb.  That one has served as a great starting point.. and if I ever use docker at work I hope to do rthe same with this if I can figure out how to get started from scratch.
