### ISSUE TITLE
Works in Powershell does not work in VS2019

### ISSUE THREAD

**Issue by punkouter2018** [dotnet-architecture/eShopOnContainers#1203]
It compiles and run and everything seems deploys when I F5 docker compose . But I can't connect to anything. Any idea what the difference could be doing 

docker build
docker up

vs. 

Clicking Docker Compose ?

**Comment by punkouter2018** [comment]
I have a 16 gig machine and set up 4 gig in docker

**Comment by erikpique** [comment]
Hi @punkouter2018

If the error is a 503, it may be that if you wait a few seconds and refresh the browser everything works correctly. That is because the containers are all working, but some of the applications that reside inside have not yet given time to get up.

If it's not that error, can you give more error information?

Anyway, the difference you ask for is speed and memory usage, when running with F5 EVERYTHING runs much slower and requires more memory. You could also try assigning 6 GB RAM to Docker, it was recently reported that 4 GB weren't enough any more.

Greetings

**Comment by punkouter2018** [comment]
retested on freshly booted machine.. Intially its gives an error... Then I reload and the MVC page works.. but now the images are missing. .. any idea ?

**Comment by vid83** [comment]
I noticed another problem with Visual studio 2019: if I F5 the docker-compose project the WebSPA application doesn't work at all (404 - not found); if I start docker-compose from Powershell everything works smoothly...

**Comment by vid83** [comment]
> but now the images are missing. .. any idea ?

I solved the missing picture problem tinkering with the .env file in the docker-composer project. Try these settings:

ESHOP_EXTERNAL_DNS_NAME_OR_IP=host.docker.internal
ESHOP_STORAGE_CATALOG_URL=http://host.docker.internal:5202/c/api/v1/catalog/items/[0]/pic/
ESHOP_STORAGE_MARKETING_URL=http://host.docker.internal:5110/api/v1/campaigns/[0]/pic/

Please note that, after fixing the environment variables, in order to get the Mvc application to work you have to access via browser with this URL: http://host.docker.internal:5100/. Using the default startup URL (http://localhost:5100) I got an authorization error when I try to access the login page: "Sorry, there was an error : unauthorized_client".

Weirdest thing is that I can't explain how this could possibly work: as per [Docker desktop for Windows docs](https://docs.docker.com/docker-for-windows/networking/) the dns name host.docker.internal should be use for connecting FROM a container TO the host, and not vice versa, like in this case...

**Comment by sughosneo** [comment]
Considering this issue has been addressed already, I am closing this item as of now. But please feel free to reopen it if you have any questions. 

Thank you.
