### ISSUE TITLE
How hard is it to use windows containers?  

### ISSUE THREAD

**Issue by punkouter2018** [dotnet-architecture/eShopOnContainers#1216]
At my job we can only get docker using windows containers working but it seems this example uses Linux containers.. I am new to this and I have gotten the project work on my home machine. How hard is it to switch  ? Do I just change the sql MySQL etc.. all to grab a windows image instead of Linux or is it more complex than that?

**Comment by erikpique** [comment]
Hi @punkouter2018

That scenario hasn't been tested in quite a while, because it's seldom used but you could try, of course. There could be issues with some supporting containers though, like Redis or Seq. You should also verify that the environment variables have the correct values for the Windows containers.

Greetings.

**Comment by punkouter2018** [comment]
ok thanks. I don't know enough about it to figure it out myself but I get the sense people are just using Linux containers so I should just stick to that.
