### ISSUE TITLE
After Docker-up get the issue on the login page

### ISSUE THREAD

**Issue by Taifunov** [dotnet-architecture/eShopOnContainers#1236]
Done all by instructions but get this an error in login page

Sorry, there was an error : unauthorized_client
Request Id: 0HLTA3L5VSPET:00000019

**Comment by loxx123** [comment]
same problem here, no matter which repo is used, the same problem happens. WebSPA doesn't work as an alternative either. the only thing that works correctly on client side is the home page, everything else is down. i've tested all repos and all releases.

**Comment by vid83** [comment]
Looks like a common problem, i've got the exact same issue. I'm starting the docker-composer project in VS2019, with docker desktop for windows 2.2.0.3. Any hint for a possible solution?

**Comment by marcosharbs** [comment]
same problem here

**Comment by pedroyan** [comment]
Same issue here. I'm starting the project using VS2019 via the docker compose file and Docker Desktop Windows 2.2.0.3

**Comment by pedroyan** [comment]
I've looked around SEQ and found this entry. Might be useful

![image](https://user-images.githubusercontent.com/11574849/75634647-49fec980-5bee-11ea-9657-0e5fb9122dfb.png)

**Comment by vid83** [comment]
Actually I found a solution: you have to edit the .env file in the docker-composer project with these settings:

ESHOP_EXTERNAL_DNS_NAME_OR_IP=host.docker.internal
ESHOP_STORAGE_CATALOG_URL=http://host.docker.internal:5202/c/api/v1/catalog/items/[0]/pic/
ESHOP_STORAGE_MARKETING_URL=http://host.docker.internal:5110/api/v1/campaigns/[0]/pic/

Delete the sqldata container, since the Identity database should be rebuilt from scratches, and then restart the project: the MVC application should be accessible through this URL: http://host.docker.internal:5100/.

Still, I can't understand how this could possibly work: that symbolic name should be used for the connections FROM a container TO the host (source: [Docker Destktop for Windows docs](https://docs.docker.com/docker-for-windows/networking/), and not vice versa, like in this case...

**Comment by mohammed-fuad** [comment]
@pedroyan I‘ve a question which is beyond the issue 🙂, what is the name of the tool in screenshot used to debug such requests, is it Fiddler?

**Comment by pedroyan** [comment]
@mohammed-fuad Its called SEQ :) It is a log processing server application that comes with the solution. If you run the docker-compose file and go to http://localhost:5340/, you will be able to see it too

**Comment by nishanil** [comment]
Thank you, everyone, for reporting this issue. I wasn't able to reproduce this issue until I reset my docker and started the docker build fresh. I can confirm, this issue is valid and we are looking into it. 
@mvelosop probably, it is related to the fixes that went in as part of the DockerNAT issue reported earlier. 
Version tested: Docker Desktop 2.2.0.3.  Docker version 19.03.5, build 633a0ea.

**Comment by nishanil** [comment]
As a workaround, use `docker-compose up` and when the services are up navigate to 
`http://docker.for.win.localhost:5100/` for **webmvc** and 
`http://docker.for.win.localhost:5104/` for **webspa**

**Comment by vid83** [comment]
> As a workaround, use `docker-compose up` and when the services are up navigate to
> `http://docker.for.win.localhost:5100/` for **webmvc** and
> `http://docker.for.win.localhost:5104/` for **webspa**

In my case this didn't work, i had to use the host.docker.internal symbolic name. From what I can understand, the docker.for.win.localhost was deprecated (see [here](https://github.com/docker/for-win/issues/1764#issuecomment-385910460)

Btw, shouldn't this hostname be used for the connections FROM a container TO the host? How is it possible that a browser running in my host can access a web application running inside a container?

**Comment by mvelosop** [comment]
Hi everybody, let's try to figure it out.

I had the issue when upgrading to Docker Desktop 2.2 and could fix it by using the `docker.for.win.localhost` and just now I tried changing it to `host.docker.internal` and it worked just the same...

BUT, there's an important detail that that we have to consider.

The unauthorized client issue occurs because the service redirect uri, required to log in, isn't registered in the IdentityServer DB as an authorized client.

Those redirect uris are seeded in the IdentityServer DB upon creation, taking the values from the configuration in `docker-compose.override.yaml` file:

![image](https://user-images.githubusercontent.com/7357806/76345912-10b80f00-62fc-11ea-8f89-693598e099f6.png)

So, if we change now the initial url from `localhost` to `docker.for.win.localhost` or `host.docker.internal`, IdentityServer will reject the connections, because it only knows about `localhost` clients.

So there at least two possible solutions:

1. Update the table records by hand:

![image](https://user-images.githubusercontent.com/7357806/43640769-15b1d4f6-9719-11e8-97d3-5056296c5996.png)

2. Delete the containers, and just restart the app, **BUT first update the .env file like so**:

![image](https://user-images.githubusercontent.com/7357806/76349925-cd14d380-6302-11ea-8d32-3881ad625212.png)

That should do the trick.

If you get problems when restarting the containers, try dropping the related volumes too.

Hope this helps.

**Comment by HuzzDTX** [comment]
Work like a charm, thanks. you can run this command in SQL server to avoid updating values manually:
update ClientRedirectUris set RedirectUri = REPLACE(RedirectUri,'docker.for.win.localhost','localhost');

**Comment by HuzzDTX** [comment]
@mvelosop thanks, works like a charm, you can run this command in SQL server to avoid the manual update:
update ClientRedirectUris set RedirectUri = REPLACE(RedirectUri,'docker.for.win.localhost','localhost');

**Comment by mvelosop** [comment]
Glad this helped 😊

@HuzzDTX, thanks for the update command!  I'd only suggest to add a minor tweak:

```sql
update ClientRedirectUris set RedirectUri = REPLACE(RedirectUri,'host.docker.internal','localhost');
```

Since `docker.for.win.localhost` has been deprecated.
