### ISSUE TITLE
How to rollback state for microservice database in functional / integration tests?

### ISSUE THREAD

**Issue by dcs3spp** [dotnet-architecture/eShopOnContainers#1257]
Hi,

Finding the sample architecture really useful for learning microservices architecture. 

For functional testing of a microservice understand that creating a TestServer in a base class and performing migration on database with connection string in application settings.

How is the database reset to a clean state before running next test?
- Delete the database after each test?
- Create / Abort transaction for each test, not sure if nested transactions possible with EFCore?
- Clear tables after each test, e.g. provide a ContextSeedUp and ContextSeedDown?

Also asked question [here](https://stackoverflow.com/questions/60510597/integration-testing-with-asp-net-core-and-entity-framework-core-how-to-restore), on stackoverflow.

**Comment by mvelosop** [comment]
Hi @dcs3spp,

Depending on what you want to test you might use:

- An in-memory provider, as mentioned in [Testing with InMemory](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory), or
- The [Respawn](https://github.com/jbogard/Respawn) utility, that helps in clearing the tables. Although I'd recommend that you do it **before** running the tests, because it's usually helpful to explore the state of the database after a failed test run.

Hope this helps.

**Comment by dcs3spp** [comment]
Cheers thanks @mvelosop, have gone with the option of clearing the tables. Thanks again, appreciated :)
