### ISSUE TITLE
Error when pressing Login button locally on Mac [unauthorized_client]

### ISSUE THREAD

**Issue by sunny-sidhu** [dotnet-architecture/eShopOnContainers#1283]
I've updated the .env file to use the Mac variables as so:

```
ESHOP_EXTERNAL_DNS_NAME_OR_IP=docker.for.mac.localhost
ESHOP_STORAGE_CATALOG_URL=http://docker.for.mac.localhost:5202/c/api/v1/catalog/items/[0]/pic/
ESHOP_STORAGE_MARKETING_URL=http://docker.for.mac.localhost:5110/api/v1/campaigns/[0]/pic/
```

But get the following error: 

![image](https://user-images.githubusercontent.com/39477309/77905459-32af0c80-727e-11ea-946e-6bfc0ca1023c.png)

I've tried deleting all containers/images and trying again. i've also tried different variations of the DNS including **host.docker.internal** and **docker.for.mac.host.internal**. Both of these yield a worse result with catalog times not loading at all.

Here's my OS:

![image](https://user-images.githubusercontent.com/39477309/77906028-27101580-727f-11ea-9da3-b1fc13a6a122.png)

I'm using the beta version of chrome: 81.0.4044.83 (Official Build) beta

**Comment by sunny-sidhu** [comment]
Nevermind. I just worked out I need to start the app from the same DNS defined above and not localhost. E.g. for the SPA `http://docker.for.mac.localhost:5105/`

**Comment by mvelosop** [comment]
Hi @sunny-sidhu, please take a look at the updated [unauthorized_client error on Login](https://github.com/dotnet-architecture/eShopOnContainers/wiki/unauthorized_client-error-on-login) wiki page with this issue.

Please try with `host.docker.internal` instead of `docker.for.mac.localhost` because it's deprecated.

Hope this helps.
