### ISSUE TITLE
Is any other SQL server support

### ISSUE THREAD

**Issue by mmuruev** [dotnet-architecture/eShopOnContainers#1317]
I've found only one PostgreSQL mention in the main README. Is it possible to use other SQL servers or it's so specific to MSSQL?

**Comment by mvelosop** [comment]
Hi @mmuruev,

It should be possible, but you'd have to modify code in several files, because everything was done with SQL Server in mind.

I haven't worked with PostgreSQL so I wouldn't know for sure, but I guess you'd have to redo the migrations, and fix the configuration in the startup. Probably the seeding and perhaps some queries, that might be using some SQL Server-specific syntax.

You'd probably also have to take a look at the connection resiliency support using Polly, that's being used right now.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
