### ISSUE TITLE
[Question] Async queries?

### ISSUE THREAD

**Issue by pedroyan** [dotnet-architecture/eShopOnContainers#1325]
Hi all,

I came across the following paragraph while reading the .NET Microservices Architecture:

> If possible, never depend on synchronous communication (request/response) between multiple
microservices, **not even for queries.** The goal of each microservice is to be autonomous and available to the client consumer, even if the other services that are part of the end-to-end application are down or unhealthy. 

Even after finishing the book and digging the code in this repo, I couldn't find an example of a microservice asynchronously querying another but I did find examples of synchronous queries at aggregator level like when adding an item to the basket the aggregator triggers 2 sync queries to 2 different services.

![image](https://user-images.githubusercontent.com/11574849/82398096-61e52d00-9a28-11ea-94fc-21d53f4a4bf5.png)

That paragraph also boggles my mind a bit because queries are inherently synchronous. A query by definition expects a response.

One of the proposed solutions to the issue was data replication via integration events. That way all the information service A needs to query can be found within its boundaries due to the duplication of data from events published by service B.

But what if such replication is simply unfeasible? What if the work service B does is so granular that it would need to publish hundreds of thousands (perhaps millions) of events just for the sake of replication? What if a future service C depends on data from B but wasn't around by the time B published all those events? Wouldn't it make sense on those cases to just query B for its latest info? 

With that in mind, are there any examples in the solution that can illustrate an asynchronous query?

**Comment by mvelosop** [comment]
Hi @pedroyan, thanks for your feedback!

The idea behind the **not even for queries**, is not really to use asynchronous queries, but to update your (microservice) DB asynchronously, so it has all the information for the queries it needs, so that it depends from other microservices as less as possible.

Now, this is the ideal situation, real-life is something else.

The case you mention could be an extreme one in some contexts and yet a day-to-day situation in another context, so this is an absolute "it depends" 😉

This is no religion and there's no black and white, it always depends on your context at the moment you decide, so no worries, take it easy. Keep in mind that the paragraph you quoted starts with "**if possible**".

Hope this helps.

**Comment by pedroyan** [comment]
Hi Miguel,

Thanks a lot for your response :) 

It brought me a lot of clarity on the subject
