### ISSUE TITLE
How ApiGateway and BFF Aggregator work?

### ISSUE THREAD

**Issue by dev-fatih-erol** [dotnet-architecture/eShopOnContainers#1327]
I saw that question "Does request from client reach to MobileShoppingAggregator first?".
And  i read some answers but i didnt see any apigateway in your project thats way i want to ask why did you remove apigateway or how it is working?
[Question Link](https://github.com/dotnet-architecture/eShopOnContainers/issues/593#issuecomment-386358182)

**Comment by mvelosop** [comment]
Hi @dev-fatih-erol, 

There's still an API gateway, but the implemented was changed recently from Ocelot to Envoy.

That change came in because of plans to support gRPC for external communications and Ocelot didn't support that gGRPC by then. Actually AFAIK it doesn't support that yet.

Hope this helps.

**Comment by dev-fatih-erol** [comment]
Thank you for your answer.
