### ISSUE TITLE
How to use request / response design pattern with RabbitMQ?

### ISSUE THREAD

**Issue by tuphampro** [dotnet-architecture/eShopOnContainers#1328]
How to use request / response design pattern with RabbitMQ?

**Comment by mvelosop** [comment]
Hi @tuphampro, that's an interesting question!

AFAIK, the only way to implement request/response with RabbitMQ and most similar products is by using two messages, because messages are one-way.

So you can have message receipt acknowledgement, but that only tells you that the message reached it's destination, not that the receiver has done anything about it.

So the way to go would be to use two messages, as in:

- Service "A" sends a message (the request) to which service "B" is subscribed, and
- Service "B" sends a message (the response) to which service "A" is subscribed.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
