### ISSUE TITLE
Cannot launch SPA Webapp - Return Http Error 404

### ISSUE THREAD

**Issue by rekhajay** [dotnet-architecture/eShopOnContainers#1360]
I am unable to launch the SPA Webapp service - All the other endpoints work. Web SPA: http://localhost:5104     ---  **RETURNS 404** 

Web apps
Web MVC: http://localhost:5100
Web SPA: http://localhost:5104     ---  **RETURNS 404** 
Web Status: http://localhost:5107
Microservices
Catalog microservice: http://localhost:5101 (Not secured)
Ordering microservice: http://localhost:5102 (Requires login - Click on Authorize button)
Basket microservice: http://localhost:5103 (Requires login - Click on Authorize button)
Identity microservice: http://localhost:5105 (View "discovery document")

**Comment by rekhajay** [comment]
![image](https://user-images.githubusercontent.com/48165295/86660498-a492a280-bf9f-11ea-9849-2628a1b6cc7a.png)

**Comment by dereklew** [comment]
Are you using Visual Studio to launch?  If yes, I have a similar issue, have to try using "docker-compose up" to get everything up.

**Comment by rekhajay** [comment]
If, I manually run these commands:

Commands run:

1.       cd eShopOnContainers\src

2.       docker-compose build

3.       docker-compose up


Then both the SPA Web aPP, and the MVC app work fine.


However - If I build from visual studio, the MVC Web App works, but the SPA
web app returns a 404 on launching.


Microsoft tech support has been able to replicate this issue.


Will keep you posted on what they come up with.

**Comment by cryptSky** [comment]
You need to run these lines to make SPA work for you.

npm install
npm run build:dev

**Comment by n-stefan** [comment]
There are a few options to get the SPA web client to launch:
1. Use the "Release" build configuration instead of "Debug".

2. In docker-compose.dcproj add

`<DockerDevelopmentMode>Regular</DockerDevelopmentMode>`

however it will hurt build performance.

3. In WebSPA.csproj add

`<ContainerDevelopmentMode>Regular</ContainerDevelopmentMode>`

which should only hurt build performance for the WebSPA project.
Unfortunately it doesn't seem to work as of the time of writing this (Visual Studio Community 2019 Preview Version 16.8.0 Preview 6.0).

**Comment by hero3616** [comment]
Solution for me was:

1. cd src\Web\WebSPA\
2. npm install
3. ng build
4. Start debugging from VS2019
5. Browse to http://host.docker.internal:5104/ (or http://localhost:5104/)

**Comment by mvelosop** [comment]
Hi @sughosneo, this issue has fixed in commit https://github.com/dotnet-architecture/eShopOnContainers/commit/598c675811508f6a7c3cae6e12ce5cd0dc0f67e4 that merged to dev in PR https://github.com/dotnet-architecture/eShopOnContainers/pull/1587.

I'm closing it here.

Cheers 😊

**Comment by mvelosop** [comment]
I'm sorry I closed this one, I confused the issues for a moment.

Currently there are no scripts/commands to build the SPA ClientApp in VS, it's all done when building the container.

This is because the current SPA templates and support libraries didn't exist back then, when eShop was initially built.

So, there are two options to solve this issue, one is to revamp the SPA application to work with the current SPA templates. That would make it for a nice PR 😉

The other option is to follow the instructions on the [local SPA application setup wiki page](https://github.com/dotnet-architecture/eShopOnContainers/wiki/06.-(Optional)-Setting-the-Web-SPA-application-up)

The page is a bit dated but  should do it.

Hope this helps.
