### ISSUE TITLE
Can't run solution in Visual Studio debug mode

### ISSUE THREAD

**Issue by robertocg72** [dotnet-architecture/eShopOnContainers#1383]
Hello

I've followed the instructions in https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup to setup the project

When I run the project from either the console (i.e via `docker-compose build` and `docker-compose up`) or Visual Studio in Release mode, the solution runs without a problem but of course I can't debug with breakpoints, etc.; the Docker images pulled in this case are tagged with `linux-latest` (for example `eshop/webmvc:linux-latest`)

But when I  run the solution in Visual Studio Debug mode, other Docker images are pulled down (if not present), and they are tagged with `dev` (for example `eshop/webmvc:dev`), and Visual Studio shows 16(!) ovelapping dialog boxes with the message `Debugging Error: The program to debug can not be found on the container`

The logs of the running `dev` containers in Docker Desktop show the following message: `It was not possible to find any installed .NET Core SDKs. Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from: https://aka.ms/dotnet-download`

I've logged into the console of the running containers and executed `dotnet --list-sdks`, and that returned nothing (i.e. the sdks are not installed); I do get a list of runtimes (`Microsoft.AspNetCore.App 3.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]` and `Microsoft.NETCore.App 3.1.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]`) when I execute `dotnet --list-runtimes`

So of course the question is why Debug mode is not reusing the existing images (tagged `linux-latest`), or alternatively, why the images tagged with `dev` don't have dotnet sdks installed

I've gone through the trouble of manually installing dotnet sdks in every one of the running `dev` containers; in that case, I don't get the errors anymore, but after Visual Studio has started running in Debug mode, it simply stops without any message; of course this is not a good "solution"

Thanks in advance for any help

Roberto

**Comment by sughosneo** [comment]
Thanks @robertocg72  for the details. Here are the answers of your questions.

`Q-1) Why is not using same linux-latest image, when we run the application in  debug mode ?`

Visual Studio build docker image context using `dev` tag in `debug` mode.
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/visual-studio-tools-for-docker?view=aspnetcore-3.1#debug

For e.g - When you try to run a simple aspnet core app using `VS F5` debug mode, your `Container Tools` output in `output` windows looks to be as per below - 

![image](https://user-images.githubusercontent.com/13281246/89025438-7e64e600-d344-11ea-88bc-480fa0dd5317.png)

`Q-2) Under docker dev container why don't we see output of `dotnet --list-sdks` command ?`

Because  `dotnet/core/sdk` only uses to build the solution. But only aspnet runtime is used to host the application. 
This procedure is called multistage build. You can refer more details in here : https://docs.microsoft.com/en-us/visualstudio/containers/container-build?view=vs-2019

We don't need to install SDK separately in running containers. 

`Q-3) Why isn't my local application working ?`

This could be of few reasons. So, could you please try following below steps  ? :
- Clean up all the existing running container and unused images. 
- Then build the solution one more time in VS. 
- Select the `docker-compose` project start-up project and try to rerun this application. 
- If everything goes fine, you should be able to see WebMVC app is listening on http://localhost:5100/ or the DNS which has been configured in your `.env` file. By default it's - `docker.for.win.localhost` for windows os as of now.

`Q-4) VS environment has stopped running - Why ?`

This could be because of debugger got detached from the container or application specific container got stopped. You may want `clean` and `rebuild` the solution before try to run it again.

**For Further Reference :**

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-3.1

https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/multi-container-applications-docker-compose

Hope this helps !

**Comment by robertocg72** [comment]
Hello Sumit

Thank you for your reply and clarifications

I fixed the problem; your answer to my last question, where you say "This could be because of debugger got detached from the container" made me realise that I had come across this type of problem before, when the debugging session could not be attached or got detached

So I run VS as Administrator, and I couldn't open the VS solution because it was stored on a network drive; that also reminded me of some problem VS has when running as Administrator and trying to access network shares

So in my case the solution was to move the solution to a non-network drive, and then open it running VS as an Administrator; not it's working

Regards,

Roberto

**Comment by sughosneo** [comment]
Great ! thanks for the update @robertocg72
