### ISSUE TITLE
.\deploy-all-mac.ps1 does not have the correct helm install command

### ISSUE THREAD

**Issue by noahjd** [dotnet-architecture/eShopOnContainers#1409]
Hello, 

I tried spinning on the project locally on my minikube cluster following the wiki, and the .\deploy-all-mac.ps1 does not seem to have the correct helm install command. When running this locally on mac, you will see the following:

```
Installing Api Gateway Chart: apigwmm
Helm Command: helm install eshop-apigwmm --values app.yaml --values inf.yaml --values ingress_values_dockerk8s.yaml  --set app.name=eshop --set inf.k8s.dns=localhost  --set image.pullPolicy=Always --set inf.mesh.enabled=False --set ingress.hosts=`{localhost`} --set inf.tls.enabled=False apigwmm
Error: This command needs 1 argument: chart name
```

for each chart that it tries to install.

**Comment by sughosneo** [comment]
Hello @noahjd, thank you for reaching out. 

I haven't personally tried the solution with `minikube cluster`. Could you please check the helm version installed in your local ?

For more details, you could refer [Install Helm](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes#install-helm)

**Comment by sughosneo** [comment]
Hello @noahjd,

As of now, we are only supporting local k8s deployment with `Docker for Desktop` for both Windows and MacOS. 
Due to bandwidth and maintainability, we have kept this item (*Install eShopOnContainers on Minikube*) as a low priority. But if anyone in the community wants to give this a try with `Minikube` and capture the steps as blog/article, we will be happy to link it in the wiki.

**Comment by erjain** [comment]
This issue is stale because it has been open for a long ago. I am closing this issue as of now. Please feel free to reopen it, if needed.
