### ISSUE TITLE
Install eShopOnContainers on Minikube 

### ISSUE THREAD

**Issue by spabbi007** [dotnet-architecture/eShopOnContainers#1418]
Hi,

Can you please share the instructions for installing eShopOnContainers application on:
1) Minikube (with VM driver as VirtualBox) running on Windows
2) Minikube running on Linux

I could find instructions for installing eShopOnContainers on Windows using Docker Desktop:
a) https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup
b) https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes

but could not locate the instructions for deploying on Minikube on Windows or on Linux.

Thanks.

**Comment by sughosneo** [comment]
Hello @spabbi007, thank you for reaching out. 

As of now, we are only supporting local k8s deployment with `Docker for Desktop` for both Windows and MacOS. 
Unfortunately due to bandwidth and maintainability, we have kept this item (*Install eShopOnContainers on Minikube*) as a low priority. But if anyone in the community wants to give this a try with `Minikube` and capture the steps as blog/article, we will be happy to link it in the wiki. 

Hope this helps !
