### ISSUE TITLE
Refused to load the script 'http://host.docker.internal:5105/lib/jquery/jquery.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

### ISSUE THREAD

**Issue by ghamry** [dotnet-architecture/eShopOnContainers#1428]
I've newly cloned the app and that happens when I try to go to the login page 
![Untitled](https://user-images.githubusercontent.com/6347354/93141855-97a3d500-f6ed-11ea-974e-c94c5120ecb6.png)

**Comment by sughosneo** [comment]
Hi @ghamry,  Thank you for reaching out. 

To my opinion, the actual issue here is "unauthorized_client". Are you using http://localhost:5100/ to browse the WebMVC app ? Because that's when you would see the above error message.
Ideally the request should reach to the Identity Server from the same source and for that you should use the below urls :

Web MVC : http://host.docker.internal:5100/
Web SPA : http://host.docker.internal:5104/

Hope this helps !

**Comment by ghamry** [comment]
hi @sughosneo first of all thanks for your reply 
but as you can see from the attached screenshot 
I'm using  http://host.docker.internal:5105 not localhost

**Comment by sughosneo** [comment]
> hi @sughosneo first of all thanks for your reply
> but as you can see from the attached screenshot
> I'm using http://host.docker.internal:5105 not localhost

Thanks for the update @ghamry. 

Actually in the screenshot, I see the request has already been redirected to the Identity Server which is listening on http://host.docker.internal:5105 and that can happen irrespective of you are browsing the Web MVC or Web SPA using `localhost` or `host.docker.internal`. 

Do you see the same behavior with Web SPA too ? URL : http://host.docker.internal:5104/
Also, if you could try to access the below URLs in In-Private/InCognito window of Edge/Chrome browser ? 

Web MVC : http://host.docker.internal:5100/
Web SPA : http://host.docker.internal:5104/

**Comment by sughosneo** [comment]
Hi @ghamry , just checking if you had a chance to look into this further ? Thanks.

**Comment by Mahenbisht** [comment]
I have exactly same error, when I try to login.

**Comment by sughosneo** [comment]
> I have exactly same error, when I try to login. What is the solution for this error.

Hi @Mahenbisht, there could be different reasons behind this behaviour. 
You may want to refer our documented wiki page for [unauthorized_client error on Login](https://github.com/dotnet-architecture/eShopOnContainers/wiki/unauthorized_client-error-on-login).

Hope this helps !

Thank you

**Comment by sughosneo** [comment]
I am closing this issue as of now, If you have any further questions, please feel free to reopen it. 

Thank you.

**Comment by amarendratollplus** [comment]
Hello Everyone,
I am facing the below mentioned issue and debugging the source code using visual studio 2019.  As mentioned in the above messages I changed the path in MVC application/ appsettings.json file from 
"CallBackUrl": "http://localhost:5100/" to "CallBackUrl": http://host.docker.internal:5100/" but even after changing i am facing the same issue.

Issue:
Refused to load the script 'http://host.docker.internal:5105/lib/jquery/jquery.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Please let me know how to proceed further.

Regards,
Amarendra.

**Comment by Basel78** [comment]
@sughosneo<
Thanks for your comment, I've tried to run the eshop online on docker and was able to load the homepage of MVCpp in http://host.docker.internal:5100/, but when trying to login by "demouser@microsoft.com" the authentication failed, and by looking into the Identity logs in docker dashboard I noticed  warring message : Certificate CN=idsrv3test has expired on 01/20/2020 22:00:00
is that possible the reason behind the sign in failure.. although the [ClientRedirectUris]table has the correct urls: http://host.docker.internal:5100/signin-oidc and user is created in the [Microsoft.eShopOnContainers.Service.IdentityDb] DB properly.. any suggestions?

**Comment by sughosneo** [comment]
Hi @Basel78,

Content security policy error shouldn't stop you login to the app. You may want to check this old issue https://github.com/dotnet-architecture/eShopOnContainers/issues/1302 which actually talked about similar behavior. 

Thank you.
