### ISSUE TITLE
Why the API Gateway communicates directly with microservices without going through the event bus?

### ISSUE THREAD

**Issue by Hp93** [dotnet-architecture/eShopOnContainers#1493]
Hi, I'm learning microservice architecture through the ebook, I have a question about the architecture, not the code. Not sure if I should ask it here?

As I understand, API Gateways connect directly with each microservices using HTTP (gRPC or REST), without going through the Even Bus.
I can think of some issues with this approach:
- API gateways need to know about the microservices and where they are located (server, IP address, port...).
- We need to set up a load balancer if we want to run more instances of a microservice.
- Lacking feature that Event Bus support like message queue...

So I wonder if we already have an event bus, why don't use it, and why the event bus is only used between microservices?

There are also some features that I think are missing from the event bus (rabbitMQ):
- Process multiple requests (messages) in parallel to utilize resources (like web API): could this be solved by running more instances?
- Request/response pattern: this can be implemented using temporary queues to wait for responses.

**Comment by sughosneo** [comment]
Hi @Hp93, thank you for reaching out. 

Yes, `eShopOnContainers` is the reference application for the eBook [.NET microservices - Architecture e-book](https://docs.microsoft.com/dotnet/architecture/microservices/)

EventBus is been used to implement asynchronous event-driven communication among different microservices. RabbitMQ has been used as a choice of event bus to keep the implementation simple. But for production scenario you may want to use managed services like *Azure Event Bus*. You can refer [Asynchronous-messaging](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Asynchronous-messaging) for more details. And you can read the implementation specific details in [here](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/integration-event-based-microservice-communications)

Whereas the purpose of having an API Gateway pattern is to provide the specific backend for frontends For e.g [BFF-Implementation](https://github.com/dotnet-architecture/eShopOnContainers/wiki/BFF-implementation)
Apart from supporting basic routing between clients and individual microservices, API gateway also helps in providing many advance features like compositions of the granular microservices API call, rate-limiting, authorization etc..
It also can be seen a uniform layer for the client for interacting to different microservices in a similar manner irrespective of how it has actually been implemented internally or even ignoring the fact of which specific communication protocol that microservice supports. Initially `Ocelot` had been used as an API gateway but later that has been replaced with `Envoy` service proxy. But that architecture point of view there is not much of a difference.
API gateway is more like a pattern and it doesn't emit any event or consume any messages of it's own to make pub-sub communication happen through the event bus. If you refer the [architecture](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/img/eShopOnContainers-architecture.png) of eShopOnContainers you would notice 
each microservice has it's own API gateway where they get registered in API Gateway with the name rather with hard coded ip address and port. So that the service gets discoverable internally through it's name both in local or production scenario.   

Further references :

[The API gateway pattern versus the Direct client-to-microservice communication](https://docs.microsoft.com/dotnet/architecture/microservices/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-api-gateway-pattern)

[Implement API Gateways with Ocelot](https://docs.microsoft.com/dotnet/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot)

Hope this helps !

**Comment by sughosneo** [comment]
Hi @Hp93, Considering the original questions have been answered, I am closing this issue as of now. 
If you have any further questions, please feel free to reopen it.

Thank you.

**Comment by ryanwaite28** [comment]
> Hi, I'm learning microservice architecture through the ebook, I have a question about the architecture, not the code. Not sure if I should ask it here?
> 
> As I understand, API Gateways connect directly with each microservices using HTTP (gRPC or REST), without going through the Even Bus. I can think of some issues with this approach:
> 
> * API gateways need to know about the microservices and where they are located (server, IP address, port...).
> * We need to set up a load balancer if we want to run more instances of a microservice.
> * Lacking feature that Event Bus support like message queue...
> 
> So I wonder if we already have an event bus, why don't use it, and why the event bus is only used between microservices?
> 
> There are also some features that I think are missing from the event bus (rabbitMQ):
> 
> * Process multiple requests (messages) in parallel to utilize resources (like web API): could this be solved by running more instances?
> * Request/response pattern: this can be implemented using temporary queues to wait for responses.

Just to add to this:

The API gateway, like @sughosneo said, is the entrypoint for clients (web, mobile); it's main job is using the various microservices to compose a response for the request. The gateway doesn't have to connect to microservices with REST, it can use messages and wait for a response to that message. When a client makes a request, the server has to respond to that request because that's the global standard for communication; client's don't communicate in any other protocol except HTTP.

What that means is, the server can't send an event to a microservice and listen for a response meanwhile do nothing with the client's request, what will the server do with the client's request if the event never gets picked up? 

There's a difference between messages and events. A message is basically a command/instruction for a microservice to **do something**, for example PING. A microservice listens for that message and emits an event that **something happened**. Usually a message is only handled by one listener while events are broadcasted to many listeners.
