### ISSUE TITLE
MacOS Catalina 10.15.7 - Docker Compose -   Login Error: "Microsoft.eShopOnContainers.Services.CatalogDb" 

### ISSUE THREAD

**Issue by jeffreywstevens** [dotnet-architecture/eShopOnContainers#1499]
On the healthcheck app: localhost:5107 both Catalog and Marketing are throwing this error:

Cannot open database "Microsoft.eShopOnContainers.Services.CatalogDb" requested by the login. The login failed. Login failed for user 'sa'.

I can only assume that is why Web Shopping and Mobile Shopping are also unhealthy.

Is there a way to correct this?  It works great on Windows except that images are broken on refresh.

**Comment by sughosneo** [comment]
Hi @jeffreywstevens, thank you for reaching out.

This could be because of the **Microsoft.eShopOnContainers.Services.CatalogDb** database wasn't created properly. You could run the solution by following below mentioned steps. 

- Perform clean up 

```powershell

docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
docker volume rm $(docker volume ls -q)

```
> !IMPORTANT: Above commands will clean up all running containers and it's data in your MacOS/Workstation. So you want to be careful on that.

- You need to make the following changes in the `.env` file.

 > Comment out `host.docker.internal` windows section.
 > Uncomment `docker.for.mac.localhost` DNS name section.

```powershell
docker-compose up sqldata
```
- once it's ready to accept the connection then you can bring up the other container by using the following command from a separate terminal

```powershell
docker-compose up
```

Hope this helps !

**Comment by sughosneo** [comment]
Hi @jeffreywstevens , just checking if you had a chance to look into this further ? Thanks.

**Comment by sughosneo** [comment]
I am closing this issue as of now. Please feel free to reopen it, if you have any other questions. 

Thank you.
