### ISSUE TITLE
Where is eShopOnContainers.sln ?

### ISSUE THREAD

**Issue by vinajava** [dotnet-architecture/eShopOnContainers#1503]
I follow this guideline

https://github.com/dotnet-architecture/eShopOnContainers/wiki/Explore-the-code

And download latest version from default branch "dev" but when I open the repository I could not find the file eShopOnContainers.sln for a solution containing all the projects (All client apps and services).

Can you tell me where I can find that file ? Thank you.

**Comment by vinajava** [comment]
I found it. Commit 643d09a65a on 21 Nov 2019 in branch Dev is the last commit which had that file. After that commit, that file was removed, and the whole structure of the repository changed.
Would you like to add that file back, or change your documentation to reflect that change ? Many books and articles still follow your old repository structure. Or you can have different solution.

Thank you.

**Comment by sughosneo** [comment]
Hi @vinajava, thank you for reaching out.

If you are looking for the solution file of the entire `eShop` application then you can find that in `\eShopOnContainers\src\eShopOnContainers-ServicesAndWebApps.sln`. Yes, the entire directory structure has been changed since the solution has been upgraded from ASP.NET Core version 2.2.1 to ASP.NET Core version 3.1. Present `dev` branch is updated to ASP.NET Core 3.1 and all the older releases are available under `https://github.com/dotnet-architecture/eShopOnContainers/tags`

We have updated the contents for [.NET app architecture guides](https://docs.microsoft.com/en-us/dotnet/architecture/) to accommodate ASP.NET Core 3.1 related changes. But if you still find any of the content, which is not updated or not relevant as per this reference `eShopOnContainers` application. You can open an issue in the [docs](https://github.com/dotnet/docs) repo.

Hope this helps !

**Comment by vinajava** [comment]
eShopOnContainers-ServicesAndWebApps.sln only contains services and web app projects. Only eShopOnContainers.sln contains all projects for the repository, including all mobile app projects, and their unit tests and test runners.
I will not open an issue in the https://github.com/dotnet/docs repo, as I already figured out what is the latest commit which still have that file.
Thank you for your prompt reponse.
