### ISSUE TITLE
Usage of ILogger and ILoggerFactory

### ISSUE THREAD

**Issue by nhatmvo** [dotnet-architecture/eShopOnContainers#1543]
I'm wondering why only the DomainEventHandler classes within Ordering service use the `ILoggerFactory.CreateLogger<>` for logging `(Ordering/Ordering.API/Application/DomainEventHandlers)` 
But everywhere else in the project use `ILogger<>` for logging.

Based on Microsoft [docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1): 

> ILogger<T> is equivalent to calling CreateLogger with the fully qualified type name of T.

So, is there any special reason to do this?

**Comment by sughosneo** [comment]
Hi @nhatmvo , thank you for reaching out. 

By default `ILogger` is the standard way to do the logging in ASP.NET core. This `ILogger` or `ILogger<T>` actually helps to log from the specific class and class information will be clearly visible during the logging because they will include the full class name as the context. For e.g : `Microsoft.eShopOnContainers.Services.Ordering.API.Controllers.OrdersController`

In case for any reason if you want to change the category name and override the logger with your specific name then you can do that by using the `ILoggerFactory` interface. In this scenario you specifically call the factory to create the logger instance.
For e.g : `_logger.CreateLogger<OrderCancelledDomainEvent>().LogTrace()`

Hope this helps !

**Comment by sughosneo** [comment]
Hi @nhatmvo , considering the original question has been answered, I am closing this issue as of now. 
Please feel free to reopen it if you have any further questions. 

Thank you.

**Comment by nhatmvo** [comment]
Thank you so much, it's clear now!
