### ISSUE TITLE
Is this a "True" Microservice (Discussion)

### ISSUE THREAD

**Issue by j0nimost** [dotnet-architecture/eShopOnContainers#1557]
Whilst reviewing the eShop architecture I found the solution file example; `eShopOnContainers-ServicesAndWebApps.sln` is forcing devs to include multiple services in the same project.

This is an anti-pattern. For midsize to large teams updating their respective services becomes a cumbersome task that requires them to build the whole solution. How best can we break this dependency?

**Comment by j0nimost** [comment]
Can we have partial solutions? Where before running docker-compose we have a dotnet command ran to generate a single solution for all the services. Each service will still have its own partial solution that allows it to ran and deployed separately.

**Comment by sughosneo** [comment]
Hi @j0nimost, thank you for your feedback. 

Yes, you are right. In real production scenarios, you will have a separate repository for each microservices. Each microservice will have it's own project and can completely be independent in nature, in many ways. For e.g : choice of database etc.
To keep things simple for the beginners, in the `eShopOnContainers` reference application all microservices are kept under one repository. So that it can easily be referred by a developer who has just started exploring microservices architecture and wants to develop more knowledge on this aspect. Having said that, the `eShopOnContainers` application follows the best set of practices and recommended approaches to build each microservice. For more details, you can always refer [.NET Microservices: Architecture for Containerized .NET Applications](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/)

Hope this clarifies your thought !

**Comment by j0nimost** [comment]
Hello @sughosneo , unfortunately even the examples given by [Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes) indicates the same architecture as eShopContainer. The `sln` file is the single point of failure for the architecture. It would be nice to have partial `sln` files or an easy way to refer `sln` files for each microservice in `docker-compose.yml`

**Comment by nishanil** [comment]
Hey @j0nimost, the sln file exists for an F5 debug experience in Visual Studio. This is just to make things easier for people who are getting started. However, our build pipelines (CI/CD) are independent and they do not reference the sln files. What this means is, if you change the code within their projects, only those are built and pushed to Docker Hub. There are no dll references and services do not depend on each other. All services communicate with their endpoints or asynchronously using messaging. 

If you wish to open the project separately, open it using the .csproj file inside the service directory. If you wish to run only few services, you can do that by modifying docker-compose file and enabling those services that you want it to run.

**Comment by j0nimost** [comment]
Hello @nishanil , this is a very nice explanation you've given. So the `sln` is just dependent on Visual Studio or Vscode, to build and run. I think this should be made clear in the docs all across. Thanks!
