### ISSUE TITLE
HttpClient should be reused instead of transient

### ISSUE THREAD

**Issue by FDUdannychen** [dotnet-architecture/eShopOnContainers#166]
In dev branch I saw two implementations of `IHttpClient`: `StandardHttpClient` and `ResilientHttpClient`, they are registered to be transient. However according to [this article](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/), the socket port is still on a `TIME_WAIT` state even the client is disposed. It's recommended to reuse the `HttpClient`. And be aware of thread-safety issues e.g. setting `HttpClient.DefaultRequestHeaders` `HttpClient.BaseAddress` concurrently...

**Comment by CESARDELATORRE** [comment]
@FDUdannychen - It would be good to continue the discussion about this topic in here.
The point is that we're using a specific 'header bearer' in many authenticated Http calls when accessing microservices like Basket, Order, etc. When sharing the same HttpClient object as as singleton, if using our current approach with using "DefaultRequestHeaders", it would be messed up because of those headers being shared across different threads and requests.
For instance, see the following code we actually have:
```
        public async Task<Basket> GetBasket(ApplicationUser user)
        {
            var context = _httpContextAccesor.HttpContext;
            var token = await context.Authentication.GetTokenAsync("access_token");

            _apiClient.Inst.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

            var basketUrl = $"{_remoteServiceBaseUrl}/{user.Id}";
            var dataString = await _apiClient.GetStringAsync(basketUrl);

            var response = JsonConvert.DeserializeObject<Basket>(dataString) ?? 
                new Basket()
                {
                    BuyerId = user.Id
                };
            return response;
        }

        public async Task<Basket> GetBasket(ApplicationUser user)
        {
            var context = _httpContextAccesor.HttpContext;
            var token = await context.Authentication.GetTokenAsync("access_token");

            _apiClient.Inst.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

            var basketUrl = $"{_remoteServiceBaseUrl}/{user.Id}";
            var dataString = await _apiClient.GetStringAsync(basketUrl);

            var response = JsonConvert.DeserializeObject<Basket>(dataString) ?? 
                new Basket()
                {
                    BuyerId = user.Id
                };
            return response;
        }
```
With our current approach for the authentication headers, changes to the default headers made on one thread would impact requests sent on other threads.

After researching for a while, a potential solution would be NOT to use "DefaultRequestHeaders".
At the end of the day, the simpler HttpClient methods are just wrappers around the single method SendAsync which would allow specific/different auth headers per request, like here: 

`public Task<HttpResponseMessage> SendAsync(HttpRequestMessage request)`

We could implement GET and POST methods through an extension method that would allow to manipulate the request header and anything within the **HttpRequestMessage** before it is sent through **SendAsync(HttpRequestMessage request)**.

```
public static Task<HttpResponseMessage> GetAsync
    (this HttpClient httpClient, string uri, Action<HttpRequestMessage> preAction)
{
    var httpRequestMessage = new HttpRequestMessage(HttpMethod.Get, uri);
    preAction(httpRequestMessage);
    return httpClient.SendAsync(httpRequestMessage);
}

public static Task<HttpResponseMessage> PostAsJsonAsync<T>
    (this HttpClient httpClient, string uri, T value, Action<HttpRequestMessage> preAction)
{
    var httpRequestMessage = new HttpRequestMessage(HttpMethod.Post, uri)
    {
        Content = new ObjectContent<T>
            (value, new JsonMediaTypeFormatter(), (MediaTypeHeaderValue)null)
    };
    preAction(httpRequestMessage);

    return httpClient.SendAsync(httpRequestMessage);
}
```

Used like:
```
var response = await httpClient.GetAsync("token",
    x => x.Headers.Authorization = new AuthenticationHeaderValue("basic", clientSecret));
```

We could implement that approach precisely in our StandardHttpClient and ResilientHttpClient application blocks.

A few links about it:
https://msdn.microsoft.com/en-us/library/hh159066(v=vs.118).aspx
http://chimera.labs.oreilly.com/books/1234000001708/ch14.html#_cancelling_the_request
https://iamthecoder.azurewebsites.net/index.php/2016/03/15/httpclient-sendasync-method-usage-for-post-request/
http://stackoverflow.com/questions/37928543/httpclient-single-instance-with-different-authentication-headers

Thoughts?
Cesar.

**Comment by FDUdannychen** [comment]
Is there any other `preAction` scenarios besides setting authentication header values? IMO an `Action<HttpRequestMessage> preAction` in the method signature is too broad from the caller's perspective.

**Comment by CESARDELATORRE** [comment]
What do you think about this implementation managing the HttpRequestMessage request and setting our  ResilientHttpClient as singleton?

https://github.com/dotnet-architecture/eShopOnContainers/blob/**httpclientreview**/src/Web/WebMVC/Startup.cs

https://github.com/dotnet-architecture/eShopOnContainers/blob/httpclientreview/src/BuildingBlocks/Resilience/Resilience.Http/ResilientHttpClient.cs

We're allowing the authentication as:
`public Task<string> GetStringAsync(string uri, string authorizationToken = null, string authorizationMethod = "Bearer")`

**Comment by FDUdannychen** [comment]
Looks perfect to me.

**Comment by eiximenis** [comment]
Ok! I close the issue then.
@FDUdannychen  feel free to reopen if needed!

**Comment by Eneuman** [comment]
@CESARDELATORRE Im looking at the latest code and I can see that the HttpClient is still created and not injected as singleton. Since the issue was closed, I thought this was fixed?

https://github.com/dotnet-architecture/eShopOnContainers/blob/08a5eeea71e98e5fbb55dfb645294dd245da4aa3/src/BuildingBlocks/Resilience/Resilience.Http/StandardHttpClient.cs#L21

**Comment by CESARDELATORRE** [comment]
@Eneuman - It is singleton.  What we're registering as singleton are our own classes (ResilientHttpClient and StandardHttpClient), not HttpClient.

See Startup.cs from WebMVC:
https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Web/WebMVC/Startup.cs

```
services.AddSingleton<IHttpClient, ResilientHttpClient>(sp => sp.GetService<IResilientHttpClientFactory>().CreateResilientHttpClient());
//...           
                
services.AddSingleton<IHttpClient, StandardHttpClient>();
```

**Comment by Eneuman** [comment]
Aaa, Nice :)

________________________________
