### ISSUE TITLE
Remove foreign key navigation properties from Aggregate-Root (No direct references across aggregate boundaries)

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#18]
The Buyer is an Aggregate-Root. do we really need to show it as an object within the Order Aggregate-Root? - Can we just use the BuyerId here?

This issue is similar to the Payment (PaymentMethod) that also appears as an object within the Order.

    public class Order
        : Entity, IAggregateRoot
    {
        public int BuyerId { get; private set; }
        public Buyer Buyer { get; private set; }

If we maintain it as a reference through the EF graph..., how can we make clearer in the model that it is NOT a child entity but just a reference?

Review, confirm/fix.

**Comment by iancooper** [comment]
I'd support this, we dropped direct references across aggregate boundaries because they were too tempting to navigate, thus expanding the transactional boundary to include elements from a second aggregate. As this is another aggregate, you must not pull it into the same transation and an easy way to help remind folks of that is to force them to load directly.

BTW, we tend to have a 'read-only' interface for any entity that we might want to pull into read values from, but you should not update because you will violate the transactional boundary. We then use a model that allows you to get this aggregate from a repository without taking an intent lock (see my comment on aggregates) and thus access the entity in a read-only fashion.

This might be too complicated for your example though
