### ISSUE TITLE
Not working on Mac "out of the box"

### ISSUE THREAD

**Issue by Murf** [dotnet-architecture/eShopOnContainers#201]
Container "eshop/catalog.ap" exits after startup, error as follows. All other containers seem to be up and working correctly

Unhandled Exception: System.AggregateException: One or more errors occurred. (A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)) ---> System.Data.SqlClient.SqlException: A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer

**Comment by CESARDELATORRE** [comment]
@Murf Looks related to the SQL container but I cannot initially tell without experiencing the error. A few things to check:
- 1. Did you set Docker with the required memory (4GB for Docker) and procs (2 or 3) as explained in the setup procedure here: [https://github.com/dotnet-architecture/eShopOnContainers/wiki/04.-Setting-eShopOnContainer-solution-up-in-a-Mac,-VS-Code-and-CLI-environment--(dotnet-CLI,-Docker-CLI-and-VS-Code)](https://github.com/dotnet-architecture/eShopOnContainers/wiki/04.-Setting-eShopOnContainer-solution-up-in-a-Mac,-VS-Code-and-CLI-environment--(dotnet-CLI,-Docker-CLI-and-VS-Code))
Please, confirm if you followed the mentioned setup procedure above in the first place.

- 2. I never had that error in my Mac machine, nor in my Windows machine. In both of them I have 16GB or ram. But in a machine with 8GB of ram I remember I had similar errors because sometimes it could not assign enough memory to the SQL container. How much memory do you have in your Mac?.

**Comment by Murf** [comment]
Yes I set docker to use 5GB it was not enough, I tried 8GB in docker for mac and it works now thanks.
Might be a good idea to update the guide.

**Comment by CESARDELATORRE** [comment]
4gb set to Docker is usually enough unless you have many more processes running in the Mac. I'll add a note about it. Thanks for confirming! :)

**Comment by CESARDELATORRE** [comment]
Closing it.
