### ISSUE TITLE
any efforts or impediments putting it on docker hub?

### ISSUE THREAD

**Issue by rs38** [dotnet-architecture/eShopOnContainers#205]
did I miss it? what would be the easiest way, simply to let it run as a container demo?

**Comment by CESARDELATORRE** [comment]
Not any impediment. :)
In fact, we already have the images in Docker Hub.
Also in Azure Container Registry which we use when deploying to ACS-Kubernetes.
We're just focusing on code because our goal is about development, .NET Core, Visual Studio 2017, etc., but it is a good idea to write how to make it run just by pulling down the containers from Docker Hub. I'll write a post on the Wiki, when possible, on how to do that demo.

**Comment by CESARDELATORRE** [comment]
Closing this since there's no any impediment for this. In fact, we already have the images in Docker Hub. Here:
https://hub.docker.com/u/eshop/dashboard/

But this application has not been created because of a demo on Docker but focus on the code and Visual Studio. That's why we focus on the F5 experience in VS for developers, focus on the code, instead of simply running a demo in Docker (That can also be done, of course).

**Comment by rs38** [comment]
thanks for the hints!
