### ISSUE TITLE
What is the EventBus

### ISSUE THREAD

**Issue by JamesYing** [dotnet-architecture/eShopOnContainers#207]
Hi sir,I don't konw the eventbus's feature. Now, it's only logs the data change in the eShop. 

Whether it like to android's eventbus?

**Comment by prisar** [comment]
what is the difference between eventbus and command bus

**Comment by alhardy** [comment]
@prisar http://cqrs.nu/Faq/commands-and-events

**Comment by CESARDELATORRE** [comment]
Basically:
- **Event Bus** for Pub/Sub, since by definition an event could be processed by many subscribers. 1:Many
- **Command Bus for commands**. A command should be processed a single time by a single receiver. 1:1
Here you have our explanations related to eShopOnContainers and the [Guidance/eBook](https://aka.ms/microservicesebook) where it is explained.
**Event Bus and integration-events:**
https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/architect-microservice-container-applications/asynchronous-message-based-communication

https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/multi-container-microservice-net-applications/integration-event-based-microservice-communications

**Commands and CommandHandlers:**
https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/microservice-application-layer-implementation-web-api#implementing-the-command-and-command-handler-patterns

**Comment by mvelosop** [comment]
@CESARDELATORRE, would it be right to add that usually (always?) a command issuer expects a confirmation on whether it succeeded or not, i.e. the command's result, but events don't have any response back? would that a fundamental difference?

**Comment by prisar** [comment]
thank you
