### ISSUE TITLE
The eShopOnContainers.sln file is missing entry for DataProtection project

### ISSUE THREAD

**Issue by shaijujanardhanan** [dotnet-architecture/eShopOnContainers#229]
Unable to resolve '..\eShopOnContainers-master\src\BuildingBlocks\DataProtection\DataProtection\DataProtection.csproj' for '.NETCoreApp,Version=v1.1'.

**Comment by tmagalhaes** [comment]
You have to add the DataProtection Project to the solution and then build it again. 
I've had to do the same to the Markting.Api projetc and Location.Api Project.
I'm not sure if this is a known bug, but it's importante to be fixed. Otherwise the new developers that push this project will have the same troubles to make it build.

**Comment by CESARDELATORRE** [comment]
We'll fix this. However, we recommend to use the eShopOnContainers-ServicesAndWebApps.sln solution which focuses only on the "server side" projects.
Or the eShopOnContainers-MobileApps.sln for the Xamarin apps.
Having both, Xamarin client apps and server-side projects within the same solution should only be used for a demo if you want to show ALL the projects. But when working with it, it is better to have them separated because of the Hyper-V incompatibility with the Google Android Emulator (and Docker for Windows using Hyper-V).

**Comment by tmagalhaes** [comment]
Thanks!

**Comment by infofromca** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve 'E:\eShopOnContainers-zg2\eShopOnContainers\src\BuildingBlocks\EventBus\EventBusServiceBus\EventBusServiceBus.csproj' for '.NETCoreApp,Version=v1.1'.	

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve 'E:\eShopOnContainers-zg\eShopOnContainers\src\Services\Location\Locations.API\Locations.API.csproj' for '.NETCoreApp,Version=v1.1'.		

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve 'E:\eShopOnContainers-zg\eShopOnContainers\src\Services\Marketing\Marketing.API\Marketing.API.csproj' for '.NETCoreApp,Version=v1.1'.				

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve 'E:\eShopOnContainers-zg\eShopOnContainers\src\BuildingBlocks\DataProtection\DataProtection\DataProtection.csproj' for '.NETCoreApp,Version=v1.1'.

**Comment by CESARDELATORRE** [comment]
This is fiexed in the DEV branch. Closing.
