### ISSUE TITLE
gateway api

### ISSUE THREAD

**Issue by dquijada** [dotnet-architecture/eShopOnContainers#239]
I was wondering if you are planning to develop a version of this project which contains gateway apis (as the book recommends). I'm trying to build a platform based on microservices architecture, but I'm having a hard time authorizing apis. 

Should I authorize at microservice level only, or should I authorize at gateway api level, or both?

How am I supposed to authorized based on roles? do roles come in the access token? or so I have to go to the identity service api again to get the roles an then authorize?

**Comment by CESARDELATORRE** [comment]
If you add a Gateway API, initially, you wouldn't need to authorize at Microservices level as you could protect the internal Microservices by NOT publishing them out of the Docker Host, just by removing that line in the Docker-compose files, so the Microservices could only be accessed by other Containers within the Docker host thru the "internal port" of each Container.
We're not planning to add a API Gateway approach because of the following reasons:
1. This app is probably too small for a API Gateway and would be overigineered, needing too many steps when coding/updating features.
2. The approach would be different depending if you use Azure API Management product just for securing/authorizing/routing or a custom API Gateway (or several custom API Gateways) also for aggregating calls. But the way of doing it should be straightforward depending on the selected approach. 

So, no, we're not initially planning about adding a API Gateway approach because of the above reasons. That's our initial thinking, thought. We could change our mind depending on the volume of feedback similar to yours which is probably the first one requesting it.

**Comment by CESARDELATORRE** [comment]
About authorization and roles, it depends on the used system. Since we're currently using IdentityServer4, please, look at examples and documentation from IdentityServer4 about using roles. Our current authorization system at eShopOnContainers is pretty basic.

**Comment by dquijada** [comment]
understood! thanks!
