### ISSUE TITLE
npm install --skip

### ISSUE THREAD

**Issue by infofromca** [dotnet-architecture/eShopOnContainers#256]
![eshop-npm-install](https://user-images.githubusercontent.com/297675/28974869-eb3c9e40-7905-11e7-8755-213e5d1ff65a.png)

**Comment by CESARDELATORRE** [comment]
Not sure what's the issue here but I'm testing in a clean machine, clean "git pull of the dev branch repo",  with the latest NPM version, regular "npm install" and then "npm run build:prod" and the SPA application is working properly. 
I didn't need to run "npm install enhanced-resolve@3.3.0"...
See:
![image](https://user-images.githubusercontent.com/1712635/28983840-612acabe-7910-11e7-8d69-58ad6b7c06db.png)
![image](https://user-images.githubusercontent.com/1712635/28983868-72b0f6be-7910-11e7-9582-b2970752cfa7.png)
