### ISSUE TITLE
shopping cart:  when quantity 0 produce exception

### ISSUE THREAD

**Issue by infofromca** [dotnet-architecture/eShopOnContainers#259]
in the cart, when I change the quantity to 0 manually,
 then checkout, exception in eventbus --RabbitMQ

**Comment by CESARDELATORRE** [comment]
I'll mark this as a bug to be fixed. Exceptions should be minimized, even for a sample app.

However, even when you a re are right on that "application bug", the purpose of this sample application is just to provide a sample application showing how to use microservices and Docker containers plus showing multiple clients (MVC, SPA and Xamarin.Forms). For sure, from a "business eCommerce" point of view, this sample app might have dozens of areas that could be improved or could even be wrong from an "eCommerce business" perspective or we could have many other "business logic application" bugs.

So, certainly, we're NOT trying to create an "eCommerce reference" application. We just chose the "eShop" domain because it is a well know domain by most developers/people. 
There are many functional/business areas that might not be polished from a functionality point of view.

In this case, we are not testing/considering all the possibilities or "side cases" like this manual change to 0, for a basket's item quantity. This could be controlled/fixed from the UI, possibly.

Thanks for your feedback and for taking the time to think about it, of course. :)

**Comment by infofromca** [comment]
to be clear for others, that happened when there were many items in the cart, even the quantity is not 0

**Comment by CESARDELATORRE** [comment]
Still not working properly in the SPA app.
When adding an article with CERO:
![image](https://user-images.githubusercontent.com/1712635/29594414-9b67055e-8765-11e7-8a8b-e0cadbeb4d54.png)
Then when submitting the ORDER, it appears as 1 article.
The SPA app simply has to NOT allow any value equal to CERO before submitting.

**Comment by CESARDELATORRE** [comment]
This is fixed. Closing.
