### ISSUE TITLE
shoping cart: should have delete function

### ISSUE THREAD

**Issue by infofromca** [dotnet-architecture/eShopOnContainers#260]
each row of the item, user can delete (remove) the item

**Comment by CESARDELATORRE** [comment]
You are right on that, but the purpose of this sample application is just to provide a sample application showing how to use microservices and Docker containers plus showing multiple clients (MVC, SPA and Xamarin.Forms). For sure, from a "business eCommerce" point of view, this sample app might have dozens of areas that could be improved or could even be wrong from an "eCommerce business" perspective.

So, certainly, we're NOT trying to create an "eCommerce reference" application. We just chose the "eShop" domain because it is a well know domain by most developers/people. 
There are many functional/business areas that we deliberately chose not do implement. This is one of those features. 
In this case, for simplicity's sake and smaller investment on UI and functional implementation, we chose NOT to implement the basket line delete functionality. If you want to clean the basket, just submit the order.

I'm closing this issue because of the reasons above. ok?

However, if anyone would like to improve the "eCommerce functionality" of the apps, we're open to accept PRs (Pull Requests) from the community, as long as the PRs don't break the rest of the scenarios and client apps. So, if you do, please test all the client apps (including the Xamarin.Forms app consuming the microservices) before submitting a PR.

Thanks for your feedback and for taking the time to think about it, of course. :)

**Comment by tthiatma** [comment]
Hello,

I am trying to improve the eCommerce functionality by adding the delete button.  but I have a question.

I tried below:
- in BasketViewModel add DeleteCommand that accept string as argument :
        public ICommand DeleteCommand => new Command<string>(async (string args) => await DeleteItemAsync(args));

- in BasketItemTemplate, add delete Button.
<Button  Text="Delete" 
   Command="How to call the command I created in view model while I'm in template"
   CommandParameter="{Binding ProductName}" </Button>

I am not sure how to call the command that I just added from the delete button. I will create a PR once I can solve this.

Regards,
Tonny
