### ISSUE TITLE
Shooping cart: anonymous user can not ADD To Cart

### ISSUE THREAD

**Issue by infofromca** [dotnet-architecture/eShopOnContainers#261]
issue-- anonymous user can not see cart, and can not add to cart
resolution--can do those

**Comment by CESARDELATORRE** [comment]
You are right on that, but the purpose of this sample application is just to provide a sample application showing how to use microservices and Docker containers plus showing multiple clients (MVC, SPA and Xamarin.Forms). For sure, from a "business eCommerce" point of view, this sample app might have dozens of areas that could be improved or could even be wrong from a business perspective.

So, certainly, we're NOT trying to create an "eCommerce reference" application. We just chose the "eShop" domain because it is a well know domain by most developers/people. 
There are many functional/business areas that we deliberately chose not do implement. This is one of those features. 
In this case, for simplicity's sake and smaller investment on UI and functional implementation, we chose that the apps requires the user to login before getting into the "private areas".

I'm closing this issue because of the reasons above. ok?

However, if anyone would like to improve the "eCommerce functionality" of the apps, we're open to accept PRs from the community, as long as they don't break the rest of the scenarios and client apps. So, if you do, please test all the client apps (including the Xamarin.Forms app consuming the microservices) before submitting a PR.

Thanks for your feedback and for taking the time to think about it, of course. :)
