### ISSUE TITLE
shopping cart number

### ISSUE THREAD

**Issue by infofromca** [dotnet-architecture/eShopOnContainers#262]
after click "add to cart"  for the same item 2 times, should the cart on right upper side should 2 or 1?

**Comment by CESARDELATORRE** [comment]
You are right on that, but the purpose of this sample application is just to provide a sample application showing how to use microservices and Docker containers plus showing multiple clients (MVC, SPA and Xamarin.Forms). For sure, from a "business eCommerce" point of view, this sample app might have dozens of areas that could be improved or could even be wrong from an "eCommerce business" perspective.

So, certainly, we're NOT trying to create an "eCommerce reference" application. We just chose the "eShop" domain because it is a well know domain by most developers/people. 
There are many functional/business areas that we deliberately chose not do implement. This is one of those features. 
In this case, for simplicity's sake and smaller investment on UI and functional implementation, we chose to simply add any item as a Basket line, even it if it the same item, instead of accumulating.

I'm closing this issue because of the reasons above. ok?

However, if anyone would like to improve the "eCommerce functionality" of the apps, we're open to accept PRs from the community, as long as they don't break the rest of the scenarios and client apps. So, if you do, please test all the client apps (including the Xamarin.Forms app consuming the microservices) before submitting a PR.

Thanks for your feedback and for taking the time to think about it, of course. :)
