### ISSUE TITLE
place order: bug on ---total 

### ISSUE THREAD

**Issue by infofromca** [dotnet-architecture/eShopOnContainers#263]
click "add to cart" 2 times on the same item, go to http://localhost:5104/order page , it show correct total which is the sum of the two items.
after click "PLACE ORDER" , total become different which just show the  price of  one item.

**Comment by CESARDELATORRE** [comment]
OK, this is a BUG to be fixed, so I'm marking it as a bug and it'll be fixed. 
Thanks! :)

In any case, take into account the purpose of this sample application is just to provide a sample application showing how to use microservices and Docker containers plus showing multiple clients (MVC, SPA and Xamarin.Forms). 
So, certainly, we're NOT trying to create an "eCommerce reference" application, so, from a business/functionality point of view, ceartainly, there are many business features that could be improved and we chose to have the simplest/easiest implementation because of the reasons above.
Other scenarios reach to a further business complexity because they are good scenarios to show certain technical/patterns implementations, like the Ordering microservice, Order process, integration events through messaging, etc.

But certainly, in this case, this is a bug to be fixed. Thanks! :)

**Comment by CESARDELATORRE** [comment]
This is fixed. Closing it.
