### ISSUE TITLE
build ok, but can not run the site 

### ISSUE THREAD

**Issue by infofromca** [dotnet-architecture/eShopOnContainers#264]
the same code, yesterday, every thing is ok.
but now build ok, but can not run the site.
it seems the first time--ok.
second or sometime later --this issue. (alreay close sln, reopen it ,build, run docker)
I think we should deal with this famous issue ESHOP_AZURE_STORAGE_CATALOG_NAME variable is not set in code according to diff.  env. 
![second-time-build](https://user-images.githubusercontent.com/297675/29002466-19723f24-7a71-11e7-9fae-63962e220a77.png)

**Comment by CESARDELATORRE** [comment]
The ESHOP_AZURE_XXXX variables are not needed unless you are deploying databases/resources in Azure.
I cloned a clean eShopOnContainers repo and it is running properly in my dev machine.
It looks like an error due to the Docker in that machine.
Are you able to deploy any other Docker "Hello World" project in your machine?

**Comment by CESARDELATORRE** [comment]
Btw, I made a small [change/commit](https://github.com/dotnet-architecture/eShopOnContainers/commit/f885f6e2d77d91c31a747e5e420526c186653aee) so you won't get the warnings about having the ESHOP_AZURE_XXXX variables empty. But those warnings are not related to this issue that is preventing you from running the app properly. This issue looks like a Docker environment issue.
