### ISSUE TITLE
[Question] How to synchronize after subscriber outage?

### ISSUE THREAD

**Issue by Dresel** [dotnet-architecture/eShopOnContainers#267]
Thanks for this great repository and all the work you have put in. I'm currently digging through the source / ebook and trying to understand the bits and pieces.

I'm wondering which pattern / solution you would propose if a subscriber misses an integration event because it had a temporary outage.

For example the `Basket` service listens to the `ProductPriceChanged` event to update the product price if it was changed in the `Catalog` service. The *Resiliently publishing to the event bus* section in the ebook describes how to handle possible errors between the publisher and the event bus. But what about the subscriber? If you stop the `Basket` service, change the price and start it again it will miss the event.

So what would you propose? I would be thankful for any hints, references, or similar.

**Comment by CESARDELATORRE** [comment]
This scenario is easy. It is usually handled by the messaging infrastructure. No worries. :)
Basically, you use one subscription/queue per subscriber. So the message will be there waiting for his subscriber and it'll be processed when the client subscriber is up and running.
When using Azure Service Bus this feature you ask about is pretty common by using one subscription (queue based on topics) per subscriber. 
In Azure Service Bus, in a topic\subscription pattern, the messages in the topic are copied to multiple subscriptions. So each subscription is independent of the other subscription. It's like a different copy of the queue.
Now, your client applications that are receiving messages from a subscription are the subscribers. Each client (subscriber) is meant to connect to a single subscription/queue. In this case, subscribers do not compete for messages, and each subscriber can process the same message as others did.
It is only a matter of how long a message will be maintained in the queue/subscription waiting for his specific subscriber.
See here: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-how-to-use-topics-subscriptions

So, when a subscriber processes a message it is only removed for the subscriber that called it, in his specific subscription/queue. See also https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-how-to-use-topics-subscriptions#how-to-receive-messages-from-a-subscription

**Comment by i02coroj** [comment]
Hello.
I know this question is closed but I haven't found a better place to ask my doubt:

I got the same question above, and I undertand the answer from @CESARDELATORRE. But that's it not working for me, not sure if I'm doing something wrong.

The thing is if my client subscriber is up and running, it gets all the events published in the service bus. Even if it is busy (for instance I stop it with a breakpoint), when he gets free he processes the event.

But if my client subscriber is down, and if I publish an event to the Service Bus, then when I start my subscriber again it doesn't process any event.

Is there any logic that I should add for that? Shouldn't it be done automatically when I create my new SubscriptionClient?

Thanks in advance!

**Comment by Dresel** [comment]
I can't remember all the details, but to get this working you have to change some queue properties, for example use durable queues. I would suggest reading https://www.rabbitmq.com/tutorials/tutorial-one-dotnet.html and just play with the samples.

**Comment by i02coroj** [comment]
Ok.
Many thanks.
Actually I'm using the Azure Service Bus instead of RabbitMQ.
So far I haven't seen any configuration for these durable queues in the Azure portal.
Have you ever faced that issue with Service Bus?
Thanks!

**Comment by i02coroj** [comment]
Just update to say that unfortunatelly I haven't seen anyway to automatically get the messages after a subscriber outage using Azure Service Bus. So far, I have only made it work when the subscriber is up and running when the event is published.

Any help would be appreciated.

**Comment by CESARDELATORRE** [comment]
@i02coroj - If I understood you well, this is how I see it.
Basically: In Azure Service Bus, by default, messages are deleted from the subscription as they are read; however, you can read (peek) and lock the message without deleting it from the subscription by setting the optional parameter **isPeekLock** to true.

The following would happen PER SUBSCRIPTION, so per each microservice/app subscribed:
The default behavior of reading and deleting the message as part of the receive operation is the simplest model, and works best for scenarios in which an application can tolerate not processing a message in the event of a failure. To understand this, consider a scenario in which the consumer issues the receive request and then crashes before processing it. Because Service Bus will have marked the message as being consumed, then when the application restarts and begins consuming messages again, it will have missed the message that was consumed prior to the crash. (THIS IS YOUR ISSUE, I BELIEVE).

If the isPeekLock parameter is set to true, the receive becomes a two stage operation, which makes it possible to support applications that cannot tolerate missing messages. When Service Bus receives a request, it finds the next message to be consumed, locks it to prevent other consumers receiving it, and then returns it to the application. After the application finishes processing the message (or stores it reliably for future processing), it completes the second stage of the receive process by calling deleteMessage method and providing the message to be deleted as a parameter. The deleteMessage method will mark the message as being consumed and remove it from the subscription.
This should happen for each subscription.

You can see further related info here:
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-nodejs-how-to-use-topics-subscriptions 

You could either evolve our Event Bus implementation for Azure Service Bus, or you can use (replace it) with a service bus like NServiceBus or MassTranssit that also support those scenarios on top of Azure Service Bus.
