### ISSUE TITLE
Kubernetes issue

### ISSUE THREAD

**Issue by chriscooper87** [dotnet-architecture/eShopOnContainers#269]
Hello when running the deploy.ps1 in the k8s folder I receive the following error:

ERROR: Service 'webstatus' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder921516507/obj/Docker/publish: no such file or directory

Any idea what could be causing this?

Thanks

**Comment by eiximenis** [comment]
Hi @chriscooper87 
If you are receiving this message, the most probably cause is that `WebStatus` project failed to build and the folder `src/Web/WebStatus/obj/Docker/publish` is empty or do not exist. This is the folder from were the images are created.

**Keep in mind that if you DON'T pass the parameter `-buildBits $true` the script won't build the code**. So if you didn't built by yourself before, you'll find these errors.  Take a look at https://github.com/dotnet-architecture/eShopOnContainers/blob/master/k8s/README.k8s.md for more info about the parameters that `deploy.ps1` accepts.

If this is the only image that fails, you can try to publish the project yourself:
```
cd src\Web\WebStatus
dotnet restore
dotnet publish -o obj/Docker/publish
```

If you see any error and need help feel free to copy-paste here :)

Then you can try to re-run the `deploy.ps1` (with `-buildBits $false` which is the default value because there is no need to rebuid the projects again).

**Comment by chriscooper87** [comment]
Thanks @eiximenis

There was indeed an issue with my build. Thanks a lot for your help.
