### ISSUE TITLE
Kubernetes ACS deployment - 502 bad gateway from nginx

### ISSUE THREAD

**Issue by chriscooper87** [dotnet-architecture/eShopOnContainers#271]
Hi guys,

I've managed to deploy this to azure using kubernetes. However when I try access the application i get a 502 bad gateway error from nginx.

Looking at the kuberenetes portal I can see this error for all deployments:

Failed to apply default image tag "XXXXX.azurecr.io/eshop/webspa:": couldn't parse image reference "XXXXX.azurecr.io/eshop/webspa:": invalid reference format
Error syncing pod, skipping: failed to "StartContainer" for "webspa" with InvalidImageName: "Failed to apply default image tag "XXXXX.azurecr.io/eshop/webspa:": couldn't parse image reference "XXXXX.azurecr.io/eshop/webspa:": invalid reference format"

Any ideas where I've gone wrong?

Thanks

**Comment by tanermelikoglu** [comment]
Do you have a solution for the problem above @chriscooper87 ?

**Comment by CESARDELATORRE** [comment]
Hi! - @tanermelikoglu @chriscooper87 - So, I'm not sure what can be the issue but looks like your Docker image for the SPA (Single Page Application) might not be created correctly or the specified name in the K8s doesn't match..
Question: Is the SPA app working for you in just a local Docker host? (like in a local Linux VM from 'Docker for Windows')?
If it is working locally, it looks like the image was not deployed correctly to your Azure Container Registry in Azure or the full name of the image doesn't match in the deployment files.

In order to isolate the issue:
Since the SPA web app is optional, because you can start trying the MVC web app consuming the microservices, what I'd do first in your case is to remove all the references/YAML code related to the SPA app in the Kubernetes deployment .yml files.
Then, try to re-deploy the app again and initially test it only with the MVC app and the microservices.
Once that is working, you can go ahead and try to isolate what's going on with the SPA app.
first

**Comment by eiximenis** [comment]
Hi @chriscooper87 
How did you invoked the script to deploy to Kubernetes? It seems the tag used for the images is invalid.
