### ISSUE TITLE
[QUESTION] Run eShopOnContainers on  centos7 docker

### ISSUE THREAD

**Issue by WithLin0510** [dotnet-architecture/eShopOnContainers#310]
hi, i want to run eShopOnContainers on centos7, i have git clone this project. and then i start ./run.sh in cli-linux,but i can not run the docker container. because  i install docker on centos7. so what can i do? i do not want to  install  docker on windows.i want to get some suggestion.that i want to run eShopOnContainers ,which is on centos7.

**Comment by eiximenis** [comment]
Hi!
Do not use cli-linux/run.sh (this file is intended to launch from single docker machine using the images in the Docker Hub. I will review this file because not sure if it is properly updated!)

You need first to build the project using cli-linux/build-bits.sh (which requires netcore installed). If you don't want to install netcore, you can build the project using a build container:

```
docker-compose -f docker-compose.ci.build.yml up
```

This will pull a build container and build all the required projects. After running this command you should have every project built in a project's `obj/Docker/publish` subfolder

Once project is built you can run it using:

```
docker-compose -f docker-compose.yml -f docker-compose.override.yml up
```

This will launch all containers. Once containers started you can go to localhost:5000 to view the web

**Comment by CESARDELATORRE** [comment]
Closing this issue.
