### ISSUE TITLE
[Feedback] Support for .NET Core 2.0 Razor Pages (replacement for MVC)

### ISSUE THREAD

**Issue by ghd258** [dotnet-architecture/eShopOnContainers#315]
Support for .NET Core 2.0 Razor Pages (replacement for MVC)

**Comment by CESARDELATORRE** [comment]
The focus for this project is currently most of all about the microservices, not so much about the client apps. So, this is a good idea but for now we cannot prioritize it as we have many other priorities in the backlog.
However, if you want to see an "eShop sample" with .NET Core 2.0 Razor Pages, we'll be building it for the plain-vanilla eShopOnWeb (no Docker Containers, here): https://github.com/dotnet-architecture/eShopOnWeb/tree/netcore2.0
Still not started, though, but it'll be done in a few weeks.

**Comment by SychevIgor** [comment]
I'm not part of dev team for this project, but from my name I can say - in a dev community we have some concerns against Razor Pages and investing time in it.
Primary argument is- that razor pages are not giving us anything extra over normal mvc controllers in one hand, but limiting development in another hand.
100% sure, that asp.net core product team have some good reason to invest their time in razor pages, but some part of the community think it as a one more reincarnation of web forms...

Once again, it's my personal opinion and opinion of some people I know from community. It's not the official position of Microsoft or any product group.

**Comment by ardalis** [comment]
@SychevIgor have you read this and associated MSDN article? https://ardalis.com/aspnet-core-razor-pages-worth-checking-out

**Comment by SychevIgor** [comment]
@ardalis only after you give me this link. It didn't change my opinion, but it give me some time think about my opinion and type it here.

In a one sentence my position is "One ring/framework to rule them all". 
I'm not sure that I will tell you something you never heard before about it, but let's try:

- Instead of MVC only, we have one more way to create UI in asp.net core. Learning curve is higher. 
- PG will spend time on support instead of new development (where is signalr for .net core?).
- People who migrating from classic asp.net to asp.net core will be frustrated with Web Pages. (MVC5 can be imported more or less as is. Web Forms- Yes, PG did something similar but different and name it Razor Pages.).
- as a benefit from yet another approach we have - file structure base routing and model is closer to a view. It's not sound like a enough to adopt one more feature.

**Comment by CESARDELATORRE** [comment]
Closing this one. I'm setting Razor pages as a possible update in eShopOnContainers, with not very high priority, though, for now, as that is focusing more on a client application.
