### ISSUE TITLE
[QUESTION] Does it work on Docker Toolbox?

### ISSUE THREAD

**Issue by avrensburg** [dotnet-architecture/eShopOnContainers#327]
Hiya - anybody got eShopOnContainers-ServicesAndWebApps working with Docker ToolBox?

**Comment by CESARDELATORRE** [comment]
@avrensburg The application has been tested in regular Docker Hosts Linux VMs in Azure.
But we haven't tested it, as a development environment, with Docker Toolbox since the official dev environment from Docker and Visual Studio is based on "Docker for Windows" (DockerCE) or "Docker for Mac".
We are not planning on testing on Docker Toolbox since that environment is being deprecated by Docker.
In any case, I would also like to know if anyone has tried it out on Docker Toolbox. :)

**Comment by SychevIgor** [comment]
@avrensburg it's working on windows 10 with hyper-v. from Docker Tool - kitematic 100% working with it.

**Comment by CESARDELATORRE** [comment]
Closing. Thanks! :)
