### ISSUE TITLE
[Question] Do we have a reason to use dynamics type in OrderQueries.cs file

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#366]
I just started working on https://github.com/dotnet-architecture/eShopOnContainers/issues/305 and got an interesting situation... I can't normally describe the return type for OrderController.GetOrder because type essentially dynamic.
after some research - I didn't find any reason for dynamic type here. 
May I fix the type or could you explain the idea?

@CESARDELATORRE

**Comment by CESARDELATORRE** [comment]
@SychevIgor 
The reason is that being dynamic, you can just change the SQL query (new attributes/columns, etc.) and you'll get that returned. you have like a dynamic ViewModel. No need to have static classes for those ViewModels.  So, it is more agile when developing.
So, for a service used only by the same application, it is ok and more agile.

However, for a public API, it would be better to use ViewModels or "contracts".
And even for a long term application, I find that having explicit ViewModel classes is safer and also, as you mentioned, better for Swagger or even other "unknown clients".
So, after testing that PR well, we can merge it. But, can you test it with all the client apps? Including the SPA app and the Xamarin app?

**Comment by CESARDELATORRE** [comment]
Closing this issue. We decided to accept the PR and use predefined ViewModel DTOs classes as it is better for public APIs but also for long term microservices, even if they are just used by the same application.
Also, as mentioned by SychevIgor, if you want to specify response types for swagger, you need to use explicit DTO classes as the return type. Therefore, predefined DTO classes allows you to offer a richer information from Swagger. That will benefit the API documentation and compatibility when consuming an API.
