### ISSUE TITLE
Please remove the docker crap, docker !~ microserivce architecture

### ISSUE THREAD

**Issue by HansHammel** [dotnet-architecture/eShopOnContainers#400]
Please remove the docker crap or find a better solution. Ever thought of people setting up a microservice architecture without unstable crap like docker!? I just tried to install docker. First my current VS version is reported to have broken docker tag support. Then the docker install crashed my System with a bluescreen (known issues with Samsung 960 pro Drivers). After fixing that, I had to uninstall HAXM, VirtualBox and Vagrant. No Android Emulator and broken vagrant support for my other projects. And now it still keeps crashing for unknown reasons on a fresh, high-end developer machine! Thanks MS! Tanks docker! ;-( Please start using solid technologies. This is very frustrating. Next time please focuse on one toppic. Either container or microservices. How about packing things into hyper-v or VMware images? Or better yet, go with nested virtualisation!? Sorry for the rant, but it's true. Btw. After the silverlight and WPF/Prism disaster and after 3 years of absense, I tried to come back to a MS stack. See what you have done... A nice experience.

**Comment by CESARDELATORRE** [comment]
Microservices and Docker are complementary and should be used at the same time in many cases.
There are thousands of people using Docker in development environments but you need to take into account incompatibilities before moving ahead, especially in regard to hypervisors.
IMHO, Docker/Containers can be used with no microservice architecture.
But microservices without Containers, even when it is possible, I say that any microservice platform not based on Docker will be out of the market in the medium term.
Even Service Fabric that was a microservice platform without containers is now supporting Docker.
Development environment issues can happen but that doesn't mean Docker is not strategic for most microservice-based applications. 
You can see that in all orchestrators with larger success, all of them betting on Docker containers:
- Kubernetes
- Service Fabric
- DC/OS
So, I'm sorry, but I don't agree at all with your comment.
Neither most vendors in the industry betting on Docker:
- Microsoft
- Amazon AWS
- IBM
- Google
etc.

**Comment by HansHammel** [comment]
•Rancher

And that's why canonical and oracle came up with their bare matel as a serive initative aka MaaS.
I abolutly makes no sense to host a selfhosting .net core application inside a docker Container, for every host I could just spin up some services and I am good to go scaling. This just went fine for decades e.g. ADs/DCs, DNSs, DBs and their failovers and replicas. A good old windows-Service is a Service, even an old novel network service worked well in huge installations back in the 90s. That said, I am even more depressed.

**Comment by HansHammel** [comment]
IMHO We got lost in abstraction and vm crap. Like Software defined storage. They din't manage to put it in the Firmware of a hw controler, so now they try to make it over several abstraction layers of the os and maybe some vms. OMG. Just like the fact that everyone is abusing the NIC in lack of Knowledge of IPC, pipes, etc. A program on the same physical host is communication over a REST API with it's fellows!? It seems to be better to abuse the NICs buffer as message queue than handling things more efficently.

**Comment by HansHammel** [comment]
^^ Orchestration
Copy a portable, self-hosted app to fresh deployed machine and execute it or shut it down. That's it. All Solutions I have evaluated over the years lack a consistent way of doing service and configuration discovery, centralized logging, queueing, loadbalancing, etc. The app has to Support this anyway, dcoker doesn't help here, except it is just another "thing" to !orchestrate".

**Comment by CESARDELATORRE** [comment]
What you are trying to do is what Azure Service Fabric is/was and supporting mission critical applications built on top of it for years,  like Azure Service Bus, Azure SQL DB, Skype backend, Cortana backend and many other Tier 1 apps/platforms all of them running as processes on top of Azure Service Fabric. 
We just made Service Fabric available as an orchestrators for customers like 2 years ago, but it was internally used by Azure. It originally just supported processes on Windows.
But now, it is cross-platform, Linux and Windows Server and it is supporting Docker containers!... ;)

Why?, I tell you, if Azure Service Fabric were based just on processes, it would be out of the market already pushed by container-based orchestrators like Kubernetes. And still, Kubernetes, 100% about Docker containers is growing like crazy. Kubernetes is also supported by Azure (in Azure AKS and ACS), btw.

The beauty of Docker containers is that the dependencies "travel" with your application, so it eliminates a lot of cases that surfaced like "QUESTION: Hey, why is the app is not working in Production? -- ANSWER: I don't know, it works in my development machine...".... For sure you heard that... ;)

With your approach, "_Copy a portable, self-hosted app to fresh deployed machine and execute it or shut it down. That's it._" you will have many more issues when deploying into production or Dev/test environments.

Sure, the development with Docker environment is a little more complex than when developing simple processes, as you say, but it pays off when moving/deploying to multiple environments (Dev/Test, QA, Production) and when using DevOps CI/CD pipelines.

In any case, it is good to have your point of view recorded here.
I'm closing the issue since the premise for this sample application is to show how to develop "Microservice architecture AND container-based applications", so definitely using Docker. :) 
Thanks,
