### ISSUE TITLE
[Feedback] Consider moving migrations folder to their own external projects

### ISSUE THREAD

**Issue by ASADeveloper** [dotnet-architecture/eShopOnContainers#401]
Hi,

Wouldn't it be better to put migration folders in the same project as the related DbContext?

Now the migration files of the IntegrationEventLogContext and OrderingContext are in the Ordering.API.Infrastructure which is in my opinion not a good thing. Because IntegrationEventLogContext  is also used by other services like Catalog.API. In my apps I put the migrations folder inside the DbContext project, implement an IDesignTimeDbContextFactory and change the project to a .netcoreapp 2.0 program with a Program class.

This way at design time I could use all kind of commands and add migration files to local project and don't pollute other projects with the migration files. 

One other thing about current implementation is that as far as I can see, the IntegrationEvents of the Catalog.API depends on the successful migrations inside Ordering.API. 
I don't expect that a BuildingBlock depends on a client service. But it is now the case, isn't it?

By the way, it would also prevent issues like #314

**Comment by CESARDELATORRE** [comment]
You are right, we'll take a look on how to improve this. It is not right to have a dependency between microservices even if it is just about EF Migrations. Each EF Migration should be completely autonomous per microservice. We need to fix this.

**Comment by mvelosop** [comment]
@CESARDELATORRE, digging a little on this issue I realized Catalog and Ordering each have their own migration in their own database, which is the way it should be, to keep the microservices independent. The point here is that they share the IntegrationEventLogEF model, which is in the BuildingBlocks project.

That situation, according to a recent conversation on sharing models, it's ok, because, as I understood, it's not bad to share infrastructure models, not so with business models.

So I'm closing this issue, will reopen in case you deem necessary!

**Comment by josephwambura** [comment]
Hello @mvelosop , I understand the issue has been closed, but how does one run migration in the Catalog.API, I have tried much in vain, where should run from? Thanks in advance. PS. I am running the released solution for dotnet 5.0 and added a test field property to the CatalogItem, and tried to run `add-migration MyTest -c CatalogContext -o Infrastructure/CatalogMigrations`
