### ISSUE TITLE
[Bug] WepSPA is not build in build-bits.ps1

### ISSUE THREAD

**Issue by buzzfrog** [dotnet-architecture/eShopOnContainers#404]
I have a strange problem. When running build-bits.ps1 the command "dotnet publish" is not completed for WebSPA. The dll is not created in the output folder. 

If I remove -parallel in the foreach statement it works.

**Comment by CESARDELATORRE** [comment]
Strange... I haven't had that issue.
You might have done this, but just in case, before running build-bits.ps1, make sure you followed the following steps in order to compile the "JavaScript side":
https://github.com/dotnet-architecture/eShopOnContainers/wiki/06.-Setting-the-Web-SPA-application-up 
If you follow that, you shouldn't have issues with the SPA app.

**Comment by buzzfrog** [comment]
Yes, I did that (compile the JS code) before I got this error. 
I want to report this so if anyone has the same problem, they have a workaround.

**Comment by ramonTC** [comment]
Hi buzzfrog,

We currently introduced a new feature "docker multi-staging" in Dev so it is no longer necessary to use the build-bits.ps1 script to generate the bits.

You can skip that step and just run docker-compose build or docker build to generate the images.

Thx.
