### ISSUE TITLE
Internal server error (JsonReaderException) when running a fresh clone of branch "dev"

### ISSUE THREAD

**Issue by Uziron** [dotnet-architecture/eShopOnContainers#438]
Hi,

I am running into an unhandled exception when launching an unmodified and freshly cloned 'eShopOnContainers-ServicesAndWebApps' solution. The containers are running and everything seems OK on Docker. I have searched a bit and it seems the problem comes from a DNS/URL error somewhere. Is there anything I must do in the 'webmvc' section of 'docker-compose.override.yml' for it to run properly?

I am using Visual Studio Enterprise 2017 (v. 15.5.1) on Windows 10 Enterprise (v. 1709) and am behind a corporate proxy.

Thanks for your help! :)

**Comment by CESARDELATORRE** [comment]
Initially, when using it in VS2017 15.5 or later, you shouldn’t need to do anything additional.
If you were running on a Mac or you want to access the services from a remote app like the Xamarin app in a phone, then, yes, you need to change the .env file and the IP for external access instead of LOCALHOST.
But since you are just trying the MVC app in VS2017, the issue must be related to your environment, I guess.
Can you answer and paste the exact errors that you are getting when trying to run it?
Thanks,

**Comment by Uziron** [comment]
Thank you for your reply. The error happens at runtime when loading the webmvc app. Everything builds properly and then my browser loads the webmvc home page. I get the error page I described instead of the home page. The webmvc app tries to call an API and parse JSON data but that fails because it got a DNS error message instead of the expected JSON. My development machine has a fresh installation of Windows 10, Docker For Windows and Visual Studio and is not joined to my corporate domain. However, I still might be getting some policies that mess with my environment. I am currently not in the office but I could give you more info tomorrow (I am in Europe). Thanks.

**Comment by CESARDELATORRE** [comment]
Yeah, first of all I'd try the same tests in a machine out of the corporate policies, just in case.

**Comment by mikemowgli** [comment]
Hi there, I'm a colleague of @Uziron and we've explored multiple directions. Long story short:
The Docker for Windows engine propagates HTTP_PROXY environment variable inside the containers as it deploys them (as documented [here](https://docs.docker.com/docker-for-windows/#proxies)). So when the webmvc container tries to get json data out of the catalog.api container, it triggers the request to http://catalog.api/api/v1/catalog. But the request is forwarded to the corporate proxy, instead of being targeted to the catalog.api container directly. This can be avoided by defining "catalog.api" in the proxy bypass in the Docker Engine. That propagates a NO_PROXY=catalog.api environment variable inside the webmvc container.
However though, we don't think this is a viable solution: catalog.api is an application specific setting, and defining it in the Docker Engine configuration makes it a system wide setting.
Instead, a cleaner approach is to adapt the docker-compose.yml file like this:
`services:
  [...]
  catalog.api:
    [...]
    environment:
      - NO_PROXY=catalog.api`
This keeps the setting in the scope of the aplication rather than publish it to the platform (which would be unmaintainable should multiple applications, with the same NO_PROXY requirement, run on the host)

**Comment by CESARDELATORRE** [comment]
Using environment: - NO_PROXY=catalog.api and so on is a good/clean approach.
Is this issue about the corporate proxy solved then for you guys?

**Comment by Uziron** [comment]
Hi Cesar. Indeed, we think updating the docker-compose.yml file with the NO_PROXY variable is the right thing to do. Would you consider fixing this directly in the codebase? A lot of corporate developers are likely to run into this problem when trying eShopOnContainers and letting developers handle this themselves might not be the best solution (the process is rather error-prone as several microservices/containers should have this NO_PROXY variable, which should probably not only list catalog.api but other microservices as well). The problem and solution could also be described somewhere in the documentation but it will be another setup step for corporate developers, of which many probably know little about Docker and Compose and just want to see a clean microservices architecture in action. Thanks again for your help.

**Comment by CESARDELATORRE** [comment]
Yes, we’ll add it after some tests and document it in the wiki. Thanks for sharing your experiences with a corporate proxy. :)
I’ll leave this issue open until we focus on this point, due to holidays and other priorities might take some days.
Btw, feel free to also provide a PR for this. :)

**Comment by mikemowgli** [comment]
We ran new tests and it turns out a lot of things need to be tested in order to adapt the entire application to a corporate proxy environment (not only from the webmvc to the catalog.api). Unfortunately we do not have the time to work on that for the moment. We'll try to contribute on this in the coming weeks/months, but we cannot file a PR right away :(

**Comment by mikemowgli** [comment]
Hi,
no progress so far. You can close the issue, although it hasn't been solved.
