### ISSUE TITLE
[Question] Service Fabric

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#448]
Could you please tell us more about roadmap for SF support in a project? We have it in a roadmap https://github.com/dotnet-architecture/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases and sources, but status a bit not clear.

1- Before we got links from .sln files to .sfproj, now links dropped. Will we have lit again?
2- Could we fix our wiki pages, where we have info about deploying from Visual Studio, because we can't do it now in a dev branch https://github.com/dotnet-architecture/eShopOnContainers/wiki/11.-Setting-the-solution-up-in-Service-Fabric ?
3 - Will we add support for service fabric CLI to a project in a nearest future? CLI will help us deploy not only from windows, but also from Linux.  https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-sfctl
4 - any plans to include https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-docker-compose 

@CESARDELATORRE

**Comment by CESARDELATORRE** [comment]
Support for SF is based on these SF project files (either for Linux or Windows SF clusters). 
https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/ServiceFabric 

We decided that we don't need links from the global .sln since the SF project dependencies are just with the Docker images that you need to have in any Docker registry like Docker Hub or Azure Container Registry. Having th SF projects segregated from the .sln with the code shows you better that the only dependency is with the Docker images that need to be already in any Docker Registry.

You are right, the Wiki needs to be updated so it shows the SF projects instead the global solution. 
This is the SF project to be used when deploying to a Linux SF cluster, for instance:
https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/ServiceFabric/Linux/eShopOnServiceFabric/eShopOnServiceFabric.sfproj

We'll update that the next time we test it in SF. I'm updating our TO DO list.

About SF CLI and docker-compose in SF, we will do it in the future, but we have other priorities to focus on first, like creating the API Gateway tier, etc.

Thanks for the feedback! :)
