### ISSUE TITLE
eShopOnServiceFabricBus is not working in Azure Service Fabric cluster

### ISSUE THREAD

**Issue by heavenwing** [dotnet-architecture/eShopOnContainers#450]
I created a test Service Fabric cluster with 3 nodes on Azure.
NodeType is:
OS: Windows 2016 DataCenter with Container
vCPU: 2
Memory: 8G

When I published Application into this cluster, I get errors below:

Error event: SourceId='System.Hosting', Property='ServiceTypeRegistration:RabbitMQType'. The ServiceType was disabled on the node.

Error event: SourceId='System.Hosting', Property='Download:1.0:1.0'. There was an error during download.Container deployment is not supported on the node.

**Comment by CESARDELATORRE** [comment]
Since the OS: Windows 2016 DataCenter with Container, can you confirm that you are trying to deploy the eShopOnContainers **Windows Containers** (not the Linux Containers)?

When you get that error, can you specify the step you took?
Can you specify the detailed steps you took? 

In order to isolate the issue and make sure that it is just related to the RabbitMQ container, you can split the XML manifest deployment files so you deploy each infrastructure container, one by one, first, like "only the SQL container", only the RabbitMQ container, so the deployment issue is isolated.

We'll check SF deployments during the upcoming weeks, just in case things/images/infrastructure have changed in the last weeks.

**Comment by mvelosop** [comment]
Closing this issue as it seems stale! wil reopen  if necessary.
