### ISSUE TITLE
Is there a Chinese version of this document?

### ISSUE THREAD

**Issue by jingxin2015** [dotnet-architecture/eShopOnContainers#462]
Enterprise-Application-Patterns-using-XamarinForms.pdf

Is there a Chinese version of this document?

**Comment by CESARDELATORRE** [comment]
No. As of today we have translated the following:

.NET Microservices Architecture:
https://aka.ms/microservicesebook-zh-cn

Modernizing existing .NET apps with Windows Containers:
https://aka.ms/liftandshiftwithcontainersebook-zh-cn

I'm not aware of plans about translating the Xamarin eBook to Chinese.
I'm adding @davidbritch (owner of the Xamarin eBook) so he's aware of the request.

**Comment by CESARDELATORRE** [comment]
Since this week, the Xamarin eBook in online web format has also been migrated to http://docs.microsoft.com, so it also supports automatic translation to multiple languages.
For Chinese:
[https://docs.microsoft.com/zh-CN/xamarin/xamarin-forms/enterprise-application-patterns/ ](https://docs.microsoft.com/zh-CN/xamarin/xamarin-forms/enterprise-application-patterns/ )

Still no plan for a manual translation in .PDF for the Xamarin eBook.
Closing this issue. Thanks.
