### ISSUE TITLE
[Question] Interservice communication

### ISSUE THREAD

**Issue by goldytech** [dotnet-architecture/eShopOnContainers#484]
Hi,

Thanks for reference project. I wanted to know how does interservice communication happen ? From the documentation I came to know the synchronous communication happen over http with standard request and response , whereas async communication happens over messaging (RabbitMQ). Can you please point me towards the sample code in the repo, where can I find the implementation of sync communications over http ?

**Comment by SychevIgor** [comment]
@goldytech 
https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/src/BuildingBlocks/Resilience/Resilience.Http

**Comment by CESARDELATORRE** [comment]
However, Http communication should happen most of all between the client apps or any API Gateway and the microservices.
We discourage the use of communication between the internal microservices because that will cause the creation of long Http calls across many microservices. 

Microservices should be autonomous from other microservices, as much as possible. Sometimes you need to make exceptions, especially with external services, but those exceptions should be minimized as much as possible.

This is why async communication across microservices is important.
This is explained here in the "Asynchronous microservice integration enforces microservice’s autonomy" section:
https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/architect-microservice-container-applications/communication-in-microservice-architecture 

Therefore, that's why in eShopOnContainers the use of Http communication happens only between the client apps (including a possible API Gateway in between) and the microservices, but not Http communication between the microservices themselves.

**Comment by CESARDELATORRE** [comment]
Closing the issue.
