### ISSUE TITLE
[Feature] Add Authentication to Catalog.API

### ISSUE THREAD

**Issue by raboud** [dotnet-architecture/eShopOnContainers#496]
Currently the Catalog.API does not require Authentication

So anyone can mode Products and change prices...woo hoo free stuff.

**Comment by eiximenis** [comment]
>woo hoo free stuff.
eShopOnContainers trust their customers!!! :P

Yes, you're true. This API should be secured.

**Comment by CESARDELATORRE** [comment]
@raboud Thanks for the feedback. You are right, even when anyone should be able to access the catalog as read-only, the write methods are not secured and they should be. 

In any case, @raboud I want to highlight that eShopOnContainers is not trying to be an eCommerce reference, neither a product that could be deployed in production. It is just a sample architecture with focus on microservices/containers to research on architectural patterns. 

Therefore, at a functional and even security level there are hundreds of gaps, like this one you mention.
For instance, many more functional/security areas that could be improved:
- Anonymous basket
- Additional page level for each product
- Additional private/secured dashboard for the back-office admins with rights to change the Order's status. Right now anyone can change the status from the eCommerce Orders page, which is not "real".
- Complete Order process and payment process
- Improved Security
So, we might improve the functionality/Security as we evolve. But functional features cannot be our priority because this is not meant to be a production-ready product.

I agree that this suggestion could be easy to make and it is not really a new business feature but a not too complex improvement. It could show a pattern on how to secure only part of a microservice. 👍 
The write methods should be secured. We'll do it eventually, thanks for the feedback! :)

**Comment by raboud** [comment]
@CESARDELATORRE would you mind if i took it on?

**Comment by CESARDELATORRE** [comment]
@raboud You mean you'd implement the code and will submit a PR! We'd love if you do that! 👍 
Just make sure that the three apps work after the changes:
- MVC app
- SPA app
- Xamarin app connecting to the containers, by default it uses fake data in-memory.

Thank you! :)

**Comment by raboud** [comment]
@CESARDELATORRE okay...

Got spa workinging...
Got UnitTest working with an In memory IdentyServer TestServer...added 
- updateProductAsAdmin - Created
- updateProductAsUser - Forbidden
- updateProductAnonymour  - Unauthorized

MVC app causing issue.

An unhandled exception occurred while processing the request.
TaskCanceledException: A task was canceled.
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
IOException: IDX10804: Unable to retrieve document from: 'http://10.0.75.1:5105/.well-known/openid-configuration'.
Microsoft.IdentityModel.Protocols.HttpDocumentRetriever+<GetDocumentAsync>d__8.MoveNext()
InvalidOperationException: IDX10803: Unable to obtain configuration from: 'http://10.0.75.1:5105/.well-known/openid-configuration'.
Microsoft.IdentityModel.Protocols.ConfigurationManager+<GetConfigurationAsync>d__24.MoveNext()

dropped back to dev branch ...same thing.

havent tested with Xamarin app yet.

Any clue about the MVC app....all firewalls are open

**Comment by mingyanzhen** [comment]
> @CESARDELATORRE okay...
> 
> Got spa workinging...
> Got UnitTest working with an In memory IdentyServer TestServer...added
> 
> * updateProductAsAdmin - Created
> * updateProductAsUser - Forbidden
> * updateProductAnonymour  - Unauthorized
> 
> MVC app causing issue.
> 
> An unhandled exception occurred while processing the request.
> TaskCanceledException: A task was canceled.
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> IOException: IDX10804: Unable to retrieve document from: 'http://10.0.75.1:5105/.well-known/openid-configuration'.
> Microsoft.IdentityModel.Protocols.HttpDocumentRetriever+d__8.MoveNext()
> InvalidOperationException: IDX10803: Unable to obtain configuration from: 'http://10.0.75.1:5105/.well-known/openid-configuration'.
> Microsoft.IdentityModel.Protocols.ConfigurationManager+d__24.MoveNext()
> 
> dropped back to dev branch ...same thing.
> 
> havent tested with Xamarin app yet.
> 
> Any clue about the MVC app....all firewalls are open

Hello, have you solved it? I have also encountered this problem. It is a branch of dev. My question is on the logon page.If it is solved, can you tell me how to solve it?
SocketException: Cannot assign requested address
System.Net.Http.ConnectHelper.ConnectAsync(string host, int port, CancellationToken cancellationToken)

HttpRequestException: Cannot assign requested address
System.Net.Http.ConnectHelper.ConnectAsync(string host, int port, CancellationToken cancellationToken)

IOException: IDX20804: Unable to retrieve document from: 'http://localhost:5105/.well-known/openid-configuration'.
Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(string address, CancellationToken cancel)

InvalidOperationException: IDX20803: Unable to obtain configuration from: 'http://localhost:5105/.well-known/openid-configuration'.
Microsoft.IdentityModel.Protocols.ConfigurationManager<T>.GetConfigurationAsync(CancellationToken cancel)

**Comment by Misiu** [comment]
Is this solved?

**Comment by mvelosop** [comment]
Closing this issue as it's not in the plans to add authentication to the Catalog API.
