### ISSUE TITLE
Main page closes after stopping solution

### ISSUE THREAD

**Issue by RamazanBIYIK** [dotnet-architecture/eShopOnContainers#504]
I am just a beginner at docker. So please forgive for nonsense question.

First of all thanks a lot it is a great project. I started eShopOnContainers-ServicesAndWebApps with VS-17 for testing if it is working. And it is worked. 15 containers are created. I tested everything that located in wiki page.

After ı stop and close the VS project. I though that localhost:5100 would stand alone. But it don't. 

Is it supposed to be still work after ı close the VS? Because when ı check Container ı could still see the containers. But after a while that container closed too.

Is there any reason for that ?

**Comment by eiximenis** [comment]
Hi @RamazanBIYIK 

Containers created with Visual Studio are only running when VS is open. I don't know exactly when VS kills the containers, but you can't expect to have them available once VS is closed.

To launch containers outside of VS use `docker-compose up` from the command line. This will start all containers, until you type `docker-compose down` to destroy them all.
Note that if you type `docker-compose up` and then launches VS, VS will throw errors when running the project (port already allocated) because VS uses always their own containers but the host ports are already allocated by containers created from command-line.

**Comment by CESARDELATORRE** [comment]
Closing the issue.
