### ISSUE TITLE
[Feature] Centralized logging

### ISSUE THREAD

**Issue by raboud** [dotnet-architecture/eShopOnContainers#528]
I have started using this in most of my apps.

I use Serilog with a gelf sink and a console sink. Configuration in the appsettings so production can disable the console sink.

I add a container to hold my graylog server.

BAM! all my logs in one place easy to see and containerized.

**Comment by mvelosop** [comment]
This looks good, thanks. Good suggestion!

**Comment by raboud** [comment]
I can implement it you all like the idea but i don't want to waste time and effort if the feature is not going to be approved.

**Comment by mvelosop** [comment]
Let's wait for @CESARDELATORRE's comments!

**Comment by CESARDELATORRE** [comment]
@Serilog - Thanks for the suggestion. It is a good approach. The point is that we also have comparable approaches in Azure for distributed logging and I initially don't want to include too many OSS libraries/components in the project because it'll grow too much, but if you do that implementation in a fork within your GitHub repo, we'll review it and point to it from the Wiki so folks have additional options to research. 
If that sounds good for you. :)

**Comment by mvelosop** [comment]
Hi @raboud, I'm closing this issue now, because this has been included in the roadmap.

You might want to get involved somehow on the discussion later on.

Thanks!
