### ISSUE TITLE
Strange implementation of images store in Catalog.API

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#535]
Today I had worked with fully cloud version of an app (deployed to k8 in Azure and all data sources like sql/mondo/storage were in a cloud)
And I spend some time debugging situation that images missed
![image](https://user-images.githubusercontent.com/578954/36950877-94711898-200d-11e8-998e-fba01203cdd9.png)
After some investigation I had recognized what was the primary reason for that. 
src/Services/Catalog/Catalog.API/Controllers/CatalogController.cs method ChangeUriPlaceholder implementation:
 catalogItem.PictureUri = _settings.AzureStorageEnabled
                    ? baseUri + catalogItem.PictureFileName
                    : baseUri.Replace("[0]", catalogItem.Id.ToString());
Looks like initially planned that images could be stored in azure blog storage, but it was not implemented. Catalog.API CatalogContextSeed don't know anything about azure blog storage.
As a result together (implementation of seed methid and  CatalogAzureStorageEnabled : "TRUE" in k8/conf_cloud.yml) file activation this BUG

I think - that the best way to fix will be- implement storing images in azure blog storage... maybe with cdn.
but simple fix will be- if we will drop AzureStorageEnabled setting from Catalog.API and will drop check _settings.AzureStorageEnabled 

Looks like seeding in storage was not done also for marketing.api, but in arm template we have this storage 

@CESARDELATORRE if you are agree to drop this strange check- here is pull request https://github.com/dotnet-architecture/eShopOnContainers/pull/534. but it definitely should be fixed

**Comment by CESARDELATORRE** [comment]
@SychevIgor - The product Catalog images are in plain files only for the "dev version" as you might not have Azure.
But we implemented Azure BLOB support for the Product Images, you just need to enalbe it:
That's why we have this env-var in the .env file:
ESHOP_AZURE_STORAGE_CATALOG_URL=<YourAzureStorage_Catalog_BLOB_URL>

and this at the docker-compose.override.yml for the CATALOG service:
      - AzureStorageAccountName=${ESHOP_AZURE_STORAGE_CATALOG_NAME}
      - AzureStorageAccountKey=${ESHOP_AZURE_STORAGE_CATALOG_KEY}

If a similar approach is not working properly when deploying to KUBERNETES, we should isolate the issue and fix it.
@eiximenis Thoughts?
