### ISSUE TITLE
[BUG] Issue in Visual Studio for Mac when trying to run the solution - Works on docker-compose in Mac

### ISSUE THREAD

**Issue by frizki88** [dotnet-architecture/eShopOnContainers#553]
when i tried to run/build from visual studion on Mac, ive got an error about environment variables for Azure (its only warning if using cli).

error output:

> /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/AddIns/docker/MonoDevelop.Docker/MSbuild/Sdks/Microsoft.Docker.Sdk/build/Microsoft.VisualStudio.Docker.Compose.targets(5,5): Error: The INSTRUMENTATION_KEY variable is not set. Defaulting to a blank string.
> The ORCHESTRATOR_TYPE variable is not set. Defaulting to a blank string.
> The ESHOP_SERVICE_BUS_USERNAME variable is not set. Defaulting to a blank string.
> The ESHOP_SERVICE_BUS_PASSWORD variable is not set. Defaulting to a blank string.
> The ESHOP_AZURE_STORAGE_CATALOG_NAME variable is not set. Defaulting to a blank string.
> The ESHOP_AZURE_STORAGE_CATALOG_KEY variable is not set. Defaulting to a blank string.
> The ESHOP_AZUREFUNC_CAMPAIGN_DETAILS_URI variable is not set. Defaulting to a blank string.
> The ESHOP_AZURE_STORAGE_MARKETING_NAME variable is not set. Defaulting to a blank string.
> The ESHOP_AZURE_STORAGE_MARKETING_KEY variable is not set. Defaulting to a blank string.
> The Compose file '/Users/vidiaputri/Desktop/Sample/eShopOnContainers/obj/Docker/docker-compose.vs.debug.partial.g.yml' is invalid because:
> services.basket.api.build contains unsupported option: 'target'
> services.catalog.api.build contains unsupported option: 'target'
> services.identity.api.build contains unsupported option: 'target'
> services.locations.api.build contains unsupported option: 'target'
> services.marketing.api.build contains unsupported option: 'target'
> services.ordering.api.build contains unsupported option: 'target'
> services.ordering.backgroundtasks.build contains unsupported option: 'target'
> services.payment.api.build contains unsupported option: 'target'
> services.webmvc.build contains unsupported option: 'target'
> services.webspa.build contains unsupported option: 'target'
> services.webstatus.build contains unsupported option: 'target'.
> 
> For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting (docker-compose)

**Comment by CESARDELATORRE** [comment]
@frizki88 - Those should be just warnings (like it happens in VS for Windows or CLI) since the Azure env-vars are not needed when deploying just to Docker or just to an orchestrator.
Is that error stopping your build/run process in VS for Mac?
Please, confirm so I follow up with the VS for Mac Tools team.
Please
Thanks,

**Comment by frizki88** [comment]
@CESARDELATORRE  yes, the error stop the building process

**Comment by prisar** [comment]
@CESARDELATORRE the building process stops because of the error

**Comment by vs0533** [comment]
The key question is  “compose.vs.debug.partial.g.yml' is invalid services.basket.api.build contains unsupported option: 'target'
services.catalog.api.build contains unsupported option: 'target'
services.identity.api.build contains unsupported option: 'target'
services.locations.api.build contains unsupported option: 'target'
services.marketing.api.build contains unsupported option: 'target'”

**Comment by CESARDELATORRE** [comment]
I have reproduced the issue in two different Macs:
![image](https://user-images.githubusercontent.com/1712635/37934751-122d3116-3104-11e8-8856-79bbf981f51f.png)
 
I'll escalate the issue to the Docker Tooling team for "VS for Mac".
Thanks for raising the issue. I'l keep you posted.
For now, in a Mac, the only choice is the CLI, until this issue is solved.

**Comment by CESARDELATORRE** [comment]
Fixed. The issue was that VS for Mac now requires docker-compose v '3.4' in order to be able to F5 or Ctrl+5 as it internally uses the option: 'target' internally.
The solution is simple, just upgrade all your docker-compose files to version: '3.4' and then it works on VS for Mac.
I already updated the docker-compose files so if you do a git pull you should get it and it should work for you now, ok?
Thanks for raising the issue, though. 👍

**Comment by virasana** [comment]
This issue happens on Windows too.  I bumped the version at the top of my docker-compose yaml  as well as the override file produced by Visual Studio and things started to work!  I bumped it to v3.4.
