### ISSUE TITLE
[Refactoring] model and viewmodel in ASP.NET MVC

### ISSUE THREAD

**Issue by pablocastillaquintas** [dotnet-architecture/eShopOnContainers#564]
Hi!

There is something I don't get in the asp.net mvc project. I see:
- Viewmodels (in my understanding the DTOs that are binded to the UI) with viewmodels in that folder.
- Models (in my understanding persisting entities) but in the folder there are DTOs to the microservices.

I would rename those DTOs in model as ServiceMessages inside the Services folder.

What do you think?

**Comment by CESARDELATORRE** [comment]
It is right that those classes are not really "Models" because the MVC app does not work directly against the database like using EF or Dapper. It just communicates with the microservices.
It is called Models because those classes map probably 1:1 (just data/attributes, as in here they don't have any Domain Entity logic/behavior) with the entities used in the microservices.

However, ServiceMessages sounds too generic for me. We want to highlight that those classes are related to the data-message mapped to the entities living or being persisted on the microservices...
I agree that it could have a better name, though...

What about **"ModelDTOs" and moved within the Services folder?**

In any case, this refactoring is not critical. We have a few important merges to happen in the upcoming weeks (related to API Gateways and other "big rocks"), so we might want to wait to do this until that happens, ok?

Thanks for your feedback! 👍

**Comment by pablocastillaquintas** [comment]
I agree with that "ModelDTOs" in the service folder. 

Great job!
