### ISSUE TITLE
Swagger Auth Failing

### ISSUE THREAD

**Issue by darnoldi** [dotnet-architecture/eShopOnContainers#586]
Hi there,

Auth is working fine through the MVC app, can login and view catalog and marketing.

When trying to auth through the Swagger UI on the marketing, location or ordering API's I get
`Sorry, there was an error : unauthorized_client`

In swagger I select the 'Authorize' button and in the popup I leave all at default and submit but get the error. Even If I check the scopes button I get the error?

What am I doing wrong?

Windows 10,
Docker CE 18.03.0
VS 2017 15.7.0 Preview 4

Thanks

**Comment by VladislavAntonyuk** [comment]
you have to paste your token in swagger auth modal window

**Comment by darnoldi** [comment]
> you have to paste your token in swagger auth modal window

Thanks, doesn't clicking authorize in swagger go to the authserver and request a token?

![swagger1](https://user-images.githubusercontent.com/7987624/39120669-5ff04392-46ef-11e8-896b-19162824f07b.png)
![swagger2](https://user-images.githubusercontent.com/7987624/39120670-60264140-46ef-11e8-93fc-1ad0d373f99e.png)
![swagger3](https://user-images.githubusercontent.com/7987624/39120672-6054e022-46ef-11e8-9649-7f7e2ea10813.png)
If I click the authorize button in swagger (image 1), the window is pre-polulated with values which I think should request the token from the auth server (image 2). but accepting those values and clicking authorize again gives me the error message in (image 3)

Thanks for your help

**Comment by darnoldi** [comment]
> you paste incorrect client_id

I'm not pasting any id, that is the one that is pre-populated. Which should I use?

Thanks

**Comment by VladislavAntonyuk** [comment]
You have to pass you client id which is stored in DB

**Comment by darnoldi** [comment]
The client ids are created in Identity/config.cs aren't they?

` new Client
                {
                    ClientId = "marketingswaggerui",
                    ClientName = "Marketing Swagger UI",
                    AllowedGrantTypes = GrantTypes.Implicit,
                    AllowAccessTokensViaBrowser = true,

                    RedirectUris = { $"{clientsUrl["MarketingApi"]}/swagger/o2c.html" },
                    PostLogoutRedirectUris = { $"{clientsUrl["MarketingApi"]}/swagger/" },

                    AllowedScopes =
                    {
                        "marketing"
                    }
                },`

**Comment by VladislavAntonyuk** [comment]
you have to pass your user client id

**Comment by darnoldi** [comment]
Ok so if I understand you, I should log in using the user/password in the MVC app. Go to the database, get the token and then paste that into the swagger request?

If so, please could you show me in swagger where I can paste it?

Thanks again

**Comment by VladislavAntonyuk** [comment]
after you create your user you get client id and after that you can authorize with it

**Comment by darnoldi** [comment]
I do not see anywhere in swagger where I can paste the token.
![swagger4](https://user-images.githubusercontent.com/7987624/39122116-1b55d79c-46f4-11e8-844b-99d04cd92e9d.png)

**Comment by VladislavAntonyuk** [comment]
in authorize modal window in client id

**Comment by darnoldi** [comment]
Ok I think I am understanding you more or less, which field in the database has the clientid I need to paste?

**Comment by VladislavAntonyuk** [comment]
I don't remember exactly but it should be in Users table with Primary key.

**Comment by darnoldi** [comment]
The value in the Id column for the user?
00c9b2d8-d707-4f51-a0ab-6b96ed419417?

![swagger5](https://user-images.githubusercontent.com/7987624/39122626-c7e72e92-46f5-11e8-9a9a-cf368c95518a.png)

**Comment by VladislavAntonyuk** [comment]
seems like yes

**Comment by VladislavAntonyuk** [comment]
no, in table Clients

**Comment by darnoldi** [comment]
This one?
![swagger8](https://user-images.githubusercontent.com/7987624/39122929-9b42e5ba-46f6-11e8-9de5-5ad8e164631d.png)

marketingswaggerui ?

**Comment by VladislavAntonyuk** [comment]
yes

**Comment by darnoldi** [comment]
Thats the one that it has been using since the beginning
![swagger2](https://user-images.githubusercontent.com/7987624/39123051-f176b4f2-46f6-11e8-819a-358cc6124d79.png)

I get the error with that one

**Comment by VladislavAntonyuk** [comment]
I have check, there is no error for me. please switch to master and check does the problem reproduce

**Comment by darnoldi** [comment]
I will do thanks

**Comment by darnoldi** [comment]
I'm getting the same error unfortunately on master.

Before I try on another machine to check environment issues, please tell me:
If I load servicesandwebapps solution, wait for all downloads, Press F5, wait for build and containers and database seed population.
MVC app starts. I do not login anywhere.
I go to http://localhost:5110/swagger/ and click authorize, I leave all setting in modal as they are and click authorize again.
What should I see then?

Thanks for all the help

**Comment by VladislavAntonyuk** [comment]
the page is updated and you have autorized

**Comment by darnoldi** [comment]
Ok thanks,

I will try a PC with a fresh install of windows and let you know

**Comment by VladislavAntonyuk** [comment]
make sure you have correctly started all services and they are heathy

**Comment by darnoldi** [comment]
I have checked, they are all good, but will keep that in mind.

**Comment by darnoldi** [comment]
I am getting the exact same thing on another machine with a clean install of windows 10, 

I must be misunderstanding something.

**Comment by mvelosop** [comment]
Hi @darnoldi, I was having the same problem. 

I think I found the cause, a quick fix and why @VladislavAntonyuk doesn't have the same problem.

Checking the logs I got to this suspect:
![image](https://user-images.githubusercontent.com/7357806/39196136-4e00cacc-47d9-11e8-84e1-ce541be0d0ec.png)

So I checked the code and that value is set in Identity.Api/Configuration/Config.cs:
![image](https://user-images.githubusercontent.com/7357806/39196349-caa1911a-47d9-11e8-8461-2341f7d11f7a.png)

But changing the code there didn't fix the problem, so looking at the database I got to this table:
![image](https://user-images.githubusercontent.com/7357806/39196624-7ce435c6-47da-11e8-9322-c4067676ca33.png)
 And setting the attempted value there did the trick!

This is definitely a bug, with just a quick fix (at least in my case), please let us know if this works for you.

@VladislavAntonyuk I'm guessing you didn't have this problem because you probably haven't recreated the SQL Server container for some time so you might have the proper values in that table. Could you please confirm?

We have to dig around a little to check what's the correct value for the redirection, because it might have changed now that we are using the API Gateway. 

@eiximenis could you please take a look at this?

**Comment by eiximenis** [comment]
I'll check, but I suspect the error is due to a new version of Swashbuckle having a new version of Swagger UI with this new callback url.

**Comment by darnoldi** [comment]
> And setting the attempted value there did the trick!

Confirmed that changing the value in the database solves the problem for me too.

I appreciate your taking the time to investigate this further, I was seriously starting to question my own sanity 8-)

Dave

**Comment by darnoldi** [comment]
For anyone else wanting to use this 'quick fix', you need to replace all instances of 
`/swagger/o2c.html`
in that table with
`/swagger/oauth2-redirect.html`

Obviously keeping the url and ports correct for that service.

**Comment by al-aas** [comment]
@mvelosop I tried everything mentioned in this thread, still facing same issue. I am also using latest code which makes sure the issue mentioned above (related to redirect url) is also fixed in code; I double checked in the mentioned files as well.

When I click 'Authorize' with pre-filled client_id, I get the error saying _"Sorry, there was an error : unauthorized_client"_.

![image](https://user-images.githubusercontent.com/38518236/125065898-d3b88400-e0cb-11eb-9ad0-0be1e6bae668.png)

![image](https://user-images.githubusercontent.com/38518236/125065977-eaf77180-e0cb-11eb-9616-f8bafbc38942.png)

![image](https://user-images.githubusercontent.com/38518236/125066317-4a558180-e0cc-11eb-843b-5230b8a9c82d.png)

![image](https://user-images.githubusercontent.com/38518236/125066365-5c372480-e0cc-11eb-8fdb-73b6ebd8659f.png)

Is there anything I missed?

**Comment by randomkms** [comment]
It was fixed for me by changing Swagger url in browser from http://localhost:5102/swagger/index.html to http://host.docker.internal:5102/swagger/index.html
