### ISSUE TITLE
[Question] Ordering Queries

### ISSUE THREAD

**Issue by cmeyertons** [dotnet-architecture/eShopOnContainers#592]
In the Ordering microservices, why is the `OrderingQueries` implementation in the application layer?  This seems like it be better suited to be in the Infrastructure layer?

And why can't `IOrderingQueries` be in the domain layer?  

I'm relatively new to DDD and read through the Architecting & Developing ebook, and after looking through the code this seemed odd to me.

I would propose performing the following to avoid confusion:
Move `IOrderingQueries` to domain layer
Move `OrderingQueries` to infrastructure layer

I can do the work if approved and necessary

**Comment by mvelosop** [comment]
Closing this issue. Used to create the (first) [post on Simplified CQRS and DDD](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/docs-kb/simplified-cqrs-ddd/post.md) in the [Knowledge Base](https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/docs-kb)

**Comment by LREMe** [comment]
Hi @cmeyertons , @CESARDELATORRE 
This is the question / answer that I was looking. Many companies/developers are crazy about DDD and other patterns. I was looking at the samples and I was wondering: why you make that difference?. Also, it observed that you are creating a "mini" DDD just for the queries (so you have 2 DDD's). 

I have to add and extra comment, maybe the best solution is to put the queries on stored procedures: out from the code. When you have an application with really high use, a problem that may arise is that the queries will degrade and you will be looking at <b>historical data migration strategies</b>, or requiring more computing power (and not always you are going to be allowed to solve it on that way). You need to analyze your queries, see if you need keys, and if you database is correctly maintained, recompile keys or add some. RDBMS allows you to optimize plans and gives you an extra.

I'm returning to be a full time developer after like 10 years, and looking at the practices, I'm seeing that the applications may have a lot of performance issues because the extra layers. Respecting patters is a good way to reassure maintenance, but, on daily operations the users will hate you if your application is not performing well (I had to correct performance issues with an application on the last month that was respecting patterns, but not using store procedures in any way: after changing some key parts to procedures, creating keys and recompiling them, the application returned to work correctly: none of the team were able to see the problem because they use only EF - not like in the old days :D - ).

Thanks
