### ISSUE TITLE
[Question]Debug eShopOnContainers from vs15.6.7 error

### ISSUE THREAD

**Issue by qpcyet** [dotnet-architecture/eShopOnContainers#594]
Hello,

Since I clone the newest dev branch of ShopOnContainers, open solution with eShopOnContainers-ServicesAndWebApps.sln, and try to press the Docker button to run debug mode in vs 2017(ver 15.6.7) . It rise an error like below: 

yaml.scanner.ScannerError: while scanning a simple key
  in "E:\MyGit\eShopOnContainers\obj\Docker\docker-compose.vs.debug.g.yml", line 106, column 1
could not find expected ':'
  in "E:\MyGit\eShopOnContainers\obj\Docker\docker-compose.vs.debug.g.yml", line 107, column 15。

docker-compose	D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	363	

Check in the file docker-compose.vs.debug.g.yml error line 106 and 107:

  mobilemarketingapigw:
    image: eshop/ocelotapigw:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_mobilemarketingapigw$
    volumes:
      - E:\MyGit\eShopOnContainers\src\ApiGateways\ApiGw-Base:/app
      - C:\Users\qpcyet\vsdbg\vs2017u5:/remote_debugger:ro
(line 106)$nuget_volume_mapping_mobilemarketingapigw$
(line 107)    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_mobilemarketingapigw$ bin/Debug/netcoreapp2.0/OcelotApiGw.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""

This issue has been confused me several days. Any suggestion and help are appreciated. 
Thanks a lot
qpcyet

**Comment by G00DD4Y** [comment]
Hi @qpcyet, you are trying to run the solution from VS 15.6.7. But according to https://github.com/dotnet-architecture/eShopOnContainers/wiki/02.-Setting-eShopOnContainers-in-a-Visual-Studio-2017-environment, in order to run the solution, you need at least VS 15.7 Preview 2.0.

**Comment by qpcyet** [comment]
Hello @G00DD4Y , 

EShopOnContainers worked well on VS 2017 15.6.6 for me. This issue happened from VS 2017 15.6.7.  According to this page (https://github.com/Microsoft/DockerTools/issues/52), the issue source seems from VS DockerTools.

Thanks a lot for your information.

**Comment by CESARDELATORRE** [comment]
For the latest version of eShopOnContainers ([dev branch](https://github.com/dotnet-architecture/eShopOnContainers)) you need **VS 2017 15.7 Preview** because of a limitation in VS Docker Tools which is not able to run multiple containers based on the same Docker image. We're using that approach since we introduced the API Gateways which are using the same Docker image base on Ocelot API Gateway image.

VS 2017 15.7 RTM will be released kind of soon, though, that's why we moved forward with the Preview for a while. In addition, in the DEV branch we'll be soon updating code aligned with new features in .NET Core 2.1 Preview and ASP.NET Core 2.1 Preview.

If you want to use **VS 15.6.x** and just .NET Core 2.0 with no API Gateways, you can use eShopOnContainers but the version on [Master branch](https://github.com/dotnet-architecture/eShopOnContainers/tree/master) which is not using the API Gateways and other minor updates we're doing, as mentioned.

Finally, eShopOnContainers ([dev branch](https://github.com/dotnet-architecture/eShopOnContainers)) also works with just Docker CLI (docker-compose up) as it uses Docker Multi-Stage build and the mentioned issue/limitation was just in VS 2017 15.6.x or previous.


Hope this helps.

**Comment by qpcyet** [comment]
It's very clear and helpful for me what your explain. This issue is closed. 
Thank you.
