### ISSUE TITLE
Testing in VSTS CI/CD

### ISSUE THREAD

**Issue by benbuckland** [dotnet-architecture/eShopOnContainers#606]
Hey All,

Is there plans to flesh out continuous testing in VSTS CI/CD?

Thanks, Ben.

**Comment by CESARDELATORRE** [comment]
Good question.. 👍 
Yes, we're planning to first change the approach for the Unit Tests and Integration Tests we have now and split all the tests by microservices, instead of a single point for tests that we have now. That will favor autonomy for each microservice including the tests.
After that (in a few weeks) we're planning to run those tests in our current VSTS CI/CD pipelines that also need to be updated.
My question is, what do you mean with "flesh out continuous testing in VSTS CI/CD?". 
Documentation about it? - Access to our VSTS pipelines?

**Comment by mvelosop** [comment]
Hi @benbuckland, I'm just cleaning open stale issues and I think you might find some guidance in issue #549, including the [blog post from @eiximenis](https://geeks.ms/etomas/2018/03/07/ejecutar-pruebas-de-tus-contenedores-en-vsts/) (in spanish, but [google translator does a good job if you need it](https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fgeeks.ms%2Fetomas%2F2018%2F03%2F07%2Fejecutar-pruebas-de-tus-contenedores-en-vsts%2F&edit-text=)) and the [question in Stack Overflow](https://stackoverflow.com/questions/49492110/vsts-dotnet-with-docker-fail-to-publish-tests) adds an important tip!
