### ISSUE TITLE
Cannot find ordering.signalrhub image

### ISSUE THREAD

**Issue by Kiechlus** [dotnet-architecture/eShopOnContainers#613]
- I did `git pull` causing lot of stuff concerning `signalrhub` to be added.
- Cannot find this image here: https://hub.docker.com/u/eshop/
- `docker-compose pull` : ERROR: pull access denied for eshop/ordering.signalrhub, repository does not exist or may require 'docker login'

**Comment by eiximenis** [comment]
Hi @Kiechlus 
I pushed the eshop/ordering.signalrhub:dev to Dockerhub

Hope it helps.

**Comment by Kiechlus** [comment]
Now I get `ERROR: manifest for eshop/ordering.signalrhub:latest not found`.
As a workaround I removed all references to signalrhub in `docker-compose.yml` and `docker-compose.override.yml`, the SPA on http://localhost:5104/ seemed to work without it.

**Comment by eiximenis** [comment]
Hi!
I just pushed `:dev` tag, because SignalR is only in `dev` branch.
Are you using docker-compose from CLI?

If this is the case, just declare an environment variable called `TAG` with the value `dev` and then do the `docker-compose pull`. That should pull the `:dev` tag.

Or as a workaround, once pulled the dev tag, rename locally to latest by typing:

```
docker tag eshop/ordering.signalrhub:dev eshop/ordering.signalrhub:latest`
```
