### ISSUE TITLE
[Question] Solution structure vs CI (Teamcity for example)

### ISSUE THREAD

**Issue by kkozlowski89** [dotnet-architecture/eShopOnContainers#623]
Hi,

I have question about solution structure. Is it good to have all projects/services in one git repository in case when CI is used. Potentially problem: when you push your code (for example you changed Catalog Api), CI environment handle VCS trigger (for example in teamcity) and build all "services" and share new version. How to avoid similar situation?

Thanks

**Comment by CESARDELATORRE** [comment]
For a production environment I'd prefer/recommend a single repo per microservice. You'll have a lot more flexibility and if you have multiple dev teams working on different microservices, that also will help for those multiple dev teams.
In eShopOnContainers we're using a single repo per solution because we're looking to have the simples approach for any developer to grab/clone the code, make it work and explore it. If we had a single Git repo per microservice it'd be much more complex to deploy and see the end-to-end app working.
Closing the issue/question.

**Comment by kkozlowski89** [comment]
Thanks for quick reply.
