### ISSUE TITLE
error compiling mobile applications

### ISSUE THREAD

**Issue by franperezlopez** [dotnet-architecture/eShopOnContainers#629]
Hi,

I'm trying to deploy the mobile applications. I'm using the solution file named `eShopOnContainers-MobileApps.sln`, but I can't even compile the common project `eShopOnContainers.Core`. I tried with Visual Studio 2017 15.7.3 and 2017 Preview, and it gives me the same error

![image](https://user-images.githubusercontent.com/1222398/41120525-17ecb952-6a96-11e8-95d6-d58b556b053b.png)

thanks

**Comment by mvelosop** [comment]
Hi @franperezlopez!

I just tried the latest **dev** commit and I could compile the .Core project.

Bear in mind that the **dev** and **master** branch had undergone some adjustments lately.

If you can delete your local repo and clone back this master repo I suggest you to do that.

If you can't just replace the clone, then, please, follow the directions in issues #599 and #628.

Hope this helps.

**Comment by jsuarezruiz** [comment]
Hi @franperezlopez,

I have tried several versions on Windows and macOS using the **dev** branch.
In Windows I have tested with version 15.7.3 as well as with Preview 15.8.0 Preview 2.0:

![screen shot 2018-06-08 at 09 24 14](https://user-images.githubusercontent.com/6755973/41152222-4cb72f14-6b13-11e8-8909-a419c9afd142.png)

And in macOS with versions 7.5 and 7.5.2.40 (last of the stable channel):

![screen shot 2018-06-08 at 09 27 51](https://user-images.githubusercontent.com/6755973/41152269-778811fe-6b13-11e8-9aba-b09553f0fd75.png)

Compile without problems. Maybe I am not using the the same branch.
 
The error seems to be from duplicates **EmbededResources**, the XAML views. This error can be for several reasons. On the one hand, if there are different versions of Xamarin.Forms in the .NET Standard library and each platform projects. In the dev branch, everything looks fine, since everyone uses Xamarin.Forms 3.0.0.482510. On the other hand, can you look if you have something like the following lines in the csproj?
 
```
<ItemGroup>
  <EmbeddedResource Include = "App.xaml">
    <Generator> MSBuild: UpdateDesignTimeXaml </ Generator>
  </ EmbeddedResource>
  ...
</ ItemGroup>
```
 
Regards.

**Comment by franperezlopez** [comment]
I had to clear Visual Studio nuget cache(s) and remove /packages, /obj and /bin folders ... but in the end, it worked

thanks for your support!!
