### ISSUE TITLE
Build failed on Windows 10

### ISSUE THREAD

**Issue by MPasadu** [dotnet-architecture/eShopOnContainers#635]
I followed the steps at https://github.com/dotnet-architecture/eShopOnContainers/wiki/02.-Setting-eShopOnContainers-in-a-Visual-Studio-2017-environment

But when trying to Run the docker-compose the build fails:

Output Log:

1>C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.1.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(121,5): error : rzc generate exited with code -1073741819.
1>Done building project "WebMVC.csproj" -- FAILED.
1>C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.1.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(121,5): error : rzc generate exited with code -1073741819.
1>Done building project "Identity.API.csproj" -- FAILED.
1>C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.1.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(121,5): error : rzc generate exited with code -1073741819.
1>Done building project "WebStatus.csproj" -- FAILED.

**Comment by MPasadu** [comment]
After deleting the file in question, the build runs and succeeds but then I get the following prompt from Visual Studio:

> Exception has been thrown by the target of an invocation.

Last output from docker:

> Step 4/4 : EXPOSE 80
>  ---> Using cache
>  ---> d72255d97ef4
> Successfully built d72255d97ef4
> Successfully tagged eshop/webmvc:dev
> ========== Debugging ==========
> ========== Debugging ==========

**Comment by MPasadu** [comment]
In case someone else is getting this error. I guess it is a memory limitation. You should have 16Gb memory at least.

**Comment by CESARDELATORRE** [comment]
@MPasadu - Thanks for the note. 👍 
That's right. That's why we say so in the Dev-machine-requirements wiki post:
https://github.com/dotnet-architecture/eShopOnContainers/wiki/00.-Dev-machine-requirements

**Recommended Hardware requirements:**
**16Gb of memory RAM** - Since you need Hyper-V for Docker Community Edition (aka. Docker for Windows/Mac) in order to run the Linux Docker Host and we're also running a SQL Server container and a Redis container. An 8Gb RAM machine might be too tight.

With 8 Gb you might be able to make it but with plain Docker CLI "docker-compose up" and no any other app open, etc...

Closing the issue, ok? :)
