### ISSUE TITLE
[Question] New to API Gateway and BFF Patterns

### ISSUE THREAD

**Issue by stumpykilo** [dotnet-architecture/eShopOnContainers#637]
How and where do the controller methods like UpdateAllBasket in the Web.Shopping.HttpAggregator project get called? Do any of the services communicate with each other internally without the event bus?

**Comment by CESARDELATORRE** [comment]
The Http communication is as follows:
Client app --> API Gateway --> (Optional) HttpAggregator --> Internal Microservices
The HttpAggregator services are meant to be used only for certain Http calls that are more efficient if you aggregate them in a single call. Especially for mobile and SPA apps, it is more efficient instead of a chatty communication from remote apps.

The Event Bus is based on async communication based on RabbitMQ or Azure Service Bus and it is used for integration events derived from transactions that happened in any of the microservices and when other microservices need to be aware of those events, so they are subscribed to those events. But the Event Bus it just for events, not for queries, like Http calls.

Therefore, the HttpAggregator services are not using the event bus.

**Comment by stumpykilo** [comment]
Thanks @CESARDELATORRE for your response, that is really helpful. I'm also trying to understand how the eShopContainer services communicate between themselves (internally - querying), do they just use an HttClient call? Can you point me to an example of this in the source code?

**Comment by CESARDELATORRE** [comment]
@stumpykilo - This section from the book might be interesting for you:
[https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/architect-microservice-container-applications/communication-in-microservice-architecture](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/architect-microservice-container-applications/communication-in-microservice-architecture)

The internal microservices should have minimum or no Http communication at all between them, if possible. If you create long Http requests with many microservices within a single original Http request, your microservices won't be as autonomous as they could be and things can get pretty bad when you have any issue in one of them.
That is also a reason why you also might need async comm with the Event Bus, to have eventual consistency between the microservices thanks to the integration events.
Hope it helps. 👍

**Comment by CESARDELATORRE** [comment]
@stumpykilo - HttpAggregator services are not used from C# code. They are called only from the Ocelot API Gateways and originally from the client apps. Take a look to the configuration.json like here:
https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/ApiGateways/Web.Bff.Shopping/apigw/configuration.jsonIn there you can see there are routes for the "webshoppingagg" service/container.

About this question:
What would justify the need to put Http communication between two internal services (say an Inventory service needs to do a simple lookup from an Item service)? Would you use the event bus to do that type of query? Would you or could you use an API Gateway type service to do that type of query?

Usually, don't do that. Each microservice has to have all the data it needs for its processes. If you don't have the data you need, two things might happen:
1. That microservice's boundary might be wrong and it should be part of a larger microservice.
2. Duplicate that data (just for queries) in your microservice with eventual consistency based on async communication like when using the integration events with the Event Bus. Example is the price in the Catalog and the price in the Basket that is updated with eventual consistency with integration events.

The Event Bus is used only to propagate data through integration events, things that happened in the past in other microservices. So it is basically about updates. You don't use the Event Bus for queries.

**Comment by kolluri-rk** [comment]
@CESARDELATORRE - Thank you so much for your guidance. Yes, its certainly helpful. You just double confirmed my understanding on sharing data between microservices with integration events. Thanks a lot for clarifying me why we should not use HttpAggregation services as business rules orchestrator. 

But after looking at **Web.Shopping.HttpAggregator/Controllers/BasketController/AddBasketItem**, I'm trying to relate this to our business scenario. In AddBasketItem method, its pulling data from Catalog service and preparing BasketDataItem. Then its sent to Basket service. Similar functionality in UpdateAllBasket as well. Basket service is subscribed to Price changed event and Order started event, and perform necessary changes in it. With this, we are not replicating entire Catalog data to Basket service. We are just making catalog data available to Basket service through HttpAggregator. However changes are propagated with integration events. 

I'm seeing similarity in our case as we just need few meter attributes in order to perform billing. I'm very much leaning towards maintaining that data through integration events (created/changed/deleted). However after seeing  Web.Shopping.HttpAggregator, I'm just trying to evaluate if I can do similar thing while posting a bill. And Billing service will subscribe to meter attribute(s) changes and perform necessary actions. Either cancelling and re-billing pending bills of that meter or push them to a workflow for further review. 

Please let me know your thoughts. Thanks again for constantly responding on this thread with your guidance. 

![image](https://user-images.githubusercontent.com/15665790/41861558-a57ecec2-786f-11e8-8bbf-a282d5904e33.png)

**Comment by stumpykilo** [comment]
So much great and helpful content in this thread. Thanks @CESARDELATORRE and @kolluri-rk for all the replies and links. I'm sold on the api gateway approach and probably using Ocelot for our solution. One question I had was how would you do the gateways without docker? Would you just have everything that is the ApiGw-Base in each Bff service with its own configuration.json? Thanks again for all of y'alls help!!

**Comment by CESARDELATORRE** [comment]
@stumpykilo - Without Docker, well, if you want to re-use implementation across multiple API Gateways, it won't be "so clean"...
One approach could be to have multiple IWebHost projects where the main files, the Program.cs and the Startup.cs would be "linked-files" pointing to the base project. Something like that...

Much cleaner when using the same Docker image, of course.. :)

**Comment by mvelosop** [comment]
Closing this issue now, will reopen if needed.
