### ISSUE TITLE
[QUESTION] How is Order.Id in DomainEventHandlers initialized before persisting?

### ISSUE THREAD

**Issue by nchAlex** [dotnet-architecture/eShopOnContainers#642]
Order.Id in ValidateOrAddBuyerAggregateWhenOrderStartedDomainEventHandler is not initialized, because OrderStartedEvent is raised from Order constructor before the Order object is persisted to the database. Events are dispatched to handlers before saveEntities is called in OrderingContext.

https://github.com/dotnet-architecture/eShopOnContainers/blob/262341c140facd881237f033c5b43cd870c7a6c5/src/Services/Ordering/Ordering.API/Application/DomainEventHandlers/OrderStartedEvent/ValidateOrAddBuyerAggregateWhenOrderStartedDomainEventHandler.cs#L52

https://github.com/dotnet-architecture/eShopOnContainers/blob/262341c140facd881237f033c5b43cd870c7a6c5/src/Services/Ordering/Ordering.Domain/AggregatesModel/OrderAggregate/Order.cs#L65

https://github.com/dotnet-architecture/eShopOnContainers/blob/262341c140facd881237f033c5b43cd870c7a6c5/src/Services/Ordering/Ordering.Infrastructure/OrderingContext.cs#L56

Please, let me know if I misunderstood something and Order.Id is actually somehow initialized when we use it in ValidateOrAddBuyerAggregateWhenOrderStartedDomainEventHandler.

Please also recommend a way to solve this problem other than using GUIDs.

**Comment by mvelosop** [comment]
Hi @nchAlex,

This issue is handled internally by EF using the [HiLoValueGenerator](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.valuegeneration.hilovaluegenerator-1?view=efcore-2.1) to assign Id values PRIOR to persisting to the database. Hence there's actually an Id value by the time the domain event handler kicks in.

**What's the HiLo strategy?**

It's just a fancy name for using a [database sequence](https://docs.microsoft.com/en-us/sql/relational-databases/sequence-numbers/sequence-numbers?view=sql-server-2017) to GET unique Id values that you can use before persisting.

The database ensures sequence values are unique, so you can use them as soon as you get them.

**How does it work?**

1. Configure the entity to use the HiLoStrategy:
https://github.com/dotnet-architecture/eShopOnContainers/blob/262341c140facd881237f033c5b43cd870c7a6c5/src/Services/Ordering/Ordering.Infrastructure/EntityConfigurations/OrderEntityTypeConfiguration.cs#L20-L21

2. When the entity is added to the context:
https://github.com/dotnet-architecture/eShopOnContainers/blob/262341c140facd881237f033c5b43cd870c7a6c5/src/Services/Ordering/Ordering.Infrastructure/Repositories/OrderRepository.cs#L30  

3. (Simplifying) EF goes to the DB and gets a sequence number and assigns the value right there, as per configuration in step 1. And that's how you have an Id before persisting so you can do do the trick!

EF doesn't go to the DB every time, the [HiLoValueGenerator](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.valuegeneration.hilovaluegenerator-1?view=efcore-2.1) takes care of the details to do it just when it's really needed.

Hope this helps.

**Comment by mvelosop** [comment]
Marking this as a question, for it could be a candidate for a KB post!
