### ISSUE TITLE
[BUG] When subscribing more than 1 different event handlers for the same event type

### ISSUE THREAD

**Issue by markphillips100** [dotnet-architecture/eShopOnContainers#645]
I assume it's a valid use case to support more than one handler of different types for the same event type, at least `GetHandlersForEvent` will return more than one for a given event if they are registered?

If more than one handler is registered it means the `InMemoryEventBusSubscriptionsManager` can record duplicate event types in its private `_eventTypes` variable.  This causes a LINQ error when `GetEventTypeByName` is called during processing of the event.

Recommend using `FirstOrDefault` for `GetEventTypeByName` and also inside the logic for `DoRemoveHandler` (so as to maintain a 1-1 correlation with handler and event type counts.

**Comment by mvelosop** [comment]
Hi @markphillips100, nice observation! 👍

However, I think it would be better to stop the duplication from occuring in the first place, by just changing this:
https://github.com/dotnet-architecture/eShopOnContainers/blob/262341c140facd881237f033c5b43cd870c7a6c5/src/BuildingBlocks/EventBus/EventBus/InMemoryEventBusSubscriptionsManager.cs#L23
to `_eventTypes = new HashSet<Type>();`, because that ensures uniqueness in one LOC.

That said, it would good to know @CESARDELATORRE's opinion on this one, because although it is a dormant bug, perhaps the InMemoryEventBusSubscriptionsManager is just ok for the sample app because it's intended to be replaced by a more robust implementation in production.

**Comment by mvelosop** [comment]
Closing this issue as it was solved with PR #818.
