### ISSUE TITLE
[Question] CQRS Commands

### ISSUE THREAD

**Issue by PopovKS** [dotnet-architecture/eShopOnContainers#659]
After reading a book and see of source code, i'm have several question. 

1) If me is necessary two type of repositories in one command, and both it have property of type IUnitOfWork, who of them to call SaveChanges()?

Example: 

`
   public class AddTokensCommandHandler : IRequestHandler<AddTokensCommand,Token[]>
    {
        private readonly ITokenRepository _tokenRepository;
        private readonly IIndexRepository _indexRepository;

        public AddTokensCommandHandler(ITokenRepository tokenRepository , IIndexRepository indexRepository)
        {
            _tokenRepository = tokenRepository;
            _indexRepository = indexRepository;
        }

        public async Task<Token[]> Handle(AddTokensCommand request, CancellationToken cancellationToken)
        {
            var index = await _indexRepository.GetAsync(request.IndexName);
            foreach (var requestToken in request.Tokens)
            {
                var tokenType = index.GetTokenType(requestToken.TokenType);
                
                var token = new Token(tokenType.Id, request.Value, request.Text);
                token = await _tokenRepository.AddTokenAsync(token);

                token.Events.Add(new RegisterTokenHoldersEvent(token, request.DocumentId, request.Holders));
            }
            
            await _tokenRepository.UnitOfWork.SaveChangesAsync();

            return new Token[0];
        }
    }`

2) Is it possible to use another an approach, when we have a IUnitOfWork of set IRepositories, and send it as constructor parameter.

Example:

`
    public class UnitOfWork : IUnitOfWork
    {
        private readonly CustomDbContext _context;

        public UnitOfWork(CustomDbContext context)
        {
            _context = context;
        }
        public ITokenRepository TokenRepository => new TokenRepository(_context);
        public IIndexRepository IndexRepository => new IndexRepository(_context);

        public async Task SaveChangesAsync()
        {
            await _context.SaveChangesAsync();
        }
    }   

    public class AddTokensCommandHandler : IRequestHandler<AddTokensCommand,Token[]>
    {
        private readonly UnitOfWork _unitOfWork;

        public AddTokensCommandHandler(UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<Token[]> Handle(AddTokensCommand request, CancellationToken cancellationToken)
        {
            var index = await _unitOfWork.IndexRepository.GetAsync(request.IndexName);
            foreach (var requestToken in request.Tokens)
            {
                var tokenType = index.GetTokenType(requestToken.TokenType);
                
                var token = new Token(tokenType.Id, request.Value, request.Text);
                token = await _unitOfWork.TokenRepository.AddTokenAsync(token);

                token.Events.Add(new RegisterTokenHoldersEvent(token, request.DocumentId, request.Holders));
            }
            
            await _unitOfWork.SaveChangesAsync();

            return new Token[0];
        }
    }`

Why did you choose the first approach as the main?

Big thaks, for your answers, this will help me understand the misunderstanding.

**Comment by mvelosop** [comment]
Hi @PopovKS,

I'm not sure I'm getting your question right, because it's not related to eShopOnContainers, but I will try to give you some general guidance.

Assuming each UnitOfWork (UoW) refers to a bounded context (BC) and both BC connect to the same DB, a command should be handled by just one BC, if it doesn't it could be a design issue, and maybe the involved BC should be just one or...

Maybe the first BC should generate a domain event that would be handled, within the same microservice by the second, BC.

If the change in both BC should be in the same transaction, then you should define a transaction to encompass both updates and commit on the transaction, not on the UoW.

If the BC relate to different DBs and can't use a transaction, then you are probably talking about different microservices and you should communicate them asynchronously, with an integration event through something like RabbitMQ.

The domain events section starting on page 222 on the microservices ebook: https://aka.ms/microservicesebook treats this subject with great detail.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue, feel free to comment though, will reopen if necessary.
