### ISSUE TITLE
Bower deprecated

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#670]
Bower deprecated, right? 
https://bower.io/blog/2017/how-to-migrate-away-from-bower/
https://blogs.msdn.microsoft.com/webdev/2018/04/18/what-happened-to-bower/
https://blogs.msdn.microsoft.com/webdev/2018/07/05/workaround-for-bower-version-deprecation/

We also need to drop it from the project to look up-to-date...
https://github.com/dotnet-architecture/eShopOnContainers/search?q=bower
and also in some other places like https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Identity/Identity.API/bower.json

**Comment by CESARDELATORRE** [comment]
Yeah, eliminating Bower is in our roadmap.
The usage if Bower is very small in eShopOnContainers, though, and in the MCV app, only.
Open to anyone creating a PR to substitute Bower by Webpack, probably. :)

**Comment by mvelosop** [comment]
@CESARDELATORRE, I guess even [Library Manager](https://blogs.msdn.microsoft.com/webdev/2018/04/17/library-manager-client-side-content-manager-for-web-apps/) should be enough, right?

**Comment by rafsanulhasan** [comment]
Instead of dropping **bower**, it is possible to specify a bower registry explicitly in _bower.json_ like this
{
	"directory": "wwwroot/lib",
	"registry": "https://registry.bower.io"
}

I found it useful and working. This is needed in the Identity.API and WebMVC projects only because only the specified projects use bower in the solution.

**Comment by mvelosop** [comment]
Mine is 15.7.6 (was yours a typo?).

When you create a new ASP.NET Core MVC project, neither Bower nor Gulp are around anymore, only the minified libs in /wwwroot/lib, just like that!

And _Layout.cshtml references those as a fallback option, preferring the CDN ones.

So Bower and Gulp are gone for good.

**Comment by rafsanulhasan** [comment]
That's right, mine is also 15.7.6 (it was a typo :(). I understand that and agree. but in this solution, two projects (WebMVC app and Identity.API Service) are still using **bower** as a _client-side library manager_. What I meant to say in my previous comment is: while the project is not fully upgraded to drop bower and use LibMan or WebPack or any other alternatives instead of Bower, this is a temporary solution to using bower from npm and specifying the new registry address in .bowerrc file in those two projects otherwise it shows an error and thus resists us from running or building the specified projects. The solution, I'm talking about could, resolve the error while downloading packages like jquery from bower temporarily and at least allow running the solution without any error but it only shows a depreciation warning.

**Comment by mvelosop** [comment]
Fair enough!

**Comment by rafsanulhasan** [comment]
Okay, thanks again for your quick reply. So could you please merge the PR #705 after a review?

**Comment by rafsanulhasan** [comment]
Hi @mvelosop,
I have created a new PR #714 which replaces Bower from all related projects with [Library Manager (LibMan)](https://blogs.msdn.microsoft.com/webdev/2018/04/17/library-manager-client-side-content-manager-for-web-apps/)

**Comment by mvelosop** [comment]
Closing this issue, as Bower was removed as of 20-SEP-2018 (43c15802c183274d4cc3bd06812a05a285b1a229)
