### ISSUE TITLE
where is database of this sln

### ISSUE THREAD

**Issue by 1936xinyang** [dotnet-architecture/eShopOnContainers#672]
Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word

**Comment by CESARDELATORRE** [comment]
What do you mean? The databases run in a SQL Server Docker container. For high-availability, You could move it to Azure SQL DB, too.
The connection strings are env vars in the docker-compose.override.yml

**Comment by mvelosop** [comment]
Hi @1936xinyang,

Since this app runs on containers, the database is within a container named **sql.data**, that exposes its database port as 5433 on localhost, hence this part in the connection string: **Server=tcp:127.0.0.1,5433;**.
Once you have all the system running as per https://github.com/dotnet-architecture/eShopOnContainers/wiki/03.-Setting-the-eShopOnContainers-solution-up-in-a-Windows-CLI-environment-(dotnet-CLI,-Docker-CLI-and-VS-Code), you can open SQL Server Managment Studio and connect to **tcp:localhost,5433** (user=sa, password=Pass@word) and should see this:

![image](https://user-images.githubusercontent.com/7357806/42521789-8d985032-8461-11e8-879f-61a11e15a502.png)

Hope this helps.

**Comment by 1936xinyang** [comment]
thanks

**Comment by 1936xinyang** [comment]
thanks, @mvelosop @CESARDELATORRE
