### ISSUE TITLE
Kubernetes deployment on AKS, got UnAuthorized response on adding item to cart or loading orders

### ISSUE THREAD

**Issue by jijiechen** [dotnet-architecture/eShopOnContainers#690]
I followed [the steps in the wiki](https://github.com/dotnet-architecture/eShopOnContainers/wiki/10.1-Deploying-to-Kubernetes-(AKS-and-local)-using-Helm-Charts) and successfully set a running website on my kubernetes cluster on AKS.

I used the demouser to login and tried to add some items into cart, but failed. And I tried to check existing orders from the user profile menu, failed again.
After a quick diagnosing, I see 401 responses returned for these requests:
* `/webshoppingapigw/api/v1/basket/`
* `/webshoppingapigw/api/v1/o/orders` 

It seems the `webshoppingapigw` gateway can not validate the token provided along with the requests. Logs from this gateway proved my guess:

```
Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      => ConnectionId:0HLFKCI55LKQ4 => RequestId:0HLFKCI55LKQ4:00000001 RequestPath:/webshoppingapigw/api/v1/b/basket/6735e47b-12af-4cc4-831b-8021c004cb71
      requestId: no request id, previousRequestId: no previous request id, message: /api/v1/b/basket/6735e47b-12af-4cc4-831b-8021c004cb71 is an authenticated route. AuthenticationMiddleware checking if client is authenticated,
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[1]
      => ConnectionId:0HLFKCI55LKQ4 => RequestId:0HLFKCI55LKQ4:00000001 RequestPath:/webshoppingapigw/api/v1/b/basket/6735e47b-12af-4cc4-831b-8021c004cb71
      Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10500: Signature validation failed. No security keys were provided to validate the signature.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
```

My website locates at http://trueshop.a147769798874e40879f.eastus.aksapp.io/
I may delete the cluster a week later since the cost is high. Before being deleted, I can help diagnose it by providing logs and cluster managing privileges, if required.

**Comment by CESARDELATORRE** [comment]
@jijiechen - There's a known issue related to the Http headers size allowed by AKS ingress.
The headers sent by IDENTITY SERVER are too large for the by default config in the default NGINX ingress in AKS, so when we’re returning from a login, we get a 500 http.

This issue is related to this one: https://github.com/dotnet-architecture/eShopOnContainers/issues/691
So, I'm merging and closing this, ok?

**Comment by eiximenis** [comment]
Hi @jijiechen and @CESARDELATORRE 

I reopened the issue, because **there were (also) an error in our side**. The error was unrelated to the AKS nginx ingress, but could not be tested before (due to the AKS nginx ingress error).

I merged PR #693 which solves the error.

**PART 1: Solve the AKS nginx ingress controller headers problem**

The default nginx ingress controller deployed to AKS uses a default configuration which is not compatible with headers set by identity server. To update this configuration:

- Go to `/k8s/helm` folder and type `kubectl apply -f aks-httpaddon-cfg.yaml`. This will update the config map used by AKS nginx ingress controller
- Delete the nginx ingress controller pod to force a refresh of the configuration map. To find it type: `kubectl get ing -n kube-system` and find one pod named `addon-http-application-routing-nginx-ingress-controller-<some-suffix-here>`. Now type `kubectl delete pod <name-of-pod> -n kube-system`. This will delete the pod and it will be recreated.

**PART 2: Deploy (or redeploy) eShop**

- Do a pull of `dev` branch to get the latest changes
Now, you can deploy the eShop using Helm, and **it should work**

Please, let me know if this solves your issue.

**Comment by jijiechen** [comment]
Yes, issue fixed.
Thank you. How is the issue occurred?

BTW, to fix it manually, I tried to add `IssuerSigningKey` for `TokenValidationParameters` that used in api gateway authorization, but got signature validation failures. I thought is could be sig issues. In the sample code, why the the JWT could be validated without validating the signature by a public key?

**Comment by eiximenis** [comment]
Hi,
The issue was a bad configuration in the api gateways. So, basically there is a configuration variable (`IdentityUrl`) witch contains the URL of the Identity Server. This is used by auth middleware to get the public key for validating the token.
The name of this variable was wrong in the configuration map deployed by Helm Charts. So, the API gateways could not reach Identity Server to get a public key for token validation :)

**Comment by jijiechen** [comment]
Thanks for the clarification.
That helps a lot.
