### ISSUE TITLE
Identity.Api cannot authenticate itself

### ISSUE THREAD

**Issue by araselahi** [dotnet-architecture/eShopOnContainers#698]
When you decorate any controller actions in Identity.Api service with [Authorize] attribute, any request to it with a valid token cause the below result:

Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
Microsoft.AspNetCore.Mvc.ChallengeResult:Information: Executing ChallengeResult with authentication schemes ().

I have simply created a user profile page and action and I want to secure it with [Authorize] attribute. Any other services can authorize the access token except Identity.Api itself! I'm running them standalone on IIS Express.

**Comment by mvelosop** [comment]
Hi @araselahi,

Identity.Api IS authenticated everywhere, it just doesn't need the [Authorize] attribute because that's handled by the `app.UseIdentityServer()` middleware in `Startup.cs`.

Actually, the [Authorize] attribute is part of MVC, not IdentityServer, and that's why the use their middleware.

You can actually get a clue when you look at the [AllowAnonymous] attributes in some actions on AccountController.

Anyway, you can register a new user by navigating to http://localhost:5105/Account/Register, which is what the webapps do, only they also include a returnUrl that must be registered as a valid one in IdentityServer.

Just take a detailed view at AccoutController.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue, but feel free to comment though, will reopen if necessary.

**Comment by araselahi** [comment]
Thank you @mvelosop your explanation help me so much.

It seems that IdentityServer authenticate user with '.AspNetCore.Identity.Application' Cookie not 'JwtBearerToken'. Is that mean I should provide this Cookie for every requests to IdentityServer for the user to be authenticated? If answer is 'Yes', it is somehow ambiguous because in this application all the services have been configured to use JwtBearerToken for authentication. Actually I could not configure **IdentityServer** to use **bearer scheme** with popular code snippet:

`            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;

            }).AddJwtBearer(options =>
            {
                options.Authority = identityUrl;
                options.RequireHttpsMetadata = false;
                options.Audience = "identity";
            });
`
Every login request with this configuration will failed and cause to return to login page again. 

Finally I decide to bring out my any added resources from IdentityServer to a new service. But I do not know what to do with 'User' and 'Role' update actions that belongs to IdentityServer itself. Am I in the right direction at all?

**Comment by mvelosop** [comment]
Hi @araselahi,

I haven't gone too deep with authentication but AFAIK it uses JWT, configured with this code in the MVC Startup.cs file:

![image](https://user-images.githubusercontent.com/7357806/44266276-dff81c80-a221-11e8-9a51-7a8b3e23a437.png)

You might find more information here:

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-2.1
https://github.com/aspnet/Security

Best.
