### ISSUE TITLE
Reason of "IntegrationEvent" suffix

### ISSUE THREAD

**Issue by LucaMahler** [dotnet-architecture/eShopOnContainers#710]
https://github.com/dotnet-architecture/eShopOnContainers/blob/a2bc8aa56777126d34cd0435195e8c040a91aef7/src/BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.cs#L23

Why do you presuppose an integration event suffix in the first place and why do you remove it for the Service Bus rule?

Why should I name my event type `OrderPlacedIntegrationEvent` instead of `OrderPlaced`?

Is this documented?

> Btw: There is a typo in the constant -> `SUFFIX` has a double-F.

**Comment by mvelosop** [comment]
Hi @LucaMahler, that's a very nice question! 👍

The suffix is useful to differentiate between the two types of events that exist when working with DDD, briefly:

1. **DomainEvents**: Are events (that occur in a microservice) that have to trigger an action inside the same microservice.
2. **IntegrationEvents**: Are events that have to trigger an action in other another microservice.

There are several implications regrading the type of event:

When a microservice uses DDD patterns, domain events are raised by root aggregates in the Domain layer and integration events are raised by command handlers in the Application layer.

An integration event can be raised as a response to a domain event but not necessarily.

OTOH, by a design decision in eShopOnContainers ([documented here](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/domain-events-design-implementation#single-transaction-across-aggregates-versus-eventual-consistency-across-aggregates)), domain events are handled synchronously, in the same transaction related to the event, without using an asynchronous message queue. 

However, integration events are always handled asynchronously, through some sort of message queue/bus. 

So, since the code you're pointing at belongs to the service bus (i.e. integration events publishing), it's perfectly valid to presuppose all events going through it are IntegrationEvents (again, within the context of eShopOnContainers, that could not be a valid assumption elsewhere).

Hope this helps.

**Comment by CESARDELATORRE** [comment]
That's right. We need to differentiate between DomainEvents and IntegrationEvents, both are explained in the eBook guide: https://aka.ms/microservicesebook 

Keep in midn that we only use Domain Events in the "Ordernig microservice" which is the most complex (with more business logic) microservice with more advanced Domain-Driven Design patterns, like Domain Events.

Closing the issue, but feel free to ask if you have any further question. 👍
