### ISSUE TITLE
Question: SaveChanges() and side effects of a domain event within a logical transaction

### ISSUE THREAD

**Issue by ig16022** [dotnet-architecture/eShopOnContainers#721]
Even though there is an 'await' on 
await _mediator.DispatchDomainEventsAsync(this);

within the Ordering context's SaveEntitiesAsync() method and the base.SaveChanges() will clearly wait for the domain event handlers to complete their work, I also see

await _buyerRepository.UnitOfWork
.SaveEntitiesAsync();

in the domain event handler ValidateOrAddBuyerAggregateWhenOrderStartedDomainEventHandler (Handle() method), and it appears that the buyer will be saved immediately, not as part of a transaction with the Order. This goes against the idea of including Side Effects in an Aggregate's 'save' transaction. Am I not seeing something here?

Additionally, if the domain event handler was creating a new buyer, and the buyer's Id was needed to save an Order, how can this be done with this pattern?

**Comment by mvelosop** [comment]
Hi @ig16022,

It looks like you are right.

We were recently alerted about a related issue (#700) and it looks like there's bug regarding transaction atomicity in domain and integration event handling.

One of the possible solutions could be:

Before saving changes check if there's a transaction and if there's none, create one and only commit the transaction if you (the command handler perhaps) created it. This should handle "cascading" domain events.

Some other change could be handling an in-memory list of integration events, similar to the current domain events list on root aggregates, and committing them all at once within a transaction scope similar to the one mentioned.

Work on this issue is just beginning.

Best.

cc: @unaizorrilla

**Comment by ig16022** [comment]
This helps, thank you.

**Comment by arielmoraes** [comment]
@mvelosop I've modified the code from our application by following your tips. Now it looks like the following:

```csharp
public async Task<bool> SaveEntitiesAsync(CancellationToken cancellationToken = default(CancellationToken))
{
	var alreadyInTransaction = Database.CurrentTransaction != null;
	if (!alreadyInTransaction)
	{
		await Database.BeginTransactionAsync();
	}

	await _mediator.DispatchDomainEventsAsync(this);

	if (!alreadyInTransaction)
	{
		return await base.SaveChangesAsync(cancellationToken) > 0;
	}

	return true;
}
```

Any tips if it can be improved even further? Now I need only to create some kind of queue to achieve idempotency between all of this and the Integration Events.

**Comment by mvelosop** [comment]
Hi @ig16022, @arielmoraes,

This issue was solved, along with https://github.com/dotnet-architecture/eShopOnContainers/issues/828, with the following approach:

1. Begin a transaction in the TransactionBehaviour:
https://github.com/dotnet-architecture/eShopOnContainers/blob/e05a87658128106fef4e628ccb830bc89325d9da/src/Services/Ordering/Ordering.API/Application/Behaviors/TransactionBehaviour.cs#L40

2. While processing the related commands, add the resulting integration events to a list (an outbox):
https://github.com/dotnet-architecture/eShopOnContainers/blob/e05a87658128106fef4e628ccb830bc89325d9da/src/Services/Ordering/Ordering.API/Application/Commands/CreateOrderCommandHandler.cs#L38
  There's a nice detail here, and it's that the outbox is persisted in the DB, so it'd be easy to implement a "watchdog" microservice that would handle possible failures in the publishing mechanism. This is not implemented in eShopOnContainers.

3. Commit the transaction for all changes when returning from the behavior pipeline:
https://github.com/dotnet-architecture/eShopOnContainers/blob/e05a87658128106fef4e628ccb830bc89325d9da/src/Services/Ordering/Ordering.API/Application/Behaviors/TransactionBehaviour.cs#L44

4. Publish all integration events in the outbox:
https://github.com/dotnet-architecture/eShopOnContainers/blob/e05a87658128106fef4e628ccb830bc89325d9da/src/Services/Ordering/Ordering.API/Application/Behaviors/TransactionBehaviour.cs#L48

So this should handle this situation and the one from issue https://github.com/dotnet-architecture/eShopOnContainers/issues/828.

Any comments on this?

**Comment by mvelosop** [comment]
This issue is solved now, so I'm closing it, but feel free to comment, will reopen if needed.
