### ISSUE TITLE
[Bug] Address(Value object) in Order entity has not be saved

### ISSUE THREAD

**Issue by mehdipayervand** [dotnet-architecture/eShopOnContainers#725]
`public class Address : ValueObject
{
 ...
public class Order : Entity, IAggregateRoot
{
   // Address is a Value Object pattern example persisted as EF Core 2.0 owned entity
   public Address Address { get; set; }
   ...`

**Comment by mehdipayervand** [comment]
SQL Profiler:

`exec sp_executesql N'SET NOCOUNT ON;
INSERT INTO [ordering].[orderItems] ([Id], [Discount], [OrderId], [PictureUrl], [ProductId], [ProductName], [UnitPrice], [Units])
VALUES (@p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13);
',N'@p6 int,@p7 decimal(1,0),@p8 int,@p9 nvarchar(4000),@p10 int,@p11 nvarchar(4000),@p12 decimal(4,2),@p13 int',@p6=11,@p7=0,@p8=11,@p9=N'http://localhost:5202/api/v1/c/catalog/items/6/pic/',@p10=6,@p11=N'.NET Blue Hoodie',@p12=12.00,@p13=1`

**Comment by ardalis** [comment]
The SQL you're showing seems to indicate you're adding an OrderItem, not an Order. I wouldn't expect Address to be inserted or updated as part of adding an OrderItem. Presumably the Order (with its address) was created prior to this statement. Do you have the INSERT of the Order itself to show?

**Comment by mvelosop** [comment]
Hi @mehdipayervand,

Yes, we found that recently, the reason is that in PR #560, the Address object properties were changed to pure read-only (just get) which made complete sense at that time.

BUT, the problem is that this also makes the json deserializer unable to assign values upon receiving the integration events at destination.

We'll be working on this shortly, but if you need to fix it fast, just change the properties to `{ get; private set; }`.

The investigation for this was triggered by issue #667.

Hope this helps.
