### ISSUE TITLE
[BUG] First time MVC app runs from Visual Studio MVC app does not get the right layout 

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#729]
First time MVC app in Visual Studio it does not get the right layout. IT doesn't have the padding on the borders and other UI issues because it is not getting the Bootstrap and other files.

Repro:
- Get a clean eShopOnContainers code with `git clone`
- Build/run the app from VS 2017 with F5 or Ctrl+F5

You can see below that the layout is not visually right:

![image](https://user-images.githubusercontent.com/1712635/44818679-c00c1580-ab9e-11e8-9c00-37ea5ef43272.png)

Basically it is because of this issue if running and building the Docker images the first time with Visual Studio:

**Stackoverflow**: https://stackoverflow.com/questions/47999530/visual-studio-2017-docker-change-the-target-for-multi-stage-builds

**POSSIBLE WORKAROUND**
Build and run the first time, at least once, the application with:
 `docker-compose up`
From the root folder of the solution.
This workaround will run all the stages in docker multi-stage including the `npm install` commands that are not being run when building from Visual Studio. After that, the code will have the needed files for additional docker images built from VS.
You can test it on http://localhost:5100/ 

After running  `docker-compose up` once, then:
- Stop it and do a  `docker-compose down`
- Delete the MVC image created by Visual Studio.
- Build images and run it from Visual Studio. You should see it right, like the following screenshot:

![image](https://user-images.githubusercontent.com/1712635/44825748-e04ccc00-abc0-11e8-84ea-03cb0f54eb27.png)

**FIXES TO DO**

Option A. If we get rid of Bower and update the MVC app, we might solve this issue during that task.

Option B. Fix with current approach in eShopOnContainersAI: https://github.com/dotnet-architecture/eShopOnContainersAI/pull/117/files

**Related issues and posts for this problem (in eShopOnContainersAI, in these cases):**

https://github.com/dotnet-architecture/eShopOnContainersAI/wiki/11.-Regression-:-Sales-Forecasting#step-4-setup-web-dashboard-project

**Stackoverflow**: https://stackoverflow.com/questions/47999530/visual-studio-2017-docker-change-the-target-for-multi-stage-builds

**Comment by ramonTC** [comment]
Bug fixed.

**Comment by rafsanulhasan** [comment]
@CESARDELATORRE Since Bower has been removed, there should be mechanisms to manage client-side libraries (or anything that replaces Bower). IMHO, the better choice should be Library Manager. Without the presence of such thing make it ambiguous and thus raises confusion. I've added Library Manager in this PR  #758. I know this is not the current priority as you previously described. But it would at least clears the confusion out that what client-side libraries are being used and from where. In addition to that Library Manager allows us specifying what files we actually need and this makes the app lightweight (like Bower downloads some additional metadata files such as bower.json and so on). If you have schedule, please look at that.

**Comment by rafsanulhasan** [comment]
@ramonTC has done an excellent job with his bugfix and that's what I wanted to tell you @CESARDELATORRE, what @ramonTC did is removed bower and used libman.json for Library Manager. But  where is bootstrap? and there should be some files specified in order to omit the unnecessary file. Please look at my PR. though it is quite big :(.

**Comment by eiximenis** [comment]
Hi @rafsanulhasan 
One question: what do you mean by "where is bootstrap"? Bootstrap is defined in libman.json:

```
    {
      "provider": "unpkg",
      "library": "bootstrap@3.3.7",
      "destination": "wwwroot/lib/bootstrap/"
    },
```

Do you refer to something else?

**Comment by rafsanulhasan** [comment]
@eiximenis I can see it. in the latest merge, you'll see the bootstrap declaration in this [commit](https://github.com/sicsbd/eShopOnContainers/pull/25/commits/9d194ac097acac3fa249d90f937179544d9d8c69).

**Comment by mvelosop** [comment]
Closing this issue as it seems to be solved now. Will reopen if needed.
