### ISSUE TITLE
Automatic changes in files

### ISSUE THREAD

**Issue by rafsanulhasan** [dotnet-architecture/eShopOnContainers#741]
@CESARDELATORRE @mvelosop @eiximenis, When working in VS, I don't know how, some files are automatically changed including _site.min.js_, _site.min.css_ and so on which causes the file to be changed in source control while I didn't make any change.

Also, when installing/uninstalling bower/npm packages the changes should also be excluded from source control.

I have a fix on this issue (PR #740)

**Comment by mvelosop** [comment]
Hi @rafsanulhasan,

This happens because of [bundling and minification](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-2.1&tabs=visual-studio%2Caspnetcore2x)

So all files that are the result of bundling and minification as per bundleconfig.json, could be excluded from source control, while the sources used in the same file MUST BE included.

Hope this helps.
