### ISSUE TITLE
Handle platform lifecycle events

### ISSUE THREAD

**Issue by Ulf-Ason** [dotnet-architecture/eShopOnContainers#750]
I cannot find how this application handles platform lifecycle events, for example when the application has been destroyed by operative system because of low memory and you need to restore the gui to previous state. Where and how is this handled?

**Comment by mvelosop** [comment]
Hi @Ulf-Ason, that's a good question!

In general, there should be no state stored in the microservices so it shouldn't matter if a microservice is taken down.

A real world web app would [work with a distributed cache](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.1) to keep session and app state out of the server and would [configure it in Startup.cs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-2.1#configure-session-state).

However, eShopOnContainers doesn't handle this because it's a learning resource.

That's also the reason that even database related services (SqlServer, MondoDb, Redis, RabbitMQ ) are handled as plain microservices.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue, but feel free to comment, will reopen if needed.
