### ISSUE TITLE
WebSPA is not being started

### ISSUE THREAD

**Issue by rafsanulhasan** [dotnet-architecture/eShopOnContainers#765]
Hi team, 
Before the last change you merged, there was no problem running both MVC and SPA front-end app. But now I am unable to run SPA webpage because it says `404 Not found` and sometimes `The page you are trying to reach is not available at this moment`. When I debug the program, I got that it is trying to access the site before it has been migrated or doing the seedwork.

What can be a possible workaround to resolve the issue?

**Comment by CESARDELATORRE** [comment]
Before what change do you mean?
We’ll check this out tomorrow.
Thanks for the heads-up

**Comment by CESARDELATORRE** [comment]
Hey! - I just checked it out in a clean computer, just installed Docker for Windows, new clone from eShopOnContainers, a new/clean "docker-compose build" and "docker-compose up", and both apps (MVC and SPA) are working properly, as you can see below:

![image](https://user-images.githubusercontent.com/1712635/45267770-2e1acd00-b428-11e8-9e1e-79c22ecde175.png)

Closing this unless there's another issue, ok?

**Comment by CESARDELATORRE** [comment]
And btw, remember that in order to run the SPA app from Visual Studio, you have to follow these steps first:

https://github.com/dotnet-architecture/eShopOnContainers/wiki/06.-Setting-the-Web-SPA-application-up

I double checked that the SPA works from VS, as well. But you need to go through those steps because the `npm install` and `npm run build:prod` commands are not properly executed by VS when building the Docker images.
