### ISSUE TITLE
[Question] Why is the Ordering.BackgroundTasks an IWebHost and not an IHost?

### ISSUE THREAD

**Issue by PureKrome** [dotnet-architecture/eShopOnContainers#769]
Hi again 👋 

I'm just trying to understand how eShopOnContainers handles background tasks, like timer or queue triggers ... and how this relates to Docker. (Previously, I leveraged WebJobs for this stuff)

I've noticed that there's [an `Ordering.BackgroundTasks` project](https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/src/Services/Ordering/Ordering.BackgroundTasks). In here, it's [an `IWebHost`](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.BackgroundTasks/Program.cs#L14) with [a single `IHostedService` service that is DI'd](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.BackgroundTasks/Startup.cs#L53).

e.g.

- `public static IWebHost BuildWebHost(string[] args) => .... `
- `services.AddSingleton<IHostedService, GracePeriodManagerService>();`

Is there a reason for making this app a `WebHost` (aka a tiny/lite website?) Is it purely because this code is all based on .NET Core 2.0 and even though the project _definition_ has been upgraded to 2.1, the code hasn't (like my PR #768 which starts to do this?)

thanks kindly!

**Comment by CESARDELATORRE** [comment]
Very good question. 👍 I've been tempted to migrate it to a IHost, since it'd work the same way.
The only reason why it's IWebHost instead of IHost is because we're also using here Http in order to discover about its HealthCheck by using the DogWatch app asking to the Http HealthCheck of this service. Other than that, this background-tasks service could simply be based on an IHost.

In your code, it is up to you, for sure, being just an IHost would consume less resources, too. But the HealthCheck would need to be done in a different way... 

Also, good catch, I've just accepted your PR so we use the final implementation from the NuGet. 
Thanks! 👍

**Comment by CESARDELATORRE** [comment]
Closing the question, if it is clear now. 👍

**Comment by PureKrome** [comment]
Sweet - question is mostly answered. 

1. eShop is doing [a very simplistic TIMER based trigger](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.BackgroundTasks/Tasks/GracePeriodManagerTask.cs#L39)? So if you want to do more `cron` time'd events, this isn't the way to do it?

2. I'm still not sure where QUEUE based triggers come into play?  Again, it would be very simplistic if it was custom code, like ... check if queue has messages ... pop and handle .. else Task.Delay?

3. How does Azure Functions/Webjobs come into play, with respect to eShop on Containers? As in... if we wanted to use AzureFunctions or Webjobs with Queue/Time triggers, would that be outside of this solution or can those be Containered somehow?

Or instead of queue triggers, do we use Events instead (like in the `GracePeriodManagerTask` background task) and the tasks will then respond to events?
