### ISSUE TITLE
Question: health checks in MVC serivce

### ISSUE THREAD

**Issue by dzoech** [dotnet-architecture/eShopOnContainers#775]
I have a problem understanding the health checks implemented in the MVC service: When executing a health check, the MVC service checks the health of all downstream services (catalog, ordering, basket, etc.) as well. If I understand correctly, the whole MVC service won't be served or even killed/recycled in case one downstream service is failing. Shouldn't the MVC service itself cope with the unavailability of a certain service (e.g. ordering) and, for instance, still allow the user to browse the catalog?

**Comment by CESARDELATORRE** [comment]
The Healhchecks just tell you about its state. The containers in a Docker host don’t get killed/recycled by the HealthCheck system. That decision could be done by the orchestrator such as Kubernetes if you integrate the HealthChecks to it.
In regards the MVC web app, in fact you can browse the catalog even when the Ordering microservice might be down. Of course, it will need the catalog microservice.

**Comment by dzoech** [comment]
Sorry, I didn't mention was talking in the context of Kubernetes. I assumed the health check endpoint would be used by Kubernetes for the readinessProbe and livenessProbe. Am I correct in the assumption that the current health checks implementation (which requires all downstream services to be functioning) are not suited for these probes due to my above mentioned concerns?

**Comment by eiximenis** [comment]
Hi @dzoech 

Yes, you are absolutely correct. Current healthchecks implementation in MVC client is suitable for readiness probe of k8s but not for liveness probe.

Just fyi this is due a limitation of the healthchecks version used and it will be refactor as we will start using the new healthcehcks library in netcore 2.2 that allows for a different set of probes for readiness and liveness scenarios.

**Comment by eiximenis** [comment]
Yes you are true. No MVC instance will serve traffic, however k8s won't restart the MVC pods. 

The key point here is: an unavailable dependency must make the whole MVC unavailable? If answer is no, then this dependency should not be part of any probe, and error should be handled manually. If yes, then dependency should be part of readiness probe. So, probably in ordering service you're right and it should not be part of readiness probe (and if I remember well, the MVC deals with ordering service errors). And probably catalog service could really be part of readiness probe because a failing catalog service will make the whole MVC unavailable.

We are not currently using k8s probes, and healthcheck info is used to populate webstatus data. When we update to new healthchecks in netcore2.2 we plan to add k8s probes, so this is a good discussion to have :)

**Comment by dzoech** [comment]
Thank you for clarification. I wasn't aware the health checks are solely used for informative purposes. 
I'm looking forward for the health check implementation in 2.2 :) 
Thanks again and have a nice day.
