### ISSUE TITLE
Slowing speed when start project

### ISSUE THREAD

**Issue by SaMirzaei** [dotnet-architecture/eShopOnContainers#784]
Hi
After any change in the project and build/run that, It so boring because I have to wait to publish all of the services and project in Docker.

Have any way to run the project in the local system instead of docker?
What should I do for more speed in developing?

Thanks

**Comment by CESARDELATORRE** [comment]
Usually, in development, you would be compiling/testing a single microservice probably testing it with Swagger, etc. so it wouldn’t take so much time.
But for just testing/running, you can do a “docker-compose Build” just once (it’ll take its time) and then whenever you want to just sun it just do a “Docker-compose up” and since the images will be built, it’ll take much less time.
Another possibility is to use Kubernetes and Azure Dev Spaces (in Preview). We’re going to try to make it work for eShopOnContainers.
Closing, as this is not really an issue.
