### ISSUE TITLE
Question: What is required to 'productionize' eShopOnContainers

### ISSUE THREAD

**Issue by benbuckland** [dotnet-architecture/eShopOnContainers#831]
Hi there, I a m continuing to love the eShopOnContainers reference application, I have learnt a tremendous amount in a short time and I thank you for that.

In a number of locations in documentation it makes the comment that it is 'not production ready code'. Given the types of comments and issues other users are raising I'm guessing they are not just 'playing around' with the code.

I am wondering if some guidance on what would be required to take eShopOnContainers into a production environment would be useful?

Thanks again, Ben.

**Comment by CESARDELATORRE** [comment]
Hi Ben. Unofficially, folks might be using this code for production, but since this is a sample/reference application, we cannot support it as "production-ready" code and therefore we need to say it in a disclaimer so in case anyone have issues in production we are not responsible for it.

In a different page, what you need to make it "production ready" is to move all the infrastructure assets such as SQL, Redis, RabbitMQ and Mongo to High Available services like the ones in Azure. Also, you'd have to deploy into an scalable orchestrator such as Kubernetes or Service Fabric instead of a single Docker Host.

Thanks for your feedback! 👍

**Comment by CESARDELATORRE** [comment]
@benbuckland - Would you and your company be interested to provide your feedback about using eShopOnContainers and our guidance, then migrating infrastructure to Azure? - We'd love to hear about your journey/experiences, what you liked, where you are finding pain points and how we can improve the guidance. :)

**Comment by CESARDELATORRE** [comment]
@benbuckland - Cool! - Send an email saying that I offered you and your company to provide feedback, to the following email addresses. 
@nishanil will follow up with you, ok? :)

- Nish Anil : nanil at microsoft.com
- Cesar de la Torre : cesardl at microsoft.com
- Ankit Asthana : aasthan at microsoft.com

Thanks! 👍
