### ISSUE TITLE
Docker does not understand "volumes" config

### ISSUE THREAD

**Issue by khanhpv** [dotnet-architecture/eShopOnContainers#853]
**specification**:
* windows 10 home
* docker-toolbox

**problem**:
everything runs ok, but, webshoppingapigw, webmarketingapigw, mobileshoppingapigw, mobilemarketingapigw do not run.
![image](https://user-images.githubusercontent.com/3120540/48614095-06b02580-e9c0-11e8-8a65-6ed8b223f738.png)

**stderror**:
![image](https://user-images.githubusercontent.com/3120540/48613812-52ae9a80-e9bf-11e8-93de-6b53bbe770ca.png)

It seems volumes config can not be understood by docker on windows 10 home.

Please help me.
Thanks

**Comment by CESARDELATORRE** [comment]
We don't support Docker toolbox but "Docker for Windows" or "Docker for Mac" (under the cover it uses a Linux VM when using Linux Containers which is our by-default environment)
So, please, install "Docker for Windows" instead of Docker Toolbox which is also being deprecated by Docker.
Install Docker for Windows:
https://docs.docker.com/docker-for-windows/install/

Also, see the requirements for eShopOnContainers:
https://github.com/dotnet-architecture/eShopOnContainers/wiki/00.-Dev-machine-requirements
