### ISSUE TITLE
[Question] Identity Microservice needed when using Azure AD?

### ISSUE THREAD

**Issue by Eltargrim** [dotnet-architecture/eShopOnContainers#857]
First, thanks so much for putting together this example and documentation. It's proving to be a huge help for me as I look toward building my first microservices application.

My main question is around the identity microservice and whether this is a recommended component to pass through when using an external identity provider such as Azure AD? Could this service effectively be replaced by Azure AD? IOW, would you simply use ADAL with your client apps and perform authorization checks at the API Gateway and/or endpoints?

**Comment by eiximenis** [comment]
Yes, you can.
But our current implementations ties de identity microservice and the profile api. So, if you are going to use an external identity provider like AD then you should build a profile microservice for storing/getting the user profiles.

**Comment by mvelosop** [comment]
Hi @Eltargrim, 

AFAIK, you just need somewhere to get the user profile from. In eShopOnContainers user profiles are in the Identity.Api just because but they could be anywhere.

So, if AD has what you need you might just use it and that's it. I'd say it's even better, because then you have one thing less to worry about in your app, without mentioning all security/privacy concerns you'd have to consider if you decide to implement it yourself.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue as it seems stale, but feel free to comment, will reopen if needed.
