### ISSUE TITLE
[Question]: Deciding on aggregates

### ISSUE THREAD

**Issue by ADringer** [dotnet-architecture/eShopOnContainers#862]
Hi,

I'm wondering how you decide whether to use a root aggregate or inline the data in another row. For example in this solution, the Order service has an `OrderItem` which holds the product name and picture url. What decided to add these properties and not have a `Product` aggregate?

For what I'm working on I have an event (e.g. marathon) which has a number of participants (so similar to order and orderItems). For each participant of the marathon I also save their name and picture url.

I could either:

1. Save the person's details within the participants data
2. Have a user aggregate and then a UserId property on the participant that links to this.

My main issue with deciding is with IntegrationEvents for when the user changes either their name or picture. Depending on the above implementation I'd have to

1. Pull out every event in the system and loop through each one and see if the user is a participant of the event, and update if they are. Similiar to how the basket is updated of a product price change, but this will be an ever increasing number of events, not a temporary list like a basket so potentially could be a very large number of events.
2. Just pull out the user aggregate and update that one record.

Using the aggregate makes maintenance a lot easier as it's a simple update, but then the initial creation would be easier without it.

Are there any other factors that I need to consider? Or have I kind of answered my own question with the maintenance issue?

Thanks

**Comment by mvelosop** [comment]
Hi @ADringer,

The main issue here is considering the business needs, for example (and I'm just guessing), since this is an ordering microservice, the business owner might have decided that it's better that the customer always sees the same picture and description valid at ordering time.

Any way, this is just a sample so, in the context of eShopOnContainers, this is a good solution.

One important criteria for selecting the root aggregate is that of ensuring consistency, in this case, the order aggregate makes a lot of sense, because it's the order that controls the addition and removal of items, as in once the order is approved you can't add or remove items (in this simple example), so items can't just be a List<T> that anyone can modify without the order knowing.

But it's important to keep in mind that you don't need an aggregate for every entity in your application, for example, in eShopOnContainers, the Catalog Items is just a simple CRUD microservice, because there are no business rules regarding catalog items, the way there are with order items.

So, as usual, it's a definitive "it depends", but these are the kind of guidelines that should be considered for selecting aggregates.

I guess you might have already read it, but the [The Aggregate Pattern section](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/microservice-domain-model#the-aggregate-pattern) on the Microservices Guide and the additional resources links might can get you on the way.

Hope this helps.

**Comment by CESARDELATORRE** [comment]
@mvelosop Thanks Miguel! You got it! It feels like it was my words saying that above. 👍 
I would also add that the way you should usually define the Aggregate's boundaries is by thinking on your transactions.
In addition to the [Aggregate Pattern](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/microservice-domain-model#the-aggregate-pattern) section that I wrote on the Microservices Guide, I also recommend to read these two whitepaper (I and II) by Vaughn Vernon:
[Effective Aggregate Design by Vaughn Vernon](http://dddcommunity.org/library/vernon_2011/) 

Also, note that Aggregates are great when you have certain complexity in your business rules and transactions, but there are simpler microservices that might not need DDD patterns and can be simple CRUD. Even more, within a microservice where you use Aggregates for the transactions/updates, when querying, you don't need the constraints derived from Aggregates and that's why we also propose to use a simplified CQRS so queries are "free" to access/join any table within the microservice, as needed. Aggregate's constraints are critical for the updates/transactions, but queries are idempotent, no matter how many times you run queries, they won't change the data, therefore, no need to have the Aggregate's constraints for the queries, just for the updates/transactions which start from the Commands.

**Comment by mvelosop** [comment]
Hey @CESARDELATORRE, thanks! having read the guide several times now I'm starting to get it 😉

**Comment by mvelosop** [comment]
Closing the issue now, but feel free to comment, will reopen if needed.
