### ISSUE TITLE
Question: How would you design an admin panel for microservices?

### ISSUE THREAD

**Issue by w00519772** [dotnet-architecture/eShopOnContainers#864]
Thanks again for developing this app.  I don't believe it has an admin panel.

I believe there are a number of options available for an admin panel:

1) separate mvc app like described here: https://marmelab.com/blog/2014/12/19/microservice-administration-with-ng-admin.html.  Call the project: WebMVCAdmin?

2) add admin area to WebMVC project.

3) separate admin project per microservice.

4) other option?

I believe option 1 is most suitable (I could be wrong), so I wanted to check.

**Comment by CESARDELATORRE** [comment]
Yeah, we didn't create any admin panel simply because of scope.
You don't need to create additional microservices, only to secure them, especially the UPDATE methods.

However, there's a very simple Watchdog app for monitoring HealthChecks. You could do something similar but extending to additional features. 

About the app, I would say #1 is better because of decoupling from the public eShop.

Instead of ASP.NET Core MVC you might want to try ASP.NET Core Razor which is simpler and faster for developing web UI apps.

Closing this issue, since it is just informative. 👍

**Comment by w00519772** [comment]
@CESARDELATORRE, thank you for the response.  I have opened another issue here: https://github.com/dotnet-architecture/eShopOnContainers/issues/869.  It should be a question rather than an issue.  Therefore please close it?  It would be great if you could answer it as well as your answers are informative.
