### ISSUE TITLE
Should the domain model be completely isolated?

### ISSUE THREAD

**Issue by w00519772** [dotnet-architecture/eShopOnContainers#869]
Thanks again for developing this app.  I am enjoying learning more about it.

Domain Driven Design states that you should have a domain model, which reflects the ubiquitous language used by the domain experts. I see that you are using EF Core and have the ORM mapped to the Domain model in the Ordering microservice.  I have two questions:

1) How would you deal with a many to many relationship? I believe you have to create a join Domain entity with EF Core as described here: https://github.com/aspnet/EntityFrameworkCore/issues/1368.  Is that how you would do it? Some argue that this would "pollute" the domain model.  It could also mean that you have class names that do not reflect the ubiquitous  language used in the domain.

2) Would you ever have a completely isolated domain model i.e. a domain model that is not mapped to a relational database? I believe a separate domain model would make change tracking harder.

**Comment by CESARDELATORRE** [comment]
The Domain Model should be isolated meaning that other parts of the application depend on the model, but the model classes must not depend on anything but themselves, they must be POCO classes. Entity Framework complies with that since your entities are just POCO classes and the mapping between the entity classes and the database is performed under the covers without contaminating the Domain Entity classes. In the entity classes you have only your code.
 
- Many to many relationships? - I see no issues on that, within the same Aggregate you can establish 1:1, 1:Many or Many:Many relationships.
However, between different Aggregates, you should not have explicit relationships using Entity Framework. If there are relations between different aggregates should be based just on the IDs/Keys and Foreign Keys, but without explicit relationships in EF, meaning no navigation between Aggregates.
In nay case Aggregates should be uses for transactions, most of all.
You can have a CQRS approach and segregate the queries from all the Domain Model. You can use the Domain Model nd all the DDD constraints only for the transactions/updates. For queries you can have  separated code since queries don't impact the data and might be more flexible for queries to use a different data model based on the same physical tables where you can use any kind of join, etc.

See how we implemented that approach in the Ordering microservice. Queries are segregated from the DDD/Aggregates model by using a simplified CQRS approach against the same database. It is explained in the book, as well.   

2. Again, isolated model doesn't mean that it cannot be mapped to a relational database. It can be mapped to a relational database by using Entity Framework or any other ORM as long as the Entity Model classes do not depend on any library or infrastructure. That's what means "isolated model".

3. About change tracking, take into account that the Domain Entities are used only in the "server side", so change tracking (connected EF DbContext managing all the changes) is only needed while running the transactions. When you return data to the client side, you return DTOs in the form that the client app needs it better. You must not send the Domain Entities to the client side.

$. For transactions, you start from the client side sending data related to the transactions in the form of a Command, which is a simple class, like a DTO, but sending the data related to the business operation/Command. That will start the transaction with the Domain Aggreegates.

**Comment by w00519772** [comment]
@CESARDELATORRE 

Thank you.  I think I agree with your definition of isolation with regards to point two.  

With regards to point one; say I had the classes below (which I took from here: https://www.learnentityframeworkcore.com/configuration/many-to-many-relationship-configuration):

public class Book
{
    public int BookId { get; set; }
    public string Title { get; set; }
    public Author Author { get; set; }
    public ICollection<BookCategory> BookCategories { get; set; }
} 

public class Category
{
    public int CategoryId { get; set; }
    public string CategoryName { get; set; }
    public ICollection<BookCategory> BookCategories { get; set; }
}

public class BookCategory
{
    public int BookId { get; set; }
    public Book Book { get; set; }
    public int CategoryId { get; set; }
    public Category Category { get; set; }
}

It does not seem right adding BookCategories to Books and BookCategories to Categories.  In my mind Books should be added to Categories and Categories should be added to Books.

I don't believe eshopcontainers has an many to many relationships.  However, if it did then would this make you choose another ORM or am I overthinking this?

**Comment by gojanpaolo** [comment]
Defining the join entity (i.e. `BookCategories`) on `Book` and `Category` seems fine to me. That's exactly how the models will be related and you're just **explicitly** defining it. Of course it is nice/convenient to not define the join entity yourself. But keep in mind that when EF Core can handle many-to-many relationships without an **explicit** join entity, EF Core will still create that join entity **implicitly**.

If you want to hide the join entity on the domain classes consumers, you can follow [this blog post from Arthur Vickers](https://blog.oneunicorn.com/2017/09/25/many-to-many-relationships-in-ef-core-2-0-part-2-hiding-as-ienumerable/).

**Comment by mvelosop** [comment]
Closing this issue now as it seems to be solved, feel free to comment though, will reopen if needed.
