### ISSUE TITLE
Build fails with "sha256sum is not recognized as an internal or external command" error message

### ISSUE THREAD

**Issue by Arash-Sabet** [dotnet-architecture/eShopOnContainers#879]
The following code snippet is a part of a docker file targeting Windows containers. The issue is that we receive this error  **[0m[91m'sha256sum' is not recognized as an internal or external command,** when compiling/building in VS 2017. We also tried microsoft/dotnet:2.1-aspnetcore-runtime but it exhibited the same issue too. Wasn't the issue already resolved per #630?!

```
FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
	ENV NODE_VERSION 8.9.4
	ENV NODE_DOWNLOAD_SHA 21fb4690e349f82d708ae766def01d7fec1b085ce1f5ab30d9bda8ee126ca8fc
	RUN curl -SL "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.gz" --output nodejs.tar.gz \
    && echo "$NODE_DOWNLOAD_SHA nodejs.tar.gz" | sha256sum -c - \
    && tar -xzf "nodejs.tar.gz" -C /usr/local --strip-components=1 \
    && rm nodejs.tar.gz \
    && ln -s /usr/local/bin/node /usr/local/bin/nodejs
```

As a side note, I am opening this issue because it's happening in a separate project which is not the same as eShopOnContainers.

**Comment by eiximenis** [comment]
Hi!
Which branch are you using?

I can't see following code in `dev` branch.

**Comment by Arash-Sabet** [comment]
I meant building the container failed due to the lack of support of sha256sum in windows-based images. We had to remove sha256sum at all to get going.

**Comment by mvelosop** [comment]
Hi @Arash-Sabet,

Is this related to eShopOnContainers?

**Comment by mvelosop** [comment]
Hi @Arash-Sabet, I'm sorry I didn't read your clarification on the initial post!

You can think of a Dockerfile as some kind of a batch file so it's just sending commands to the OS where the image is being built.

So sha256sum is a command that's available on the original environment but it isn't in the current one, so it should be fixed by installing that program in the current environment.

However, that code looks more like it's targeting Linux containers than Windows containers.

I'm closing this issue now, but feel free to comment.
