### ISSUE TITLE
Question: Identity.API

### ISSUE THREAD

**Issue by D3MaxT** [dotnet-architecture/eShopOnContainers#892]
Hello,
I just have a quick question on the Identity microservice.

Why is this labeled as an API, if it has no API controllers and serves no REST?
Seems like it has the regular MVC with views for the login/logout UI. Shouldn't this be marked as WebMVC instead of .API?

Not criticizing or anything, just genuinely trying to understand.
Thank you.

**Comment by mvelosop** [comment]
Hi @D3MaxT,

It's actually an API project, only you don't get to see the API controllers because they are included in the **IdentityServer4.AspNetIdentity** package.

The MVC controllers just handle the minimum UI used for logging in and managing the user's own profile.

To get further details you can see the excelent Identity Server 4 documentation site: http://docs.identityserver.io/en/latest/index.html

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now as it seems to be solved, feel free to comment though, will reopen if needed.
