### ISSUE TITLE
Does CORS need to be set for the Xamarin client?

### ISSUE THREAD

**Issue by davidbritch** [dotnet-architecture/eShopOnContainers#905]
When the list of scopes is built to allow access to the Identity API, the Xamarin client sets `AllowedCorsOrigins` property to "http://eshopxamarin":

https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Identity/Identity.API/Configuration/Config.cs#L77

I'm not convinced this is necessary, as the `AllowedCorsOrigins` property is typically used for building a CORS policy for JavaScript clients. This is further evidenced by the fact that the JavaScript client sets the property, but the MVC and MVC test clients don't.

Thoughts?

**Comment by mvelosop** [comment]
Hi @davidbritch,

I haven't really worked with Xamarin, but from just a general web development view, I don't think it's necessary either.

AFAIK, CORS if a way of protecting JS running in the browser, so if some rogue JS gets injected, because of a non https connection for example, it just can't connect to unauthorized sources.

So, since you don't have a JS client, but Xamarin, I don't think the CORS policy has any use.

Hope this helps.

**Comment by mvelosop** [comment]
Hi @davidbritch, did you decide on this issue?

Didn't get much input, but IMHO, I think you're right about removing it.

**Comment by davidbritch** [comment]
@mvelosop 

I agree completely that the property should be removed. Whilst it's not causing any harm, it is causing confusion. However, I don't have any time to deal with this until after //build.

**Comment by mvelosop** [comment]
Hey @davidbritch, great! Do you want to leave this issue open as a reminder?

**Comment by davidbritch** [comment]
Doc updates, however, won't be made in the near future.
