### ISSUE TITLE
Can the write database be different to the read database in terms of the data it holds i.e. fields/tables included in one that are not included in the other?

### ISSUE THREAD

**Issue by w00519772** [dotnet-architecture/eShopOnContainers#915]
Thanks again once again for developing this app.  I am developing an application using the CQRS pattern.  The read database is: MongoDB (NoSQL) and the write database is SQL Server.

Please see the code below:

```
public class Product
    {
        public Guid Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }

        public void LookupDescriptionByCode(List<ProductDescriptionLookup> productCodes)
        {
            Description = productCodes.Find(x => x.Code == Code).Description;
        }
    }

    public class ProductDescriptionLookup
    {
        public Guid Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    }

```
The database (lookup tables) looks like this:

[create table ProductDescriptionLookup(Id uniqueidentifier, Code varchar(100), Description varchar(100))
insert into ProductDescriptionLookup (Id,Code,[Description])
values (newid(), 'prod1','Product1')](url)

Here is some test code for the write side:

```
[Fact]
        public void Test()
        {
            List<ProductDescriptionLookup> list = new List<ProductDescriptionLookup>();
            list.Add(new ProductDescriptionLookup { Id = Guid.NewGuid(), Code=  "prod1", Description="Product1" });
            Product p1 = new Product { Id = Guid.NewGuid(), Code = "prod1", Description = "" };
            p1.LookupDescriptionByCode(list);
        }
```

Here is the read model (which is mapped to a MongoDB database):

```
public class Product
{
	public Guid Id { get; set; }
        public string Description { get; set; }
}

```
Notice that the Product Code is not even persisted to the read side. Therefore there is no need for the lookup table on the read side (because it will never have to lookup the description by product code). Therefore I am planning to exclude the ProductDescriptionLookup table from the read side. This works perfectly from a technical point of view, however I am wandering if it is frowned upon from an architectural perepective as the read database is now different to the write database?

**Comment by mvelosop** [comment]
Hi @w00519772, as usual, everything depends on the business needs, so that should define the criteria to evaluate.

I'll dare to issue some general comments without knowing the context, so the may not be valid!

To begin with, there's no problem with the read DB being different that the write one. Actually, that's usually the case.

The read database is optimized for the specific needs of the clients that consume it, there could even be several read DBs, so it's perfectly Ok to exclude the product code it fits the business needs.

Using different technologies for read and write DBs is no problem either, the important consideration here is that the technology you choose delivers some advantage over the other options.

One side comment here is that I would've expected to see some document-related structure in the MongoDB model, that is, something with a complex, tree-like model, not like the model you show.

A model like that, being table-like is usually better handled in a relational DB, but then again, I say this without knowing the context.

Hope this helps.

**Comment by mvelosop** [comment]
@w00519772, it's not really that important that it "qualifies" as a tree, I don't know the context, so it's just a general comment.

It's just fine as long as using a MongoDB adds some significant advantage that compensates for the additional development and operational complexity of having two fundamentally different databases in sync.

**Comment by w00519772** [comment]
@mvelosop, I am trying to understand the difference between an Event Log (like this: https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/BuildingBlocks/EventBus/IntegrationEventLogEF/IntegrationEventLogContext.cs)  and an Event Store (like this: https://eventstore.org/).  Is it fair to say that: 

1) An Event Store is an Event Log 
and
2) An Event Log is not necessarily and Event Store

I am thinking of an application, which has one event and would have an EventLog (like the EventLog in eShopContainers) on the write side (Write.api) and a MongoDB database on the read side (Read.API).  The Write.API and Read.API would communicate over RabbitMQ.  There would be no relational database on the write side like eshopcontainers has: https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.Infrastructure/OrderingContext.cs i.e. the EventLog is the write database.

I would be very grateful for your thoughts on this.  It is only a hobby application to learn more about your architecture.

**Comment by CESARDELATORRE** [comment]
@w00519772 - You are right.
An Event Store is "the database" used for [Event Sourcing](https://www.youtube.com/watch?v=8JKjvY4etTY) which is a very specific architectural approach. Even there's a specially made databse for Event Sourcing named EventStore, owned by Greg Young: https://eventstore.org/

An Event Log is not necessarily and Event Store and can be a lot simpler. In our case we just need a log of integration events happening so as part of the "Out Box" pattern, if something goes wrong in the original transaction, you have that log to compensate the issue. In this case, due to transactionality, you probably want the Event-Log to be in the same system than your transactional business database.
But it could be SQL, MongoDB, CosmosDB or if you were using an Event Sourcing approach, an EventStore, of course.

About your questions:
Q1) Is it advisable not to use CQRS for a system that has only one event?
--> It depends. Research CQRS. It could be used even if you have a single integration event. Why not.

Q2) Can the EventLog act as the write database (without a relational database)?
Q3) Could it be argued that the EventLog is the single source of truth for the read model?
--> Those two approaches are not really a simple "EventLog (Log acting as a backup)" but that would be an EventStore, so you'd be using the EventSourcing approach which is for sure the source of truth.
Event Sourcing is very powerful but very specific. You don't have any more  "current state databases" but the history of everything that happened. Then, in order to know what's the current state of any entity/aggregate, you need to re-play de events in the event store. For many systems that is great since you could rewind and know exactly how was your system in the past in a particular day/hour/minute. :)

But Event Sourcing is a different and more complex paradigm than simply using an Integration Event Log.

**Comment by w00519772** [comment]
@CESARDELATORRE, I believe I have two options:

1) Map the Domain Model to a NoSQL database (MongoDB).  MongoDB is used by the read model and write model.  In this case I would only have one api for read and write.
Or
2) Serialize the Domian Model in an event log.  Then create integration events to update the read database (mongodb).  In this case the two databases are accessed in two separate web apis.

With regards to (2) - there is no relational database needed for the write database (because there is only one event) - just an event log (the serialized domain model - contained in a relational database).  The reason I believe the write database would be an event log rather than an event store is because there is one event and therefore I will never have to replay events to build an aggregate.  The event log is only there as a backup and can be truncated periodically.

I would be grateful for your thoughts.

**Comment by mvelosop** [comment]
Hi @w00519772, I think an important part of the learning process is to try things out by yourself, because theory on paper is quite different from real life because of the context.

I'd suggest that you begin to experiment what we've been talking here and decide what's valid for you and what you want to achieve.

However, I want to emphasize that's important to only add the complexity that's really needed to achieve the business goals, and no more that that, because it escalates quite fast and then it gets harder to manage. 

Anyway, I want to call your attention because I think this issue is getting a bit off-topic. Even though it's referencing eShopOnContainers code and concepts, it's not really focused on this app.

Do you think we can close the issue as per the original question? Do you think it has been answered?

**Comment by w00519772** [comment]
@mvelosop, yes the question was answered - thanks for the answers.  I thought a question about the architecture used by eShopContainers would be on topic - apologies if I have gone off topic.

**Comment by mvelosop** [comment]
Hey, no problem @w00519772, this is all fun and it's easy getting carried away 😉

Best.
