### ISSUE TITLE
[Question] IHostService clustered singleton?

### ISSUE THREAD

**Issue by uboznikov** [dotnet-architecture/eShopOnContainers#946]
Target configuration:
Multiple instances of individual microservices with Kubernetes pod clustering, running an IHostService background task.

My question is, how to ensure that only one instance (singleton) will fire? For sure I don't want to have all the instances of the same microservice fire at the same time.

Thanks in advance.

**Comment by ardalis** [comment]
Put the request into a queue. Only one instance will pick up the item from the queue and perform the work.

Will that approach work?

**Comment by mvelosop** [comment]
Hi @uboznikov,

In this case, since what you have are basically competing workers, you need an external synchronization component. 

In eShopOnContainers, synchronization is handled by RabbitMQ, since IntegrationEvents are published through _Publish/Subscribe Exchanges_ and then consumed from _Work Queues_ that deliver the events in a round robin fashion to each worker type, actually identified by the queue name.

Hope this helps.

**Comment by mvelosop** [comment]
Hi @ardalis, I'm sorry, I didn't realize you had answered already!

**Comment by mvelosop** [comment]
It depends on what you consider self-contained, as far as I see it, if the workers are competing, it has to be outside the workers, perhaps a database, and synchronize by locking a record.

**Comment by mvelosop** [comment]
Closing this issue as not related to eShopOnContainers.
