### ISSUE TITLE
Why do Ordering.API Unit Tests reference WebMVC Classes?

### ISSUE THREAD

**Issue by RLashofRegas** [dotnet-architecture/eShopOnContainers#962]
See this issue on stack exchange: https://softwareengineering.stackexchange.com/q/388218/311773

Why do all the tests in the service-specific folders only reference the WebMVC project and not the API project that it is purportedly testing?

**Comment by mvelosop** [comment]
Hi @RLashofRegas, thanks for the heads-up 👍. 

You're right, it's actually a bug.

It was probably just a left over while developing the unit tests, because the methods being tested there are covered in OrderWebApiTest.

I'll remove that, but will try to relocate those tests somewhere, it'd be a pity to lose them 😉

**Comment by mvelosop** [comment]
However API classes are being tested in the project!

**Comment by tranvannhatdev** [comment]
In this addition, should we have a Unit Test for each Ordering.API/WebMVC?
