### ISSUE TITLE
Some warning and issues

### ISSUE THREAD

**Issue by rafsanulhasan** [dotnet-architecture/eShopOnContainers#985]
Hello, 
I'm using using VS 2017 15.9.10 and getting some warnings and errors.
1. Getting errors while building the project, why do we need to run build task for library manager since all the required files are already on the repo (#848)
2. Compiler gives warning about **Razor syntax** for rendering partial pages to be changed to Tag Helpers
3. The NuGet package version conflict: Microsoft.ApplicationInsights
4. Using version in Microsoft.AspNetCore.App
5. Called some deprecated methods in authorize filters & obsolete methods in logging Adding ApplicationInsights in Startup
6. There are some async/await warnings

**Comment by mvelosop** [comment]
Hi @rafsanulhasan, I mentioned this in the PR also, just include here for completeness.

Can't remove building the client-side libraries, because, as usual, they [are not included in version control](https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/src/Web/WebMVC/wwwroot): 

![image](https://user-images.githubusercontent.com/7357806/55477031-041d3800-5610-11e9-993f-1e633031870f.png)

So there's no guarantee that they'll be there when building the project

For example, you have them in your computer because you built the project some time ago, but this wouldn't work if you just fresh cloned the project and tried building it with Docker.

You'd have to build it first in VS, and that's nonsense when working with Docker, so that's why the building from LibMan is important.

**Comment by rafsanulhasan** [comment]
Hi @mvelosop,
Ok, it makes sense. However it that case, I think the files array that specifies the files to be downloaded should be removed because this is the second solution until #848 is fixed which is discussed in this [LibraryManager](https://github.com/aspnet/LibraryManager/issues/111) issue

**Comment by mvelosop** [comment]
Closing this issue now, as it seems stale, but feel free to comment, will reopen if needed.
